fwAlertConfig.ctl File Reference
fwAlertConfig.ctl File Reference
Functions
fwAlertConfig_objectInitialize (dyn_mixed &paramsObject, int totalRanges)
_fwAlertConfig_objectCreateParams (dyn_dyn_anytype &alarmParams, dyn_dyn_anytype &alarmLimits, int totalRanges)
fwAlertConfig_objectSet (string dpe, dyn_mixed alertConfigObject, dyn_string &exceptionInfo)
bool fwAlertConfig_objectConfigExists (dyn_mixed alertConfigObject, int &configType, dyn_string &exceptionInfo)
fwAlertConfig_objectCreateAnalog (dyn_mixed &alertConfigObject, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_bool limitsIncluded, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE)
fwAlertConfig_objectCreateDigital (dyn_mixed &alertConfigObject, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE)
fwAlertConfig_objectCreateDiscrete (dyn_mixed &alertConfigObject, dyn_string alertTexts, dyn_string alertMatch, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, bool impulse, dyn_bool discreteNegation, string stateBits, dyn_string stateMatch, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE)
fwAlertConfig_objectCreateSummary (dyn_mixed &alertConfigObject, dyn_string alertTexts, int threshold, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE)
fwAlertConfig_objectExtractAnalog (dyn_mixed alertConfigObject, int &alertType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClasses, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, dyn_bool &limitsIncluded, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_objectExtractDiscrete (dyn_mixed alertConfigObject, int &alertType, dyn_string &alertTexts, dyn_string &alertMatches, dyn_string &alertClasses, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isDiscrete, bool &impulse, dyn_bool &discreteNegation, string &stateBits, dyn_string &stateMatch, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_objectExtractDigital (dyn_mixed alertConfigObject, int &alertType, dyn_string &alertTexts, dyn_string &alertClasses, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_objectExtractSummary (dyn_mixed alertConfigObject, int &alertType, dyn_string &alertTexts, dyn_string &summaryDpeList, int &threshold, string &alertClass, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_objectSetMany (dyn_string &dpes, dyn_dyn_mixed &alertConfigObjects, dyn_string &exceptionInfo)
fwAlertConfig_objectGet (string dpe, dyn_mixed &alertConfigObject, dyn_string &exceptionInfo)
fwAlertConfig_objectGetMany (dyn_string &dpes, dyn_dyn_mixed &alertConfigObjects, dyn_string &exceptionInfo)
fwAlertConfig_getAlertClasses (dyn_string searchSystems, dyn_string &alertClassDps, dyn_int &acknowledgeTypes, dyn_int &priorities, dyn_string &exceptionInfo)
_fwAlertConfig_prepareDigital (string dpe, int currentConfigType, dyn_string alertTexts, dyn_string alertClasses, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &attributes, dyn_mixed &values, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE)
fwAlertConfig_deleteMultiple (dyn_string dpes, dyn_string &exceptionInfo, string removeDpeInSummary="", bool storeInParamHistory=TRUE)
fwAlertConfig_deleteMany (dyn_string dpes, dyn_string &exceptionInfo, string removeDpeInSummary="", bool storeInParamHistory=TRUE)
fwAlertConfig_delete (string dpe, dyn_string &exceptionInfo, string removeDpeInSummary="", bool storeInParamHistory=TRUE)
_fwAlertConfig_generateExtraAnalogConfig (int ranges, dyn_float limits, dyn_int &alertHandlingTypes, dyn_float &hysteresisLimits, dyn_bool &hysteresisType, dyn_bool &includeLimits, dyn_string &exceptionInfo)
_fwAlertConfig_prepareAnalog (string dpe, int currentConfigType, int currentNumberOfRanges, dyn_int alertHandlingType, dyn_float limits, dyn_string alertTexts, dyn_string alertClasses, dyn_bool includeLimits, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_int hysteresisType, dyn_float hysteresisLimits, dyn_string &attributes, dyn_mixed &values, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, dyn_string alertWentTexts=makeDynString())
_fwAlertConfig_prepareAnalogDiscrete (string dpe, int currentConfigType, int currentNumberOfRanges, dyn_int alertHandlingType, dyn_string limitsMatch, dyn_string alertTexts, dyn_string alertClasses, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, bool impulse, dyn_bool discreteNegation, dyn_string stateBits, dyn_string stateMatch, dyn_string &attributes, dyn_mixed &values, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, dyn_string alertWentTexts=makeDynString())
_fwAlertConfig_prepareDigitalDiscrete (string dpe, int currentConfigType, dyn_string alertTexts, dyn_string alertClasses, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, bool impulse, dyn_string stateBits, dyn_string &attributes, dyn_mixed &values, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE)
_fwAlertConfig_get (string dpe, int &alertType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClass, dyn_string &summaryDpeList, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &alertActive, dyn_string &exceptionInfo)
_fwAlertConfig_getDiscrete (string dpe, int &alertType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClass, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &alertActive, bool &discrete, bool &impulse, dyn_bool &discreteNegation, string &stateBits, dyn_string &stateMatch, dyn_string &exceptionInfo)
fwAlertConfig_addDpInAlertSummary (string dpe, string dpeToAdd, dyn_string &exceptionInfo, bool errorIfPresent=TRUE, bool storeInParamHistory=TRUE)
fwAlertConfig_deleteDpFromAlertSummary (string dpe, string dpeToDelete, dyn_string &exceptionInfo, bool errorIfNotPresent=TRUE, bool storeInParamHistory=TRUE)
fwAlertConfig_checkIsDpInAlertSummary (string dpe, string dpeToLookFor, bool &dpeFound, dyn_string &exceptionInfo)
_fwAlertConfig_prepareSummary (string dpe, int currentConfigType, float threshold, dyn_string alertTexts, dyn_string dpElementList, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &attributes, dyn_mixed &values, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE)
fwAlertConfig_getMany (dyn_string dpes, dyn_bool &configExists, dyn_int &alertConfigType, dyn_dyn_string &alertTexts, dyn_dyn_float &alertLimits, dyn_dyn_string &alertClasses, dyn_dyn_string &summaryDpeList, dyn_string &alertPanel, dyn_dyn_string &alertPanelParameters, dyn_string &alertHelp, dyn_bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_get (string dpe, bool &configExists, int &alertConfigType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClasses, dyn_string &summaryDpeList, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_getDiscrete (string dpe, bool &configExists, int &alertConfigType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClasses, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, bool &discrete, bool &impulse, dyn_bool &discreteNegation, string &stateBits, dyn_string &stateMatch, dyn_string &exceptionInfo)
fwAlertConfig_setMultiple (dyn_string dpes, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE, bool discrete=FALSE, bool impulse=FALSE, dyn_bool discreteNegation=FALSE, string stateBits="", dyn_string stateMatch="")
fwAlertConfig_setMany (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_dyn_string summaryDpeList, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE, dyn_bool discrete=FALSE, dyn_bool impulse=FALSE, dyn_dyn_bool discreteNegation=FALSE, dyn_string stateBits="", dyn_dyn_string stateMatch="")
fwAlertConfig_setManyDiscrete (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, bool storeInParamHistory=TRUE, dyn_bool discrete=FALSE, dyn_bool impulse=FALSE, dyn_dyn_bool discreteNegation=FALSE, dyn_string stateBits="", dyn_dyn_string stateMatch="")
fwAlertConfig_set (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE, bool discrete=FALSE, bool impulse=FALSE, dyn_bool discreteNegation=FALSE, string stateBits="", dyn_string stateMatch="")
fwAlertConfig_setDiscrete (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, bool storeInParamHistory=TRUE, bool discrete=FALSE, bool impulse=FALSE, dyn_bool discreteNegation=FALSE, string stateBits="", dyn_string stateMatch="")
fwAlertConfig_activate (string dpe, dyn_string &exceptionInfo, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
fwAlertConfig_activateMultiple (dyn_string dpes, dyn_string &exceptionInfo, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
fwAlertConfig_deactivate (string dpe, dyn_string &exceptionInfo, bool acknowledge=TRUE, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
fwAlertConfig_deactivateMultiple (dyn_string dpes, dyn_string &exceptionInfo, bool acknowledge=TRUE, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
_fwAlertConfig_activateOrDeactivate (dyn_string dpes, bool activate, dyn_string &exceptionInfo, bool acknowledgeOnDeactivate=TRUE, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
fwAlertConfig_acknowledge (string dpe, dyn_string &exceptionInfo, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
fwAlertConfig_acknowledgeMany (dyn_string dpes, dyn_string &exceptionInfo, bool checkIfExists=TRUE, bool storeInParamHistory=FALSE)
fwAlertConfig_getLimits (string dpe, dyn_int &limitNumbers, dyn_float &limitValues, dyn_string &exceptionInfo)
fwAlertConfig_setLimits (string dpe, dyn_int limitNumbers, dyn_float limitValues, dyn_string &exceptionInfo, bool checkBeforeSetting=FALSE, bool storeInParamHistory=TRUE)
_fwAlertConfig_checkLimits (dyn_float limitValues, bool &limitsOk, dyn_string &exceptionInfo)
_fwAlertConfig_checkClassPriorities (dyn_string systemsToCheck, dyn_string &alertClasses, bool &classesOk, dyn_string &exceptionInfo, bool useAlternativeClassPriorities=FALSE)
fwAlertConfig_generateAbsoluteLimitsMany (dyn_string dpes, int limitsType, dyn_dyn_mixed relativeLimits, dyn_dyn_mixed &absoluteLimits, dyn_string &exceptionInfo)
fwAlertConfig_generateAbsoluteLimitsMultiple (dyn_string dpes, int limitsType, dyn_mixed relativeLimits, dyn_dyn_mixed &absoluteLimits, dyn_string &exceptionInfo)
_fwAlertConfig_checkAlertClasses (dyn_dyn_string &alertClasses, dyn_string &exceptionInfo)
_fwAlertConfig_createDpeAlertConfigObject (dyn_dyn_anytype &dpeAlertConfigObject, string dpe, int type, bool active, dyn_float limits, dyn_string classes, dyn_string texts, string panel, dyn_string panelParameters, string help, dyn_string &exceptionInfo, int dpeType=-1)
_fwAlertConfig_readDpeAlertConfigObject (dyn_dyn_anytype dpeAlertConfigObject, string &dpe, int &type, bool &active, dyn_float &limits, dyn_string &classes, dyn_string &texts, string &panel, dyn_string &panelParameters, string &help, dyn_string &exceptionInfo, int &dpeType)
fwAlertConfig_queryAlertsOnSystem (string systemName, dyn_dyn_string &alertData, dyn_string &exceptionInfo)
fwAlertConfig_setGeneral (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClass, string alertPanel, dyn_string alertPanelParameters, string help, bool alertRequest, dyn_string &exceptionInfo)
fwAlertConfig_setDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE)
fwAlertConfig_setAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE)
fwAlertConfig_setSummary (string dpe, dyn_string alertTexts, dyn_string dpElementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE)
fwAlertConfig_createSummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_modifySummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_createDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_modifyDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_createAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_modifyAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_deleteSummary (string dpe, dyn_string &exceptionInfo)
fwAlertConfig_deleteAnalog (string dpe, dyn_string &exceptionInfo)
fwAlertConfig_deleteDigital (string dpe, dyn_string &exceptionInfo)
fwAlertConfig_getSummary (string dpe, bool &configExists, dyn_string &alertTexts, dyn_string &dpeList, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, dyn_string &exceptionInfo)
Variables
const string fwAlertConfig_FW_ALERT_CLASS_DPTYPE = "_FwAlertClass"
const string fwAlertConfig_FW_ALERT_CLASS_ALTERNATIVE_PATTERN = "_*_[0123456789][0123456789]*"
const string fwAlertConfig_FW_NULL_PATTERN = "JCOPFW_NULL_PATTERN"
const int fwAlertConfig_ALERT_MAX_PARAM_RANGES = 20
const int fwAlertConfig_ALERT_LIMIT_TEXT = 1
const int fwAlertConfig_ALERT_LIMIT_VALUE = 2
const int fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED = 3
const int fwAlertConfig_ALERT_LIMIT_CLASS = 4
const int fwAlertConfig_ALERT_LIMIT_VALUE_MATCH = 5
const int fwAlertConfig_ALERT_LIMIT_NEGATION = 8
const int fwAlertConfig_ALERT_LIMIT_STATE_BITS = 9
const int fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS = 10
const int fwAlertConfig_ALERT_LIMIT_TEXT_WENT = 11
const int fwAlertConfig_ALERT_PARAM_TYPE = 1
const int fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST = 2
const int fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY = 3
const int fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD = 4
const int fwAlertConfig_ALERT_PARAM_PANEL = 5
const int fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS = 6
const int fwAlertConfig_ALERT_PARAM_HELP = 7
const int fwAlertConfig_ALERT_PARAM_DISCRETE = 8
const int fwAlertConfig_ALERT_PARAM_IMPULSE = 9
const int fwAlertConfig_ALERT_PARAM_MODIFY_ONLY = 10
const int fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET = 11
const int fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY = 12
const int fwAlertConfig_ALERT_PARAM_RANGES = 13
const int fwAlertConfig_ALERT_PARAM_ACTIVE = 14
const int fwAlertConfig_ALERT_PARAM = 1
const int fwAlertConfig_ALERT_LIMIT = 2
Detailed Description
This library contains function associated with the alert handling config. Functions are provided for getting the current settings, deleting the config and for creating or altering the config Seperate functions for digital, analog and summary type alerts are available. Note: In order to set/get alarms, it is recommended to use the new functions fwAlertConfig_objectSet(), fwAlertConfig_objectGet(), fwAlertConfig_objectSetMany(), fwAlertConfig_objectGetMany(). See the functions for use examples.
Creation Date
14/03/2000
Modification History
12/08/11 Marco Boccioli
#85462: Functions *_setMany and *_getMany with parameters as reference.
28/07/11 Marco Boccioli
#84905: Discrete alarms: alarm not working if range has more than one value. The problem was on the rfact that discrete alarms have 2 types: _SET (for values like "1,3,4") and _MATCH (for values lie "12" or "12-23"). Modified functions: fwAlertConfig_objectGetMany() now needs to make a further scan of dpGet: once to get the type of discrete alarm, once to get the value from attribute _set or _match, according to the type. _fwAlertConfig_prepareAnalogDiscrete() now sets the discrete value to _set or to _match, according to the ype of value (coma-separated or range or single).. Such feature is temporarely disabled because of bug on PVSS 3.8.2 (ETM-826).
18/07/11 Marco Boccioli
JCOP-121: fwAlertConfig_objectGetMany() - strange error returned in exceptionInfo. The way the exception is thrown was corrected.
24/03/11 Marco Boccioli
fix for #79936 (modifying alert results in deactivating the alert). The object setting parameter fwAlertConfig_ALERT_PARAM_ACTIVE cannot be used any more as setting, otherwise it overwrites the active status of the alarm in case of modification of the settings. fwAlertConfig_ALERT_PARAM_ACTIVE is now available Read Only.
16/02/11 Marco Boccioli
fix for #78303 (cannot add decimals to limits).
09/02/11 Marco Boccioli
fix for #77977 (sum alarm threshold is not applied when using fwAlertConfig_set).
25/11/10 Marco Boccioli
fix for JCOP-62 and #75697 (set an alarm with the JCOP fwConfigs function): modified function _fwAlertConfig_prepareAnalog(): It now checks if the Went text is filled. If not, it does not set at all the attribute _went_text. This avoids problems if setting alarm on a dist system running on PVSS 3.6.
11/10/10 Marco Boccioli
fix for bug #73869: Error printed when setting binary alerts. The function fwAlertConfig_objectSetMany() was looking for .._num_ranges also for binary alert (that don't have it)
09/08/10 Marco Boccioli
fix for bug #71138: the fwAlertConfig_objectSet() was shifting the limits.
12/07/10 Marco Boccioli
fix for bug #48354: the "went" text can be set using fwAlertConfig_objectSet().
fix for bug #68528: the "included" limits are available if using fwAlertConfig_objectSet().
fix for bug #21219: fwAlertConfig_objectGetMany() is making use of dpGet 3 times, regardless from the amount of dpes. 3 times faster than fwAlertConfig_getMany().
improvement for bug #67230: created new set of functions (fwAlertConfig_object...). Those functions allow setting an alarm by means of an object. The user should:
initialize the object (fwAlertConfig_objectInitialize())
populate the object with alarm settings (fwAlertConfig_objectCreate...)
apply the object to the dpe(s) (fwAlertConfig_objectSet()). In order to read alarm settings:
get the settings from dpe(s) (fwAlertConfig_objectGet())
extract the settings from the object (fwAlertConfig_objectExtract...) Elements of an object can be accessed directly using the indexes provided below ("indexes for alarm limits object" and "indexes for alarm parameters object")
fix for bug #67230: added optional parameters for discrete alarms to fwAlertConfig_set(), fwAlertConfig_setMany(), fwAlertConfig_setMultiple(). For back-compatibility, nothing was added to fwAlertConfig_get() and fwAlertConfig_getMany() (discrete alarms details cannot be retrieved with those functions). In order to get discrete alarms, added functions: fwAlertConfig_getDiscrete(). For consistency, added also: fwAlertConfig_setDiscrete().
05/05/10 Marco Boccioli
fix for bug #66963: modified the call of fwAlertConfig_set() at fwAlertConfig_deleteDpFromAlertSumma()ry and fwAlertConfig_addDpInAlertSummary().
10/03/10 Marco Boccioli
fix for bug #62428: On _fwAlertConfig_prepareSummary(), added a few lines: now, if the dpElementList is empty, the function removes the _dp_list and cleans the _dp_pattern.
16/01/04 Oliver Holme (IT-CO)
Added new functions for activate/deactivate/acknowledge and set/getLimits
15/01/04 Oliver Holme (IT-CO)
Completed major overhaul of whole library
05/05/00 Herve Milcent
problem with a summary alert with an empty list of dp, add a dummy dp to avoid it when creating the alert sum: compCreateAlertConfigSum
Constraints
WARNING: the functions use the dpGet or dpSetWait, problems may occur when using these functions in a working function called by a PVSS (dpConnect) or in a calling function
Usage
Public
PVSS managers
VISION, CTRL
Author:
Oliver Holme (IT-CO) based on original by Herve Milcent, Niko Karlsson based on libMLDBEH_ANLEGEN.ctl
Function Documentation
_fwAlertConfig_activateOrDeactivate (dyn_string dpes, bool activate, dyn_string & exceptionInfo, bool acknowledgeOnDeactivate = TRUE, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Activates or deactivates the alert handling on the given data point element.
Constraints
If a dpe does not have alert handling defined, the function returns without any exception. (The dpe has no active alert handling and is also available to have an alert handling config written to it)
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes The data point elements to act on
activate Set to TRUE to activate alert Set to FALSE to deactivate alert
exceptionInfo Details of any exceptions are returned here
acknowledgeOnDeactivate Optional parameter (Default value - TRUE) only used when activate is FALSE TRUE for acknowledge alert when deactivating FALSE to leave alert unacknowledge when deactivated
checkIfExists Optional parameter (Default value - TRUE) TRUE - check if alert config exists (avoids errors if it doesn't) FALSE - do not check if alert exists (may cause errors if it does not exist)
storeInParamHistory Optional parameter (Default value - FALSE) TRUE - writing to active bit is stored in alert history FALSE - writing to active bit is not stored in alert history
References _fwConfigs_getConfigTypeAttribute().
Referenced by fwAlertConfig_activate(), fwAlertConfig_activateMultiple(), fwAlertConfig_deactivate(), and fwAlertConfig_deactivateMultiple().
_fwAlertConfig_checkClassPriorities (dyn_string systemsToCheck, dyn_string & alertClasses, bool & classesOk, dyn_string & exceptionInfo, bool useAlternativeClassPriorities = FALSE)
This function checks that the given list of alert classes is appropriate for setting to an alert config. The priority of each alert class is found and then a check is performed to check that the priorities are in a valid order. The check is performed as many times as there are systems specified, as priorities may vary on the same class in different systems. Valid orders are: 1) Priorities of alert classes in descending order down to 0 (good range) - e.g. 60, 40, 0 2) Priorities of alert classes in ascending order up from 0 (good range) - e.g. 0, 20, 40, 60 ,80 3) Priorities of alert classes first descending down to 0 (good range) then ascending after then - e.g. 60, 40, 0, 40, 80
Constraints
This function does not actually check that a good range is passed. It just checks the ordering of priorities. It is your responsibility to make sure that one alert class in the list passed to this function is empty (good range).
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
systemsToCheck The list of systems to check the classes on. An empty list means local system only.
alertClasses The list of alert classes in the order you wish to write them to the alert config.
classesOk Returns TRUE if classes are OK to be set. Returns FALSE if classes are bad.
exceptionInfo Details of any exceptions are returned here
useAlternativeClassPriorities OPTIONAL PARAMETER - default value: FALSE If TRUE, the function will try to use similar alert classes of different priorities (fwWarningAck => fwWarningAck_41) in order to resolve problems with the same class being used twice in neighbouring alert ranges. If FALSE, no modification is made to the alertClasses as passed to the function. Only the checking of the priorities is carried out - no automatic attempt to correct.
_fwAlertConfig_checkLimits (dyn_float limitValues, bool & limitsOk, dyn_string & exceptionInfo)
This function check thats the given alert range limits are valid for setting to the alert config. This means that they should be in ascending order and no limit value should be duplicated.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
limitValues The list of range limit values to be checked
limitsOk Returns TRUE if limits are OK to be set. Returns FALSE if limits are bad.
exceptionInfo Details of any exceptions are returned here
Referenced by fwAlertConfig_setLimits().
_fwAlertConfig_createDpeAlertConfigObject (dyn_dyn_anytype & dpeAlertConfigObject, string dpe, int type, bool active, dyn_float limits, dyn_string classes, dyn_string texts, string panel, dyn_string panelParameters, string help, dyn_string & exceptionInfo, int dpeType = -1)
Under development - DO NOT USE
References fwConfigs_createDpeConfigObject().
_fwAlertConfig_get (string dpe, int & alertType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClass, dyn_string & summaryDpeList, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & alertActive, dyn_string & exceptionInfo)
Returns the alert handling properties of a analog or digital datapoint if the number of alert texts returned is 0, then no alert configuration exists
NOTE: THIS FUNCTION SHOULD NOT BE CALLED DIRECTLY, use fwAlertConfig_get
Constraints
The length of the alertTexts and alertClasses dyn_strings must both be 2
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
alertType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts for each range
alertLimits The limits of each range given here
alertClass Alert classes for each range One of the items of the dyn_string must always be empty to indicate the valid state. Don't forget to add the dot to the alert class names.
summaryDpeList If Summary alert, the dpeList is returned here If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in alertPanel
alertHelp Help text or path to help file
alertActive whether or not this configuration is active
exceptionInfo Details of any exceptions are returned here
References fwAlertConfig_getLimits().
Referenced by _fwAlertConfig_getDiscrete(), and fwAlertConfig_get().
_fwAlertConfig_getDiscrete (string dpe, int & alertType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClass, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & alertActive, bool & discrete, bool & impulse, dyn_bool & discreteNegation, string & stateBits, dyn_string & stateMatch, dyn_string & exceptionInfo)
Returns the discrete alert handling properties of a analog or digital datapoint if the number of alert texts returned is 0, then no alert configuration exists
NOTE: THIS FUNCTION SHOULD NOT BE CALLED DIRECTLY, use fwAlertConfig_get
Constraints
The length of the alertTexts and alertClasses dyn_strings must both be 2
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
alertType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts for each range
alertLimits The limits of each range given here
alertClass Alert classes for each range One of the items of the dyn_string must always be empty to indicate the valid state. Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in alertPanel
alertHelp Help text or path to help file
alertActive whether or not this configuration is active
discrete TRUE if discrete
impulse TRUE if impulse
discreteNegation For each limit, if the value must match it, or must not match it (TRUE = must not match it)
stateBits state bits of the alarms
stateMatch for each limit, state bits of the limit
exceptionInfo Details of any exceptions are returned here
References _fwAlertConfig_get(), and fwAlertConfig_getLimits().
Referenced by fwAlertConfig_getDiscrete().
_fwAlertConfig_objectCreateParams (dyn_dyn_anytype & alarmParams, dyn_dyn_anytype & alarmLimits, int totalRanges)
Set alarm object based on alarm params and limits. Initialize it. For more info, refer to fwAlertConfig_objectSetMany()
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
alarmParams output, object containing the alarm parameters.
alarmLimits putput, object containing the alarm limits.
totalRanges input, alarm ranges.
References fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS, fwAlertConfig_ALERT_LIMIT_NEGATION, fwAlertConfig_ALERT_LIMIT_STATE_BITS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_TEXT_WENT, fwAlertConfig_ALERT_LIMIT_VALUE, fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED, fwAlertConfig_ALERT_LIMIT_VALUE_MATCH, fwAlertConfig_ALERT_PARAM_ACTIVE, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_DISCRETE, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_IMPULSE, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST, fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD, and fwAlertConfig_ALERT_PARAM_TYPE.
Referenced by fwAlertConfig_objectGetMany(), and fwAlertConfig_objectInitialize().
_fwAlertConfig_prepareAnalog (string dpe, int currentConfigType, int currentNumberOfRanges, dyn_int alertHandlingType, dyn_float limits, dyn_string alertTexts, dyn_string alertClasses, dyn_bool includeLimits, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_int hysteresisType, dyn_float hysteresisLimits, dyn_string & attributes, dyn_mixed & values, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, dyn_string alertWentTexts = makeDynString())
Prepares a list of attributes and a list of values to be used in a dpSetWait() call to set the config for the given dpe.
Constraints
The length of the alertTexts, alertHandlingType, hysteresisType and alertClasses dyn_vars must be equal The length of the limits and includeLimits dyn_vars must be one less than the length of alertTexts
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
currentConfigType The type of the current alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
currentNumberOfRanges The current number of ranges in the alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
alertHandlingType One value in dyn_int for each range to be used. Value should be DPDETAIL_RANGETYPE_MINMAX;
limits The limits of each range given here eg. makeDynFloat(20, 60);
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
alertClasses Alert classes for each range eg. makeDynString("_fwErrorAck.", "" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
includeLimits TRUE to include, else FALSE
minimumPriority Minimum priority of alert (ignore below this value)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
hysteresisType One value for each range in use: DPATTR_HYST_NONE for no hysteresis or DPATTR_HYST_VALUE for hysteresis
hysteresisLimits Values for limits of hysteresis (length of dyn_float) should be (ranges-1)*2
attributes Output - the list of attributes that need to be set is returned here
values Output - the list of values that need to be set is returned here
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
alertWentTexts Optional parameter - the list of went texts, one per range.
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
_fwAlertConfig_prepareAnalogDiscrete (string dpe, int currentConfigType, int currentNumberOfRanges, dyn_int alertHandlingType, dyn_string limitsMatch, dyn_string alertTexts, dyn_string alertClasses, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, bool impulse, dyn_bool discreteNegation, dyn_string stateBits, dyn_string stateMatch, dyn_string & attributes, dyn_mixed & values, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, dyn_string alertWentTexts = makeDynString())
Prepares a list of attributes and a list of values to be used in a dpSetWait() call to set the discrete config for the given dpe.
Constraints
The length of the alertTexts, alertHandlingType, hysteresisType , limits and includeLimits alertClasses dyn_vars must be equal
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
currentConfigType The type of the current alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
currentNumberOfRanges The current number of ranges in the alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
alertHandlingType One value in dyn_int for each range to be used. Value should be DPDETAIL_RANGETYPE_MINMAX;
limitsMatch The values match of each range given here eg. makeDynString("*", "2,4,5", "3", "6-10"); First element must be *.
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
alertClasses Alert classes for each range eg. makeDynString("_fwErrorAck.", "" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
minimumPriority Minimum priority of alert (ignore below this value)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
impulse If TRUE, the discrete alert reacts to impulses.
discreteNegation One per limit. If FALSE, the alarm is triggered if the value matches that limit. If TRUE, the alarm is triggered if the value does not match that limit.
stateBits State Bits of the alarm. (i.e. 000010011000).
stateMatch State Bits of the limit. One per limit. (i.e. xxx0010x110xxx).
attributes Output - the list of attributes that need to be set is returned here
values Output - the list of values that need to be set is returned here
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
alertWentTexts Optional parameter - the list of went texts, one per range.
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
_fwAlertConfig_prepareDigital (string dpe, int currentConfigType, dyn_string alertTexts, dyn_string alertClasses, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & attributes, dyn_mixed & values, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE)
Prepares a list of attributes and a list of values to be used in a dpSetWait() call to set the config for the given dpe.
Constraints
The length of the alertTexts and alertClasses dyn_strings must both be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
currentConfigType The type of the current alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
alertTexts Alert texts eg. makeDynString("Bad Text", "OK")
alertClasses Alert classes eg. makeDynString("_fwErrorAck.", "") One of the items of the dyn_string must always be empty to indicate the valid state The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
minimumPriority Minimum priority of alert (ignore below this value)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
attributes Output - the list of attributes that need to be set is returned here
values Output - the list of values that need to be set is returned here
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist and must be of type binary alert.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
_fwAlertConfig_prepareDigitalDiscrete (string dpe, int currentConfigType, dyn_string alertTexts, dyn_string alertClasses, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, bool impulse, dyn_string stateBits, dyn_string & attributes, dyn_mixed & values, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE)
Prepares a list of attributes and a list of values to be used in a dpSetWait() call to set the discrete config for the given dpe.
Constraints
The length of the alertTexts, alertHandlingType, hysteresisType , limits and includeLimits alertClasses dyn_vars must be equal
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
currentConfigType The type of the current alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
alertTexts Alert texts eg. makeDynString("Bad Text", "OK")
alertClasses Alert classes eg. makeDynString("_fwErrorAck.", "") One of the items of the dyn_string must always be empty to indicate the valid state The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
minimumPriority Minimum priority of alert (ignore below this value)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
impulse If TRUE, the discrete alert reacts to impulses.
stateBits State Bits of the alarm. (i.e. 000010011000).
attributes Output - the list of attributes that need to be set is returned here
values Output - the list of values that need to be set is returned here
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist and must be of type binary alert.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
_fwAlertConfig_prepareSummary (string dpe, int currentConfigType, float threshold, dyn_string alertTexts, dyn_string dpElementList, int minimumPriority, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & attributes, dyn_mixed & values, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE)
Prepares a list of attributes and a list of values to be used in a dpSetWait() call to set the config for the given dpe.
Constraints
The length of the alertTexts should be 2 Can only set summary alerts of type dp list (not dp pattern)
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
currentConfigType The type of the current alert config on the data point element (only considered in case of modifyOnly = TRUE, otherwise value is ignored)
threshold limit of single alarms to be shown before they are masked (and only the sum alarm is shown).
alertTexts Alert texts eg. makeDynString("OK", "Bad")
dpElementList List of dpes to include in summary alert
minimumPriority Minimum priority of alert (ignore below this value)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
attributes Output - the list of attributes that need to be set is returned here
values Output - the list of values that need to be set is returned here
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist and be of type summary alert.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
_fwAlertConfig_readDpeAlertConfigObject (dyn_dyn_anytype dpeAlertConfigObject, string & dpe, int & type, bool & active, dyn_float & limits, dyn_string & classes, dyn_string & texts, string & panel, dyn_string & panelParameters, string & help, dyn_string & exceptionInfo, int & dpeType)
Under development - DO NOT USE
fwAlertConfig_acknowledge (string dpe, dyn_string & exceptionInfo, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Acknowledges the alert handling on the given data point element. This function uses the DPATTR_ACKTYPE_SINGLE to acknowledge the alert.
Constraints
Only works on dpes with alert handling already configured
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element to act on
exceptionInfo Details of any exceptions are returned here
checkIfExists Optional parameter (Default value - TRUE) TRUE - check if alert config exists (avoids errors if it doesn't) FALSE - do not check if alert exists (may cause errors if it does not exist)
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References fwAlertConfig_acknowledgeMany().
fwAlertConfig_acknowledgeMany (dyn_string dpes, dyn_string & exceptionInfo, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Acknowledges the alert handling on the given data point elements. If more than one dpe is specified, the DPATTR_ACKTYPE_MULTIPLE value is used to acknowledge, indicating that the alerts were acknowledged as part of a group acknowledge action. Otherwise the DPATTR_ACKTYPE_SINGLE value is written.
Constraints
Only works on dpes with alert handling already configured
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes the list of data point elements to act on
exceptionInfo Details of any exceptions are returned here
checkIfExists Optional parameter (Default value - TRUE) TRUE - only acknowledge alerts which exist (avoids errors if it doesn't) FALSE - do not check if alert exists (cause exceptions to be raised if they do not exist)
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References _fwConfigs_getConfigTypeAttribute(), and _fwConfigs_setConfigTypeAttribute().
Referenced by fwAlertConfig_acknowledge().
fwAlertConfig_activate (string dpe, dyn_string & exceptionInfo, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Activates the alert handling on the given data point element.
Constraints
Only works on dpes with alert handling already configured
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element to act on
exceptionInfo Details of any exceptions are returned here
checkIfExists Optional parameter (Default value - TRUE) TRUE - check if alert config exists (avoids errors if it doesn't) FALSE - do not check if alert exists (may cause errors if it does not exist)
storeInParamHistory Optional parameter (Default value - FALSE) TRUE - writing to active bit is stored in alert history FALSE - writing to active bit is not stored in alert history
References _fwAlertConfig_activateOrDeactivate().
Referenced by fwAlertConfig_setLimits().
fwAlertConfig_activateMultiple (dyn_string dpes, dyn_string & exceptionInfo, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Activates the alert handling on the given list of data point elements.
Constraints
Only works on dpes with alert handling already configured
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes The list of data point elements to act on
exceptionInfo Details of any exceptions are returned here
checkIfExists Optional parameter (Default value - TRUE) TRUE - check if alert config exists (avoids errors if it doesn't) FALSE - do not check if alert exists (may cause errors if it does not exist)
storeInParamHistory Optional parameter (Default value - FALSE) TRUE - writing to active bit is stored in alert history FALSE - writing to active bit is not stored in alert history
References _fwAlertConfig_activateOrDeactivate().
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
fwAlertConfig_addDpInAlertSummary (string dpe, string dpeToAdd, dyn_string & exceptionInfo, bool errorIfPresent = TRUE, bool storeInParamHistory = TRUE)
Adds a new data point element to the dp list of an existing summary alert handling on the given data point element.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element where the summary alert config is
dpeToAdd Name of the data point element to be added to the summary alert
exceptionInfo Details of any exceptions are returned here
errorIfPresent OPTIONAL PARAMETER - default value TRUE If TRUE, an exception is raised if the dpeToAdd is already configured in the summary alert. If FALSE, no exception is raised in this case.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References fwAlertConfig_get(), and fwAlertConfig_set().
Referenced by fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
fwAlertConfig_checkIsDpInAlertSummary (string dpe, string dpeToLookFor, bool & dpeFound, dyn_string & exceptionInfo)
Checks for a reference to a given data point element in the dp list of an existing summary alert handling on the given data point element.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element where the summary alert config is
dpeToLookFor Name of the data point element to be searched for in the summary alert
dpeFound Result is returned here. TRUE if dpe was found in summary alert, else FALSE
exceptionInfo Details of any exceptions are returned here
References fwAlertConfig_get().
fwAlertConfig_createAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to create an analog alert
For new function see fwAlertConfig_set
Usage
DEPRECATED
References fwAlertConfig_setAnalog().
Referenced by fwAlertConfig_setGeneral().
fwAlertConfig_createDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to create a digital alert
For new function see fwAlertConfig_set
Usage
DEPRECATED
References fwAlertConfig_setDigital().
Referenced by fwAlertConfig_setGeneral().
fwAlertConfig_createSummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to create a summary alert
For new function see fwAlertConfig_set
Usage
DEPRECATED
References fwAlertConfig_setSummary().
fwAlertConfig_deactivate (string dpe, dyn_string & exceptionInfo, bool acknowledge = TRUE, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Deactivates the alert handling on the given data point element.
Constraints
Only works on dpes with alert handling already configured
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element to act on
exceptionInfo Details of any exceptions are returned here
acknowledge Optional parameter (Default value - TRUE) TRUE for acknowledge alert when deactivating FALSE to leave alert unacknowledge when deactivated
checkIfExists Optional parameter (Default value - TRUE) TRUE - check if alert config exists (avoids errors if it doesn't) FALSE - do not check if alert exists (may cause errors if it does not exist)
storeInParamHistory Optional parameter (Default value - FALSE) TRUE - writing to active bit is stored in alert history FALSE - writing to active bit is not stored in alert history
References _fwAlertConfig_activateOrDeactivate().
Referenced by fwAlertConfig_setLimits().
fwAlertConfig_deactivateMultiple (dyn_string dpes, dyn_string & exceptionInfo, bool acknowledge = TRUE, bool checkIfExists = TRUE, bool storeInParamHistory = FALSE)
Deactivates the alert handling on the given list of data point elements.
Constraints
Only works on dpes with alert handling already configured
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes List of data point elements to act on
exceptionInfo Details of any exceptions are returned here
acknowledge Optional parameter (Default value - TRUE) TRUE for acknowledge alert when deactivating FALSE to leave alert unacknowledge when deactivated
checkIfExists Optional parameter (Default value - TRUE) TRUE - check if alert config exists (avoids errors if it doesn't) FALSE - do not check if alert exists (may cause errors if it does not exist)
storeInParamHistory Optional parameter (Default value - FALSE) TRUE - writing to active bit is stored in alert history FALSE - writing to active bit is not stored in alert history
References _fwAlertConfig_activateOrDeactivate().
Referenced by fwAlertConfig_deleteMultiple(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
fwAlertConfig_delete (string dpe, dyn_string & exceptionInfo, string removeDpeInSummary = "", bool storeInParamHistory = TRUE)
Deletes the alert config for the given data point element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
exceptionInfo details of any errors are returned here
removeDpeInSummary OPTIONAL PARAMETER - default value = "" (no aciton) You can specify the dpe which has a summary alert from which you want to remove the reference to the dpe to delete
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References fwAlertConfig_deleteMultiple().
Referenced by fwAlertConfig_deleteAnalog(), fwAlertConfig_deleteDigital(), and fwAlertConfig_deleteSummary().
fwAlertConfig_deleteAnalog (string dpe, dyn_string & exceptionInfo)
DEPRECATED - Function to delete an analog alert
For new function see fwAlertConfig_delete
Usage
DEPRECATED
References fwAlertConfig_delete().
Referenced by fwAlertConfig_setGeneral().
fwAlertConfig_deleteDigital (string dpe, dyn_string & exceptionInfo)
DEPRECATED - Function to delete a digital alert
For new function see fwAlertConfig_delete
Usage
DEPRECATED
References fwAlertConfig_delete().
Referenced by fwAlertConfig_setGeneral().
fwAlertConfig_deleteDpFromAlertSummary (string dpe, string dpeToDelete, dyn_string & exceptionInfo, bool errorIfNotPresent = TRUE, bool storeInParamHistory = TRUE)
Removes a data point element from the dp list of an existing summary alert handling on the given data point element.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element where the summary alert config is
dpeToDelete Name of the data point element to be removed from the summary alert
exceptionInfo Details of any exceptions are returned here
errorIfNotPresent OPTIONAL PARAMETER - default value TRUE If TRUE, an exception is raised if the dpeToDelete is not currently configured in the summary alert. If FALSE, no exception is raised in this case.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References fwAlertConfig_get(), and fwAlertConfig_set().
Referenced by fwAlertConfig_deleteMultiple().
fwAlertConfig_deleteMany (dyn_string dpes, dyn_string & exceptionInfo, string removeDpeInSummary = "", bool storeInParamHistory = TRUE)
Deletes the alert config for the given data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
removeDpeInSummary OPTIONAL PARAMETER - default value = "" (no aciton) You can specify the dpe which has a summary alert from which you want to remove the reference to the dpe to delete
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References fwAlertConfig_deleteMultiple().
fwAlertConfig_deleteMultiple (dyn_string dpes, dyn_string & exceptionInfo, string removeDpeInSummary = "", bool storeInParamHistory = TRUE)
Deletes the alert config for the given data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
removeDpeInSummary OPTIONAL PARAMETER - default value = "" (no aciton) You can specify the dpe which has a summary alert from which you want to remove the reference to the dpe to delete
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References _fwConfigs_delete(), _fwConfigs_getConfigTypeAttribute(), fwAlertConfig_deactivateMultiple(), and fwAlertConfig_deleteDpFromAlertSummary().
Referenced by fwAlertConfig_delete(), and fwAlertConfig_deleteMany().
fwAlertConfig_deleteSummary (string dpe, dyn_string & exceptionInfo)
DEPRECATED - Function to delete a summary alert
For new function see fwAlertConfig_delete
Usage
DEPRECATED
References fwAlertConfig_delete().
fwAlertConfig_generateAbsoluteLimitsMany (dyn_string dpes, int limitsType, dyn_dyn_mixed relativeLimits, dyn_dyn_mixed & absoluteLimits, dyn_string & exceptionInfo)
This function can be used to evaluate relative limits for many dpes and get back the absolute values needed to save to the PVSS configs. You can specify a different set of limits for each dpe that you pass to the function. Types of relative limit can be "Current Value +/- the limit value" or "Current Value +/- a percentage of the current value". If you use this function with limits of the normal absolute type, the output limits will be equal to the input limits.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes The list of data point elements that the limits are intended for
limitsType The type of limits that you are passing to the function. Must be one of: fwConfigs_ALERT_LIMITS_ABSOLUTE fwConfigs_ALERT_LIMITS_RELATIVE fwConfigs_ALERT_LIMITS_RELATIVE_PERCENTAGE
relativeLimits The list of values of the limits for each dpe in the dpes list.
absoluteLimits The processed limits are returned here. Each limit is found in the same position in the array as the original unprocessed limit in relativeLimits.
exceptionInfo Details of any exceptions are returned here
References _fwConfigs_getConfigTypeAttribute().
Referenced by fwAlertConfig_generateAbsoluteLimitsMultiple().
fwAlertConfig_generateAbsoluteLimitsMultiple (dyn_string dpes, int limitsType, dyn_mixed relativeLimits, dyn_dyn_mixed & absoluteLimits, dyn_string & exceptionInfo)
This function can be used to evaluate relative limits for many dpes and get back the absolute values needed to save to the PVSS configs. The same set of limits is used for every dpe that you pass to the function. Types of relative limit can be "Current Value +/- the limit value" or "Current Value +/- a percentage of the current value". If you use this function with limits of the normal absolute type, the output limits will be equal to the input limits.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes The list of data point elements that the limits are intended for
limitsType The type of limits that you are passing to the function. Must be one of: fwConfigs_ALERT_LIMITS_ABSOLUTE fwConfigs_ALERT_LIMITS_RELATIVE fwConfigs_ALERT_LIMITS_RELATIVE_PERCENTAGE
relativeLimits The limits to be evaluted for each dpe.
absoluteLimits The processed limits are returned here. The first dimension of the array indicates which dpe the limit value belongs to. The second dimension of the array provides all the limits for that particular dpe. e.g. absoluteLimits[1][2] returns the second limit value for the dpe in the first position of the dpes list.
exceptionInfo Details of any exceptions are returned here
References fwAlertConfig_generateAbsoluteLimitsMany().
fwAlertConfig_get (string dpe, bool & configExists, int & alertConfigType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClasses, dyn_string & summaryDpeList, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, dyn_string & exceptionInfo)
Returns the details of any alert configuration on a given dpe. This function can handle digital, analog and summary alerts
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertConfigType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts are returned here for all types of alert
alertLimits Alert limits are returned here for analog alerts
alertClasses Alert classes are returned here for digital and analog alertd
summaryDpeList If Summary alert, the dpeList is returned here If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
exceptionInfo Details of any exceptions are returned here
References _fwAlertConfig_get().
Referenced by fwAlertConfig_addDpInAlertSummary(), fwAlertConfig_checkIsDpInAlertSummary(), fwAlertConfig_deleteDpFromAlertSummary(), and fwAlertConfig_getMany().
fwAlertConfig_getAlertClasses (dyn_string searchSystems, dyn_string & alertClassDps, dyn_int & acknowledgeTypes, dyn_int & priorities, dyn_string & exceptionInfo)
Gets a list of all the existing archive class dps of type _FwAlertClass. Lists are also returned containing the acknowledgeType of the class and the priority The search is performed in the specified systems, and only classes found in ALL of the systems will be returned
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
searchSystems A list of systems to search in
alertClassDps The list of alert class dps found is returned here (excluding the . at the end and without system name)
acknowledgeTypes The acknowledge type of each alert class is returned here. Possible values are: DPATTR_ACK_DELETES - acknowledgement deletes DPATTR_ACK_NONE - cannot be acknowledged (unacknowledgable) DPATTR_ACK_APP - CAME can be acknowledged DPATTR_ACK_PAIR - alert pair must be acknowledged DPATTR_ACK_APP_AND_DISAPP - CAME and WENT must be acknowledged
priorities The prioritues of each alert class is returned here.
exceptionInfo Details of any exceptions are returned here
fwAlertConfig_getDiscrete (string dpe, bool & configExists, int & alertConfigType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClasses, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, bool & discrete, bool & impulse, dyn_bool & discreteNegation, string & stateBits, dyn_string & stateMatch, dyn_string & exceptionInfo)
Returns the details of any alert configuration on a given dpe. This function can handle digital, analog and summary alerts
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe input, Name of data point element to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertConfigType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts are returned here for all types of alert
alertLimits Alert limits are returned here for analog alerts
alertClasses Alert classes are returned here for digital and analog alertd
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
discrete TRUE if alert is discrete else FALSE
impulse TRUE if alert is impulse alert else FALSE
discreteNegation for each match values, TRUE if the match is negated (i.e. "!=").
stateBits state bits of the discrete alert
stateMatch state bits of each value match
exceptionInfo Details of any exceptions are returned here
References _fwAlertConfig_getDiscrete().
fwAlertConfig_getLimits (string dpe, dyn_int & limitNumbers, dyn_float & limitValues, dyn_string & exceptionInfo)
Gets the alert limits for the currently configured alert ranges on the given data point element.
Constraints
Only works on data points that have an analog alert handling set up.
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element to read limits from
limitNumbers The numbers of the limits are returned here This is always a list of integers starting at 1 up to the number of (ranges - 1) e.g. For a 5 range alert the value returned will be {1,2,3,4}
limitValues The values of the limits are returned here The limits are always returned is ascending order
exceptionInfo Details of any exceptions are returned here
Referenced by _fwAlertConfig_get(), _fwAlertConfig_getDiscrete(), and fwAlertConfig_setLimits().
fwAlertConfig_getMany (dyn_string dpes, dyn_bool & configExists, dyn_int & alertConfigType, dyn_dyn_string & alertTexts, dyn_dyn_float & alertLimits, dyn_dyn_string & alertClasses, dyn_dyn_string & summaryDpeList, dyn_string & alertPanel, dyn_dyn_string & alertPanelParameters, dyn_string & alertHelp, dyn_bool & isActive, dyn_string & exceptionInfo)
Returns the details of any alert configuration on a given set of dpes. This function can handle digital, analog and summary alerts
Constraints
Can only get summary alerts of type dp list (not dp pattern)
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes Name of data point elements to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertConfigType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts are returned here for all types of alert
alertLimits Alert limits are returned here for analog alerts
alertClasses Alert classes are returned here for digital and analog alertd
summaryDpeList If Summary alert, the dpeList is returned here If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
exceptionInfo Details of any exceptions are returned here
References fwAlertConfig_get().
fwAlertConfig_getSummary (string dpe, bool & configExists, dyn_string & alertTexts, dyn_string & dpeList, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, dyn_string & exceptionInfo)
DEPRECATED - Returns the details of the summary alert configuration on a given dpe. This function raises an exception if the summary alert uses a DP pattern as this is not supported by the FW.
NOTE: THIS FUNCTION SHOULD NOT BE CALLED DIRECTLY, use fwAlertConfig_get
Constraints
Can only get summary alerts of type dp list (not dp pattern)
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertTexts Two alert texts will be returned if summary alert exists (alertText[1] = Good State Text, alertText[2] = Bad State Text)
dpeList The list of dp elements that are used in the alert summary If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
exceptionInfo Details of any exceptions are returned here
fwAlertConfig_modifyAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to modify an analog alert
For new function see fwAlertConfig_set
Usage
DEPRECATED
References fwAlertConfig_setAnalog().
Referenced by fwAlertConfig_setGeneral().
fwAlertConfig_modifyDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to modify a digital alert
For new function see fwAlertConfig_set
Usage
DEPRECATED
References fwAlertConfig_setDigital().
Referenced by fwAlertConfig_setGeneral().
fwAlertConfig_modifySummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to modify a summary alert
For new function see fwAlertConfig_set
Usage
DEPRECATED
References fwAlertConfig_setSummary().
bool fwAlertConfig_objectConfigExists (dyn_mixed alertConfigObject, int & configType, dyn_string & exceptionInfo)
Check if the paramaters object contains a configuration
Constraints
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject Object containing the alarm config parameters
configType Returns the type of the current alert config in the object
exceptionInfo Details of any exceptions are returned here
Returns:
TRUE if the configuration is present, FALSE else.
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_PARAM, and fwAlertConfig_ALERT_PARAM_TYPE.
Referenced by fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), and fwAlertConfig_objectExtractSummary().
fwAlertConfig_objectCreateAnalog (dyn_mixed & alertConfigObject, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_bool limitsIncluded, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE)
Creates a paramaters object for analog alarm.
example: creating an object with an analog alarm with 3 ranges
    fwAlertConfig_objectCreateAnalog(alarmObject,makeDynString("cool","warm","hot"),
                                     makeDynFloat(0,22,33), makeDynString("","_fwWarningAck.","_fwErrorAck."),
                                     "panel.pnl", makeDynString("datapointForPanel1.value","datapointForPanel2.value"),
                                     "This is a help text",makeDynBool(1,1,0), exception);
Constraints
not for discrete alarms
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject Reference to the object to create
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
alertLimits The limits of each range given here eg. makeDynFloat(20, 60);
alertClasses Alert classes for each range eg. makeDynString("_fwErrorAck.", "" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
limitsIncluded TRUE to include the limit (<=), FALSE else (<)
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
See also:
fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateSummary()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_VALUE, fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_TYPE, fwAlertConfig_objectConfigExists(), and fwAlertConfig_objectInitialize().
fwAlertConfig_objectCreateDigital (dyn_mixed & alertConfigObject, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE)
Creates a paramaters object for digital alarm. The object is set to the alarm using fwAlertConfig_objectSet
example: creating an object with a digital alarm with FALSE ("cool") as good range:
    fwAlertConfig_objectCreateDigital(alarmObject,makeDynString("cool","hot"),
                                     makeDynString("","_fwWarningAck."),
                                     "panel.pnl", makeDynString("datapointForPanel1.value","datapointForPanel2.value"),
                                     "This is a help text", exc);
Constraints
not for discrete alarms
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject Reference to the object to create
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
alertClasses Alert classes for each range eg. makeDynString("" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. eg. makeDynString("" , "_fwErrorAck.") for FALSE to be good state, makeDynString("_fwErrorAck." , "") for TRUE to be good state. Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
See also:
fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_TYPE, fwAlertConfig_objectConfigExists(), and fwAlertConfig_objectInitialize().
fwAlertConfig_objectCreateDiscrete (dyn_mixed & alertConfigObject, dyn_string alertTexts, dyn_string alertMatch, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, bool impulse, dyn_bool discreteNegation, string stateBits, dyn_string stateMatch, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE)
Creates a paramaters object for digital discrete or analog discrete alarm. The object is set to the alarm using fwAlertConfig_objectSet
example: creating an object with an analog discrete alarm with 3 ranges:
    fwAlertConfig_objectCreateDiscrete(alarmObject,makeDynString("cool","warm","hot"),
                                     makeDynString("*","22,23","24-27"), makeDynString("","_fwWarningAck.","_fwErrorAck."),
                                     "panel.pnl", makeDynString("datapointForPanel1.value","datapointForPanel2.value"),
                                     "", false, makeDynBool(0,1,0), "11000000000000000000000001010101XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                                     makeDynString("0010xxxxxxxxx0101011000000001000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","0010xxxxxxxxx0101011000000001000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","0010xxxxxxxxx0101011000000001000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"),
                                     exc);
Constraints
not for discrete alarms
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject Reference to the object to create
alertTexts Alert texts for each range. the first one is always the good one eg. makeDynString("Ok", "Bad Text", "Bad Text")
alertMatch Alert values that must match. Can be one value, a list of values or a range of values. The first value is always "*" e.g. makedynString("*","1,2","5-10")
alertClasses Alert classes for each range eg. makeDynString("" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. eg. makeDynString("" , "_fwErrorAck.") for FALSE to be good state, makeDynString("_fwErrorAck." , "") for TRUE to be good state. Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
impulse TRUE if alert is impulse alert else FALSE
discreteNegation for each match values, TRUE if the match is negated (i.e. "!=").
stateBits state bits of the discrete alert
stateMatch state bits of each value match
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
See also:
fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateSummary()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS, fwAlertConfig_ALERT_LIMIT_NEGATION, fwAlertConfig_ALERT_LIMIT_STATE_BITS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_VALUE_MATCH, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_DISCRETE, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_IMPULSE, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_TYPE, fwAlertConfig_objectConfigExists(), and fwAlertConfig_objectInitialize().
fwAlertConfig_objectCreateSummary (dyn_mixed & alertConfigObject, dyn_string alertTexts, int threshold, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE)
Creates a paramaters object for summary alarm. The object is set to the alarm using fwAlertConfig_objectSet
example: creating an object with a summary alarm with a list of 3 dpes, filtering the single alarms if more than 2:
    fwAlertConfig_objectCreateSummary(alarmObject, makeDynString("cool","hot"), 2, makeDynString("",""),
                                     makeDynString("testSingleAlarm_0001.val","testSingleAlarm_0003.val","testSingleAlarm_0004.val","testSingleAlarm_0005.val"),
                                     "panel.pnl", makeDynString("datapointForPanel1.value","datapointForPanel2.value"),
                                     "", exc);
Constraints
although existing in the parameter list, the alert class cannot be set not for discrete alarms
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject Reference to the object to create
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
threshold How many single alarms must be triggered before they are filtered (i.e. not visible) by the summary alarm.
alertClasses Alert classes for each range eg. makeDynString("" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. eg. makeDynString("" , "_fwErrorAck.") for FALSE to be good state, makeDynString("_fwErrorAck." , "") for TRUE to be good state. Don't forget to add the dot to the alert class names.
summaryDpeList List of dpes to include in summary alert
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
See also:
fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateDigital()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST, fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD, fwAlertConfig_ALERT_PARAM_TYPE, fwAlertConfig_objectConfigExists(), and fwAlertConfig_objectInitialize().
fwAlertConfig_objectExtractAnalog (dyn_mixed alertConfigObject, int & alertType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClasses, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, dyn_bool & limitsIncluded, bool & isActive, dyn_string & exceptionInfo)
Returns the details of an analog alert configuration in a parameter object preivously filled.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject object from where to extract the parameters
alertType Type of alert: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling DPCONFIG_NONE if no alert handling
alertTexts Alert texts are returned here
alertLimits Alert limits are returned here
alertClasses Alert classes are returned here
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
limitsIncluded if the limit is included (<=) or excluded (<)
isActive if alert is active
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractSummary()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_VALUE, fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ACTIVE, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_TYPE, and fwAlertConfig_objectConfigExists().
fwAlertConfig_objectExtractDigital (dyn_mixed alertConfigObject, int & alertType, dyn_string & alertTexts, dyn_string & alertClasses, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, dyn_string & exceptionInfo)
Returns the details of a digital alert configuration in a parameter object preivously filled.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject object from where to extract the parameters
alertType Type of alert: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling DPCONFIG_NONE if no alert handling
alertTexts Alert texts are returned here
alertClasses Alert classes are returned here
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive if alert is active
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ACTIVE, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_TYPE, and fwAlertConfig_objectConfigExists().
fwAlertConfig_objectExtractDiscrete (dyn_mixed alertConfigObject, int & alertType, dyn_string & alertTexts, dyn_string & alertMatches, dyn_string & alertClasses, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isDiscrete, bool & impulse, dyn_bool & discreteNegation, string & stateBits, dyn_string & stateMatch, bool & isActive, dyn_string & exceptionInfo)
Returns the details of a discrete alert configuration in a parameter object preivously filled.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject object from where to extract the parameters
alertType Type of alert: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_NONE if no alert handling
alertTexts Alert texts are returned here
alertMatches Alert limits are returned here
alertClasses Alert classes are returned here
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isDiscrete TRUE if the alert is discrete
impulse TRUE if alert is impulse alert else FALSE
discreteNegation for each match values, TRUE if the match is negated (i.e. "!=").
stateBits state bits of the discrete alert
stateMatch state bits of each value match
isActive if alert is active
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractSummary()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS, fwAlertConfig_ALERT_LIMIT_NEGATION, fwAlertConfig_ALERT_LIMIT_STATE_BITS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_VALUE_MATCH, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ACTIVE, fwAlertConfig_ALERT_PARAM_DISCRETE, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_IMPULSE, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_TYPE, and fwAlertConfig_objectConfigExists().
fwAlertConfig_objectExtractSummary (dyn_mixed alertConfigObject, int & alertType, dyn_string & alertTexts, dyn_string & summaryDpeList, int & threshold, string & alertClass, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, dyn_string & exceptionInfo)
Returns the details of a summary alert configuration in a parameter object preivously filled.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
alertConfigObject object from where to extract the parameters
alertType Type of alert: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling DPCONFIG_NONE if no alert handling
alertTexts Alert texts are returned here
threshold How many single alarms must be triggered before they are filtered (i.e. not visible) by the summary alarm.
summaryDpeList List of dpes to include in summary alert
alertClass Alert classes are returned here
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive if alert is active
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractDigital()
References fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ACTIVE, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST, fwAlertConfig_ALERT_PARAM_TYPE, and fwAlertConfig_objectConfigExists().
fwAlertConfig_objectGet (string dpe, dyn_mixed & alertConfigObject, dyn_string & exceptionInfo)
Returns the details of any alert configuration on a given dpe. This function can handle digital, analog and summary alerts. For more info refer to fwAlertConfig_objectSet()
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to read from
alertConfigObject returns the object containing the parameters and the limits objects of the alarm.
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectSet(), fwAlertConfig_objectSetMany(), fwAlertConfig_objectGetMany()
References fwAlertConfig_objectGetMany().
fwAlertConfig_objectGetMany (dyn_string & dpes, dyn_dyn_mixed & alertConfigObjects, dyn_string & exceptionInfo)
Get alarm based on alarm params and limits objects. For further info on how to handle alertConfigObjects, refer to the example in fwAlertConfig_objectSet()
Constraints
dpes in list must all belong to one system
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes Names of data point elements to read from. It is passed as reference only for performance reasons. It is not modified.
alertConfigObjects returns the objects containing the parameters and the limits objects of the alarm.
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectSet(), fwAlertConfig_objectSetMany(), fwAlertConfig_objectGet()
References _fwAlertConfig_objectCreateParams(), _fwConfigs_getConfigTypeAttribute(), fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS, fwAlertConfig_ALERT_LIMIT_NEGATION, fwAlertConfig_ALERT_LIMIT_STATE_BITS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_TEXT_WENT, fwAlertConfig_ALERT_LIMIT_VALUE, fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED, fwAlertConfig_ALERT_LIMIT_VALUE_MATCH, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ACTIVE, fwAlertConfig_ALERT_PARAM_DISCRETE, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST, fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD, fwAlertConfig_ALERT_PARAM_TYPE, and fwAlertConfig_objectInitialize().
Referenced by fwAlertConfig_objectGet().
fwAlertConfig_objectInitialize (dyn_mixed & paramsObject, int totalRanges)
Set alarm object based on alarm params and limits. See note on fwAlertConfig_objectSet() for an example
Constraints
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
paramsObject object containing the alarm parameters and limits
totalRanges alarm ranges
References _fwAlertConfig_objectCreateParams(), fwAlertConfig_ALERT_LIMIT, and fwAlertConfig_ALERT_PARAM.
Referenced by fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectGetMany(), and fwAlertConfig_setMany().
fwAlertConfig_objectSet (string dpe, dyn_mixed alertConfigObject, dyn_string & exceptionInfo)
Set the alert with the alert parameter object. The alert parameter object must be previously filled. The object is a dyn_mixed variable. It is made of two dyn_dyn_mixed sub-variables:
limits parameters (index fwAlertConfig_ALERT_LIMIT), contains the parameters per range (classes, values...).
general parameters (index fwAlertConfig_ALERT_PARAM), contains the other parameters of the alarm (type, panel...).
How to fill the parameters object: use one of the functions "fwAlertConfig_objectCreate..." or fill it manually as in the examples given here:
example 1: create an analog alert object (3 ranges) using the utility functions and set it to the dpe
    dyn_mixed alarmObject;
    dyn_string exc;
    //create the alarm object
    fwAlertConfig_objectCreateAnalog(
            alarmObject, //the object that will contain the alarm settings
            makeDynString("too cold","normal","too hot"), //the text for the 3 ranges
            makeDynFloat(0,22,33), //the 3 ranges are separated by the values 22 and 33. The 1st value must always be 0.
            makeDynString("_fwWarningAck.","","_fwErrorAck."), //classes
            makeDynString(""), //$-params to pass to the alarm panel, if necessary
            "", //alarm help, if needed
            makeDynBool(0,1,0), //value included (1 means ">=", 0 means ">", 1st element ignored). Here: <= 22: too cold; 23..32: normal; >= 33: too hot
            exc); //exception info returned here
    //set the alarm to the dpe
    fwAlertConfig_objectSet("testSingleAlarm_01.val", alarmObject, exc);
    //activate it
    fwAlertConfig_activate("testSingleAlarm_01.val", exc);
example 2: create a discrete alert object (3 ranges) using the utility functions and set it to the dpe
    dyn_mixed alarmObject;
    dyn_string exc;
    //create the alarm object
    fwAlertConfig_objectCreateDiscrete(
            alarmObject, //the object that will contain the alarm settings
            makeDynString("ok","not valid","error"), //the text for the 3 ranges
            makeDynString("*","22,23","24-27"), //the 3 ranges must match these values (the 1st must be always the good one - *)
            makeDynString("","_fwWarningAck.","_fwErrorAck."), //classes (the 1st one must always be the good one)
            "", //alarm panel, if necessary
            makeDynString(""), //$-params to pass to the alarm panel, if necessary
            "", //alarm help, if needed
            false, //impulse alarm
            makeDynBool(0,0,0), //negation of the matching (0 means "=", 1 means "!=")
            "", //state bits that must also match for the alarm
            makeDynString("","",""), //state bits that must match for each range
            exc ); //exception info returned here
    //set the alarm to the dpe
    fwAlertConfig_objectSet("testSingleAlarm_01.val", alarmObject, exc);
    //activate it
    fwAlertConfig_activate("testSingleAlarm_01.val", exc);
example 3: create and set an analog alarm with 3 ranges and the basic parameters
    dyn_mixed alarmObject;
    dyn_dyn_anytype alarmLimits, alarmParams;
    dyn_string exc;
    //initialize the alarm object with 3 ranges:
    fwAlertConfig_objectInitialize(alarmObject,3);
    //extract the limits parameters from the alarm object:
    alarmLimits = alarmObject[fwAlertConfig_ALERT_LIMIT];
    //set the limits parameters:
    //text for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "cold";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_TEXT] = "hot";
    //values delimiting the ranges of the alarm.
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_VALUE] = 0; //1st element is always ignored
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_VALUE] = 22;
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_VALUE] = 33;
    //class for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = ""; //this is the ok range: no class
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwErrorAck.";
    //store the limits parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_LIMIT] = alarmLimits;
    //extract the general parameters of the object:
    alarmParams = alarmObject[fwAlertConfig_ALERT_PARAM];
    //set the general parameters:
    //set the type of the alarm
    alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_NONBINARYSIGNAL;
    //store the general parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_PARAM] = alarmParams;
    //set the object to the datapoint element:
    fwAlertConfig_objectSet("testSingleAlarm_01.val", alarmObject, exc);
    //activate the alarm
    fwAlertConfig_activate("testSingleAlarm_01.val", exc);
example 4: create and set a digital alarm with false = ok, true = alarm
    dyn_mixed alarmObject;
    dyn_dyn_anytype alarmLimits, alarmParams;
    dyn_string exc;
    //initialize the alarm object with 2 ranges:
    fwAlertConfig_objectInitialize(alarmObject,2);
    //extract the limits parameters from the alarm object:
    alarmLimits = alarmObject[fwAlertConfig_ALERT_LIMIT];
    //set the limits parameters:
    //text for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "error";
    //class for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
    //store the limits parameters back to the object:
    alarmObject[fwAlertConfig_ALERT_LIMIT] = alarmLimits;
    //extract the general parameters of the alarm object:
    alarmParams = alarmObject[fwAlertConfig_ALERT_PARAM];
    //set the general parameters:
    alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_BINARYSIGNAL;
    //store the general parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_PARAM] = alarmParams;
    //set the object to the datapoint element:
    fwAlertConfig_objectSet("testSingleAlarm_01.trip", alarmObject, exc);
    //activate the alarm:
    fwAlertConfig_activate("testSingleAlarm_01.trip", exc);
example 5: create and set a digital alarm with false = alarm, true = ok
    dyn_mixed alarmObject;
    dyn_dyn_anytype alarmLimits, alarmParams;
    dyn_string exc;
    //initialize the alarm object with 2 ranges:
    fwAlertConfig_objectInitialize(alarmObject,2);
    //extract the limits parameters of the object:
    alarmLimits = alarmObject[fwAlertConfig_ALERT_LIMIT];
    //set the limits parameters:
    //text for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "error";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
    //class for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
    //store the limits parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_LIMIT] = alarmLimits;
    //extract the general parameters of the alarm object:
    alarmParams = alarmObject[fwAlertConfig_ALERT_PARAM];
    //set the general parameters:
    alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_BINARYSIGNAL;
    //store the general parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_PARAM] = alarmParams;
    //set the object to the datapoint element:
    fwAlertConfig_objectSet("testSingleAlarm_01.trip", alarmObject, exc);
    //activate the alarm:
    fwAlertConfig_activate("testSingleAlarm_01.trip", exc);
example 6: create a discrete alert object with 3 ranges and the basic parameters
    dyn_mixed alarmObject;
    dyn_dyn_anytype alarmLimits, alarmParams;
    dyn_string exc;
    //initialize the alarm object with 3 ranges:
    fwAlertConfig_objectInitialize(alarmObject,3);
    //extract the limits parameters of the alarm object:
    alarmLimits = alarmObject[fwAlertConfig_ALERT_LIMIT];
    //set the limits parameters:
    //text for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "system ok"; //1st element must always be the good range;
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "no connection";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_TEXT] = "system fault";
    //value to be matched for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_VALUE_MATCH] = "*"; //1st element must always be the good range;
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_VALUE_MATCH] = "22, 23, 24";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_VALUE_MATCH] = "29-33";
    //if value to be matched for each range of the alarm must be negated (this is an option)
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_NEGATION] = false; //1st element must always be the good range;
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_NEGATION] = true;
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_NEGATION] = false;
    //class for each range of the alarm
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = ""; //1st element must always be the good range;
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwErrorAck.";
    //pattern match of state bits (this is an option)
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_STATE_BITS] = "11000000000000000000000001010101XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"; //only the 1st element is considered. All the others are ignored;
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_STATE_BITS] = "";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_STATE_BITS] = "";
    //pattern match of state bits for each range (this is an option)
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS] = ""; //1st element must always have this value;
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS] = "0010xxxxxxxxx0101011000000001000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS] = "001x00xxxxxxx010xx11011110000000XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    //store the limits parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_LIMIT] = alarmLimits;
    //extract the general parameters of the alarm object:
    alarmParams = alarmObject[fwAlertConfig_ALERT_PARAM];
    //set the general parameters:
    //the alarm is a non-binary one
    alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_NONBINARYSIGNAL;
    //the alarm is discrete
    alarmParams[fwAlertConfig_ALERT_PARAM_DISCRETE][1] = true;
    //store the general parameters back to the alarm object:
    alarmObject[fwAlertConfig_ALERT_PARAM] = alarmParams;
    //set the object to the datapoint element:
    fwAlertConfig_objectSet("testSingleAlarm_01.val", alarmObject, exc);
    //activate the alarm:
    fwAlertConfig_activate("testSingleAlarm_01.val", exc);
example 7: create a summary alert object and set it to the dpe
    dyn_mixed alarmObject;
    dyn_dyn_anytype alarmLimits, alarmParams;
    dyn_string exc;
    //initialize the params object (2 ranges for ummary alert):
    fwAlertConfig_objectInitialize( alarmObject,2);
    //extract the limits parameters of the object:
    alarmLimits = alarmObject[fwAlertConfig_ALERT_LIMIT];
    //set the limits parameters:
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "on";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "error";
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
    //store the limits parameters back to the object:
    alarmObject[fwAlertConfig_ALERT_LIMIT] = alarmLimits;
    //extract the general parameters of the object:
    alarmParams = alarmObject[fwAlertConfig_ALERT_PARAM];
    //set the general parameters:
    alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_SUM_ALERT;
    alarmParams[fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST] = makeDynString("testSingleAlarm_0001.val","testSingleAlarm_0003.val","testSingleAlarm_0004.val");
    alarmParams[fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD][1] = 2;
    //store the general parameters back to the object:
    alarmObject[fwAlertConfig_ALERT_PARAM] = alarmParams;
    //set the object to the datapoint element:
    fwAlertConfig_objectSet("testSingleAlarm_01.string", alarmObject, exc);
    //activate the alarm:
    fwAlertConfig_activate("testSingleAlarm_01.string", exc);
Constraints
The alert parameter object must be previously filled.
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe the datapoint element to configure
alertConfigObject object from where to extract the parameters
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectGet(), fwAlertConfig_objectSetMany(), fwAlertConfig_objectGetMany()
References fwAlertConfig_objectSetMany().
fwAlertConfig_objectSetMany (dyn_string & dpes, dyn_dyn_mixed & alertConfigObjects, dyn_string & exceptionInfo)
Set the alert with the alert parameter object alertConfigObject. The alert parameter object must be previously filled. How to fill it: fill each elemt of the array alertConfigObject[i] using one of the functions "fwAlertConfig_objectCreate..." or fill it manually as in the examples given for fwAlertConfig_objectSet()
One object per dpe must be filled. Optionally, one only object (index 1) can be filled and several dpes can be passed. In such case, the function sets the same object to all the dpes. In this case, the dpes must all be of the same type.
This function is more efficient that applying the function fwAlertConfig_objectSet() in a loop.
example 1: create 3-ranges alarms for 2 datapoint elements
  dyn_dyn_anytype alarmLimits, alarmParams;
  dyn_dyn_mixed alarmObject;
  dyn_anytype alarms;
  dyn_string exc, dpe;
  int i;
  //list of datapoint elements
  dpe = makeDynString("dpe1","dpe2");
  // alarm 1
  i = 1;
  //initialize alarm object
  fwAlertConfig_objectInitialize(alarmObject[i],3);
  //extract limits array
  alarmLimits = alarmObject[i][2];
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "warm";
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_TEXT] = "hot";
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_VALUE] = 0;
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_VALUE] = 11;
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_VALUE] = 22;
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwErrorAck.";
  //extract parameters array:
  alarmParams = alarmObject[i][1];
  //set the type
  alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_NONBINARYSIGNAL;
  //put limits and parameters arrays to the object:
  alarmObject[i][1] = alarmParams;
  alarmObject[i][2] = alarmLimits;
  // alarm 2
  i = 2;
  //initialize alarm object
  fwAlertConfig_objectInitialize(alarmObject[i],3);
  //extract limits array:
  alarmLimits = alarmObject[i][2];
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "high voltage";
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_TEXT] = "voltage trip";
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_VALUE] = 0;
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_VALUE] = 1000;
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_VALUE] = 1100;
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwErrorAck.";
  //extract parameters array
  alarmParams = alarmObject[i][1];
  //set the type
  alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_NONBINARYSIGNAL;
  //put limits and parameters arrays to the object:
  alarmObject[i][1] = alarmParams;
  alarmObject[i][2] = alarmLimits;
  //set the 2 alarms to the 2 dpes:
  fwAlertConfig_objectSetMany(dpe,alarmObject, exc);
  //activate the alerts
  fwAlertConfig_activateMultiple(dpe, exc);
example 2: create a 3-ranges alarm and set it to 4 datapoint elements. Note: the dpes must all be of the same type.
  dyn_dyn_anytype alarmLimits, alarmParams;
  dyn_dyn_mixed alarmObject;
  dyn_anytype alarms;
  dyn_string exc, dpe;
  //list of datapoint elements
  dpe = makeDynString("dpe1","dpe2","dpe3","dpe4");
  //initialize alarm object
  fwAlertConfig_objectInitialize( alarmObject[1],3);
  //extract limits array:
  alarmLimits = alarmObject[1][2];
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "warm";
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_TEXT] = "hot";
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_VALUE] = 0;
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_VALUE] = 11;
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_VALUE] = 22;
  alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
  alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
  alarmLimits[3][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwErrorAck.";
  //extract parameters array:
  alarmParams = alarmObject[1][1];
  //set the type
  alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_NONBINARYSIGNAL;
  //put limits and parameters arrays to the object:
  alarmObject[1][1] = alarmParams;
  alarmObject[1][2] = alarmLimits;
  //set the 4 dpes with the same alarm setting:
  fwAlertConfig_objectSetMany(dpe,alarmObject, exc);
  //activate the alerts
  fwAlertConfig_activateMultiple(dpe, exc);
example 3: create 4 alarms and set them to 4 datapoint elements of type bit32.
  dyn_dyn_mixed alarmConfigObject;
  dyn_string exc, dpe;
  int i;
  dyn_dyn_anytype alarmLimits, alarmParams;
  dyn_dyn_mixed alarmObject;
  dyn_anytype alarms;
  //list of datapoint elements
  dpe = makeDynString("dpe1","dpe2","dpe3","dpe4");
  //initialize alarm object
  fwAlertConfig_objectInitialize(alarmObject,3);
  //extract parameters array:
  alarmParams = alarmObject[1];
  //extract limits array:
  alarmLimits = alarmObject[2];
  //set the 4 alarm settings:
  for(i=1 ; i<=(dynlen(dpe)) ; i++)
  {
    //set the texts (first text is always the normal range)
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_TEXT] = "ok";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_TEXT] = "warning";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_TEXT] = "fault";
    //set the pattern match (first pattern is always the normal range *)
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_VALUE_MATCH] = "*";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_VALUE_MATCH] = "10010111101";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_VALUE_MATCH] = "10001011011,000110110101";
    //set the class for each value match
    alarmLimits[1][fwAlertConfig_ALERT_LIMIT_CLASS] = "";
    alarmLimits[2][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwWarningAck.";
    alarmLimits[3][fwAlertConfig_ALERT_LIMIT_CLASS] = "_fwErrorAck.";
    //set the parameters common to the alarm
    alarmParams[fwAlertConfig_ALERT_PARAM_TYPE][1] = DPCONFIG_ALERT_NONBINARYSIGNAL;
    alarmParams[fwAlertConfig_ALERT_PARAM_DISCRETE][1] = true;
    alarmParams[fwAlertConfig_ALERT_PARAM_RANGES][1] = 3;
    //put limits and parameters arrays to the object:
    alarmObject[i][1] = alarmParams;
    alarmObject[i][2] = alarmLimits;
  }
  //set the 4 dpes with the 4 alarm settings:
  fwAlertConfig_objectSetMany(dpe,alarmObject, exc);
  //activate the alerts
  fwAlertConfig_activateMultiple(dpe, exc);
}
Constraints
The alert parameter object must be previously filled.
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of datapoint elements to configure. It is passed as reference only for performance reasons. It is not modified.
alertConfigObjects list of objects from where to extract the parameters. The amount of alarm configuration objects must match the amount of dpes. Alternatively, if the number of alarm configuration objects is only one, that configuration is then applied to all the dpes in the list. Passed as reference only for performance reasons. Not modified.
exceptionInfo Details of any exceptions are returned here
See also:
fwAlertConfig_objectSet(), fwAlertConfig_objectGet(), fwAlertConfig_objectGetMany()
References _fwAlertConfig_prepareAnalog(), _fwAlertConfig_prepareAnalogDiscrete(), _fwAlertConfig_prepareDigital(), _fwAlertConfig_prepareDigitalDiscrete(), _fwAlertConfig_prepareSummary(), _fwConfigs_getConfigOptionsForDpe(), _fwConfigs_getConfigTypeAttribute(), fwAlertConfig_activateMultiple(), fwAlertConfig_addDpInAlertSummary(), fwAlertConfig_ALERT_LIMIT, fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS, fwAlertConfig_ALERT_LIMIT_NEGATION, fwAlertConfig_ALERT_LIMIT_STATE_BITS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_TEXT_WENT, fwAlertConfig_ALERT_LIMIT_VALUE, fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED, fwAlertConfig_ALERT_LIMIT_VALUE_MATCH, fwAlertConfig_ALERT_PARAM, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_DISCRETE, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_IMPULSE, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST, fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD, fwAlertConfig_ALERT_PARAM_TYPE, and fwAlertConfig_deactivateMultiple().
Referenced by fwAlertConfig_objectSet(), and fwAlertConfig_setMany().
fwAlertConfig_set (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE, bool discrete = FALSE, bool impulse = FALSE, dyn_bool discreteNegation = FALSE, string stateBits = "", dyn_string stateMatch = "")
Sets the alert configuration on a given dpe. This function can handle digital, analog, discrete and summary alerts.
Constraints
Can only get summary alerts of type dp list (not dp pattern)
For digital alerts: The length of the alertTexts and alertClasses dyn_strings must both be 2 For analog alerts: The length of the alertTexts and alertClasses dyn_strings must be equal The length of the alertLimits dyn_float must be one less than the length of alertTexts For summary alerts: The length of the alertTexts dyn_string must be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling DPCONFIG_SUM_ALERT for summary alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
summaryDpeList If Summary alert, the dpeList is passed here (otherwise ignored). If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify one value (i.e. 000010011000) per alarm.
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
References fwAlertConfig_setMany().
Referenced by fwAlertConfig_addDpInAlertSummary(), fwAlertConfig_deleteDpFromAlertSummary(), fwAlertConfig_setAnalog(), fwAlertConfig_setDigital(), and fwAlertConfig_setSummary().
fwAlertConfig_setAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE)
DEPRECATED - Please use fwAlertConfig_set instead Creates analog alert handling on the given data point element without hysteresis. The alert texts, alert limits, alert classes and the alert and help panels are set.
Constraints
The length of the alertTexts and alertClasses dyn_strings must be equal The length of the limits dyn_float must be one less than the length of alertTexts
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
limits The limits of each range given here eg. makeDynFloat(20, 60);
alertClasses Alert classes for each range eg. makeDynString("_fwErrorAck.", "" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. With TRUE this is equal to the functionality provided by fwAlertConfig_modifyAnalog With FALSE this is equal to the functionality provided by fwAlertConfig_createAnalog
References fwAlertConfig_set().
Referenced by fwAlertConfig_createAnalog(), and fwAlertConfig_modifyAnalog().
fwAlertConfig_setDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE)
DECPRECATED - Please use fwAlertConfig_set instead Creates digital alert handling on the given data point element. The alert texts, alert class of the bad state and the alert and help panels are set.
Constraints
The length of the alertTexts and alertClasses dyn_strings must both be 2
Usage
DECPRECATED
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
alertTexts Alert texts eg. makeDynString("Bad Text", "OK")
alertClasses Alert classes eg. makeDynString("_fwErrorAck.", "") One of the items of the dyn_string must always be empty to indicate the valid state The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. With TRUE this is equal to the functionality provided by fwAlertConfig_modifyDigital With FALSE this is equal to the functionality provided by fwAlertConfig_createDigital
References fwAlertConfig_set().
Referenced by fwAlertConfig_createDigital(), and fwAlertConfig_modifyDigital().
fwAlertConfig_setDiscrete (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, bool storeInParamHistory = TRUE, bool discrete = FALSE, bool impulse = FALSE, dyn_bool discreteNegation = FALSE, string stateBits = "", dyn_string stateMatch = "")
Sets the discrete alert configuration on a given dpe. This function can handle discrete digital and discrete analog alerts
Constraints
This function can handle only discrete alerts
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify one value (i.e. 000010011000) per alarm.
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
References fwAlertConfig_setMany().
fwAlertConfig_setGeneral (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClass, string alertPanel, dyn_string alertPanelParameters, string help, bool alertRequest, dyn_string & exceptionInfo)
DEPRECATED - Modifies an existing analog alert handling with 5 ranges on the given data point element. The function has similar functionality to _fwAlertConfig_createAnalog5 except that the type of alert handling for the config are not altered. This avoids problems which occur when altering the type of the alert config when something is dpConencted to the config.
NOTE: THIS FUNCTION SHOULD NOT BE USED (see constraints below), use fwAlertConfig_set
Constraints
This is an internal function and should not be called directly To modify an analog alert with 5 ranges the function fwAlertConfig_set should be used
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
alertTexts Alert texts for each range
limits The limits of each range given here
alertClass Alert classes for each range One of the items of the dyn_string must always be empty to indicate the valid state. Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in alertPanel
help Help text or path to help file
alertRequest whether to delete (FALSE) or create/modify (TRUE) the alert config
exceptionInfo Details of any exceptions are returned here
References _fwConfigs_getConfigOptionsForDpe(), fwAlertConfig_createAnalog(), fwAlertConfig_createDigital(), fwAlertConfig_deleteAnalog(), fwAlertConfig_deleteDigital(), fwAlertConfig_modifyAnalog(), and fwAlertConfig_modifyDigital().
fwAlertConfig_setLimits (string dpe, dyn_int limitNumbers, dyn_float limitValues, dyn_string & exceptionInfo, bool checkBeforeSetting = FALSE, bool storeInParamHistory = TRUE)
Sets the alert limits for the currently configured alert ranges on the given data point element. The values in the same position in limitNumbers and limitValues form a pair of values. The pair consists of the limit number to act on and limit value to set.
Example usage:
limitNumbers = {3,4,2} limitValues = {30,50,10} This will set the limit between Range 2 and 3 to 10 This will set the limit between Range 3 and 4 to 30 This will set the limit between Range 4 and 5 to 50
NOTE: Not all the limits need to be specified in the input parameters
NOTE: Values in limitNumbers must be between 1 and (number of ranges - 1)
Constraints
Only works on data points that have an analog alert handling set up. This function can not change the number of ranges defined in the alert config. If only some limits are specified, the new limits must be consistent with the old values that will not be modified
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe Data point element to set the limits to
limitNumbers The numbers of the limits to be modified are passed here
limitValues The values of the limits to be modified are passed here The values in this list correspond to the limit numbers given in limitNumbers
exceptionInfo Details of any exceptions are returned here
checkBeforeSetting OPTIONAL PARAMETER - default value FALSE If TRUE, the new limit values are compared with the existing limits to check that the final configuration will be consistent (i.e. all the range limits are in ascending order with no duplicates). In case of inconsistencies, an exception will be raised. If FALSE, the new limits are not checked and an error will appear in the log when the dpSetWait is performed and an exception will be raised.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
References _fwAlertConfig_checkLimits(), fwAlertConfig_activate(), fwAlertConfig_deactivate(), and fwAlertConfig_getLimits().
fwAlertConfig_setMany (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_dyn_string summaryDpeList, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE, dyn_bool discrete = FALSE, dyn_bool impulse = FALSE, dyn_dyn_bool discreteNegation = FALSE, dyn_string stateBits = "", dyn_dyn_string stateMatch = "")
Sets the alert configuration on for a list of dpes. This function can handle digital, analog, discrete and summary alerts
Constraints
Can only set summary alerts of type dp list (not dp pattern)
For digital alerts: The length of the alertTexts and alertClasses dyn_strings must both be 2 For analog alerts: The length of the alertTexts and alertClasses dyn_strings must be equal The length of the alertLimits dyn_float must be one less than the length of alertTexts For summary alerts: The length of the alertTexts dyn_string must be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes List of data point elements
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling DPCONFIG_SUM_ALERT for summary alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
summaryDpeList If Summary alert, the dpeList is passed here (otherwise ignored) If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify a value (i.e. 000010011000)
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
References _fwAlertConfig_prepareAnalog(), _fwAlertConfig_prepareAnalogDiscrete(), _fwAlertConfig_prepareDigital(), _fwAlertConfig_prepareDigitalDiscrete(), _fwAlertConfig_prepareSummary(), _fwConfigs_getConfigOptionsForDpe(), _fwConfigs_getConfigTypeAttribute(), fwAlertConfig_activateMultiple(), fwAlertConfig_addDpInAlertSummary(), fwAlertConfig_ALERT_LIMIT_CLASS, fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS, fwAlertConfig_ALERT_LIMIT_NEGATION, fwAlertConfig_ALERT_LIMIT_STATE_BITS, fwAlertConfig_ALERT_LIMIT_TEXT, fwAlertConfig_ALERT_LIMIT_TEXT_WENT, fwAlertConfig_ALERT_LIMIT_VALUE, fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED, fwAlertConfig_ALERT_LIMIT_VALUE_MATCH, fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY, fwAlertConfig_ALERT_PARAM_DISCRETE, fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET, fwAlertConfig_ALERT_PARAM_HELP, fwAlertConfig_ALERT_PARAM_IMPULSE, fwAlertConfig_ALERT_PARAM_MODIFY_ONLY, fwAlertConfig_ALERT_PARAM_PANEL, fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS, fwAlertConfig_ALERT_PARAM_RANGES, fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY, fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST, fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD, fwAlertConfig_ALERT_PARAM_TYPE, fwAlertConfig_deactivateMultiple(), fwAlertConfig_objectInitialize(), and fwAlertConfig_objectSetMany().
Referenced by fwAlertConfig_set(), fwAlertConfig_setDiscrete(), fwAlertConfig_setManyDiscrete(), and fwAlertConfig_setMultiple().
fwAlertConfig_setManyDiscrete (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, bool storeInParamHistory = TRUE, dyn_bool discrete = FALSE, dyn_bool impulse = FALSE, dyn_dyn_bool discreteNegation = FALSE, dyn_string stateBits = "", dyn_dyn_string stateMatch = "")
Sets the alert configuration on for a list of dpes. This function can handle discrete analog and discrete digital alerts
Constraints
This function can handle only discrete alerts
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes List of data point elements
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify one value (i.e. 000010011000) per alarm.
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
References fwAlertConfig_setMany().
fwAlertConfig_setMultiple (dyn_string dpes, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE, bool discrete = FALSE, bool impulse = FALSE, dyn_bool discreteNegation = FALSE, string stateBits = "", dyn_string stateMatch = "")
Sets the alert configuration on for a list of dpes. This function can handle digital, analog and summary alerts
Constraints
Can only set summary alerts of type dp list (not dp pattern)
For digital alerts: The length of the alertTexts and alertClasses dyn_strings must both be 2 For analog alerts: The length of the alertTexts and alertClasses dyn_strings must be equal The length of the alertLimits dyn_float must be one less than the length of alertTexts For summary alerts: The length of the alertTexts dyn_string must be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes List of data point elements
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling DPCONFIG_SUM_ALERT for summary alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
summaryDpeList If Summary alert, the dpeList is passed here (otherwise ignored) If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify a value (i.e. 000010011000)
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
References fwAlertConfig_setMany().
fwAlertConfig_setSummary (string dpe, dyn_string alertTexts, dyn_string dpElementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE)
DEPRECATED - Please use fwAlertConfig_set instead Creates summary alert handling on the given data point element.
Constraints
The length of the alertTexts should be 2 Can only set summary alerts of type dp list (not dp pattern)
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters:
dpe Name of data point element to act on
alertTexts Alert texts eg. makeDynString("OK", "Bad")
dpElementList List of dpes to include in summary alert. If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. With TRUE this is equal to the functionality provided by fwAlertConfig_modifySummary With FALSE this is equal to the functionality provided by fwAlertConfig_createSummary
References fwAlertConfig_set().
Referenced by fwAlertConfig_createSummary(), and fwAlertConfig_modifySummary().
Variable Documentation
const int fwAlertConfig_ALERT_LIMIT = 2
Description
Limits configuration object. The configuration object contains 2 sub-elements:
ALERT_PARAM, containing elements for general configuration (type... - all fwAlertConfig_ALERT_PARAM_*).
ALERT_LIMIT, containing elements concerning limits (text, values, class... - all fwAlertConfig_ALERT_LIMIT_*).
Parameter Type
dyn_dyn_anytype
Usage
Compulsory. For all types of alarms. See use example on fwAlertConfig_objectSet().
Referenced by fwAlertConfig_objectConfigExists(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectInitialize(), and fwAlertConfig_objectSetMany().
const int fwAlertConfig_ALERT_LIMIT_CLASS = 4
Description
Limit configuration item. Class of the alarm range. The ok range must be an empty string "". For more info, refer to PVSS help.
Parameter Type
string
Usage
Compulsory. For all types of alarms. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_LIMITS_STATE_BITS = 10
Description
Limit configuration item. State bits values that must match for a specific range. For more detail, see PVSS help.
Parameter Type
string
Usage
Optional. For discrete alarms only. Default value is "". Possible values: 1, 0 (ex: "11000000000000000000000001010101XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"). 0 = must be 0; 1 = must be 1. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_NEGATION = 8
Description
Limit configuration item. If true, the value to match for the alarm range is negated (!=). If false, the value must match (=).
Parameter Type
bool
Usage
Optional. For discrete alarms only. Default value is false. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_STATE_BITS = 9
Description
Limit configuration item. State bits values that must match. For more detail, see PVSS help.
Parameter Type
string
Usage
Optional. For discrete alarms only. Default value is "". Possible values: 1, 0, X (ex: "11000000000000000000000001010101XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"). 0 = must be 0; 1 = must be 1; X = can be 0 or 1. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_TEXT = 1
Description
Limit configuration item. Text of the alarm range, shown when the alert is flagged as CAME.
Parameter Type
string
Usage
Compulsory. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_TEXT_WENT = 11
Description
Limit configuration item. Text of the alarm range, shown when the alert is flagged as WENT.
Parameter Type
string
Usage
Optional. For all types of alarms. Default value is "". See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_VALUE = 2
Description
Limit configuration item. Value of the alarm range.
Parameter Type
float
Usage
Compulsory for analog alarms. For analog alarms only. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_VALUE_INCLUDED = 3
Description
Limit configuration item. Specify if the value of the alarm range must be included (<=) or not (<). True means included.
Parameter Type
bool
Usage
Optional. For analog alarms. Default value is false. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_LIMIT_VALUE_MATCH = 5
Description
Limit configuration item. Value to match for the alarm range. Can be one value (i.e. "3"), a set of values (i.e. "3,5,6"), or a range (i.e. "3-7")
Parameter Type
string
Usage
Compulsory for discrete alarms. For discrete alarms only. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM = 1
Description
General configuration object. The configuration object contains 2 sub-elements:
ALERT_PARAM, containing elements for general configuration (type... - all fwAlertConfig_ALERT_PARAM_*).
ALERT_LIMIT, containing elements concerning limits (text, values, class... - all fwAlertConfig_ALERT_LIMIT_*).
Parameter Type
dyn_dyn_anytype
Usage
Compulsory. For all types of alarms. See use example on fwAlertConfig_objectSet().
Referenced by fwAlertConfig_objectConfigExists(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectInitialize(), and fwAlertConfig_objectSetMany().
const int fwAlertConfig_ALERT_PARAM_ACTIVE = 14
Description
General parameter item. If true, the alarm is active.
Parameter Type
bool
Usage
Optional. READ ONLY. For all types of alarms.
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), and fwAlertConfig_objectGetMany().
const int fwAlertConfig_ALERT_PARAM_ADD_DPE_TO_SUMMARY = 3
Description
General parameter item. Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e.
addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs.
addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries".
Note: The summary alarms must already exist. If they do not exist, it WILL NOT be created.
Parameter Type
string
Usage
Optional. For alarms of type analog, discrete, binary. Default value is "". See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_DISCRETE = 8
Description
General parameter item. Set to true if discrete alarm. To false if else.
Parameter Type
bool
Usage
Optional. For discrete alarms only. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_FALLBACK_TO_SET = 11
Description
General parameter item. Used in combination with modifyOnly. Default value: false.
If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised.
If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
Parameter Type
bool
Usage
Optional. For all types of alarms. Default value is false. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_HELP = 7
Description
General parameter item. Enter a text to assist the user with information concerning the alert. This text can either be interpreted as "pure" text in the control script and displayed in the panel or also used as a file name (e.g. of an HTML file).
Parameter Type
string
Usage
Optional. For all alarms. Default value is "". See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_IMPULSE = 9
Description
General parameter item. true = impulse alarm. For more info, refer to PVSS help.
Parameter Type
bool
Usage
Optional. For discrete alarms only. Default value is false. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_MODIFY_ONLY = 10
Description
General parameter item. Set to true to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
Parameter Type
bool
Usage
Optional. For all types of alarms. Default value is false. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_PANEL = 5
Description
General parameter item. Displays the file path of the panel to be displayed when an alert occurs. The path is specified relative to the panel directory.
Parameter Type
string
Usage
Optional. For all alarms. Default value is "". See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_PANEL_PARAMETERS = 6
Description
General parameter item. Here you can enter $-parameters to be passed when calling the panel specified on fwAlertConfig_ALERT_PARAM_PANEL.
Parameter Type
dyn_string
Usage
Optional. For all alarms. Default value is empty. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_RANGES = 13
Description
General parameter item. Number of alarm ranges.
Parameter Type
int
Usage
Compulsory. For analog and discrete alarms. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_STORE_IN_HISTORY = 12
Description
General parameter item. You can specify if the change should be stored in the Paramterisation History of PVSS.
Parameter Type
bool
Usage
Optional. For all types of alarms. Default value is true. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_SUM_DPE_LIST = 2
Description
General parameter item. For summary alert, list of DPEs to be checked for single alarms. If you want to specify a DP pattern, then this should entered as the first item in this list.
Parameter Type
dyn_string
Usage
Optional. For summary alarms only. Default value is empty. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_SUM_THRESHOLD = 4
Description
General parameter item. Threshold filter parameter for the sum alerts. It can be used to specify after how many single alarms only the sum alert should be shown. If i.e. the threshold 5 is set and there are five single alarms, only the sum alert is shown in the alert screen.
Parameter Type
int
Usage
Optional. For summary alarms only. Default value is 0. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().
const int fwAlertConfig_ALERT_PARAM_TYPE = 1
Description
General parameter item. Type of alarm. Possible values:
DPCONFIG_NONE
DPCONFIG_ALERT_BINARYSIGNAL
DPCONFIG_ALERT_NONBINARYSIGNAL
DPCONFIG_SUM_ALERT
For more info, refer to PVSS help.
Parameter Type
int
Usage
Compulsory. For all types of alarms. See use example on fwAlertConfig_objectSet().
Referenced by _fwAlertConfig_objectCreateParams(), fwAlertConfig_objectConfigExists(), fwAlertConfig_objectCreateAnalog(), fwAlertConfig_objectCreateDigital(), fwAlertConfig_objectCreateDiscrete(), fwAlertConfig_objectCreateSummary(), fwAlertConfig_objectExtractAnalog(), fwAlertConfig_objectExtractDigital(), fwAlertConfig_objectExtractDiscrete(), fwAlertConfig_objectExtractSummary(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), and fwAlertConfig_setMany().