fwAlarmHandlingScreen.ctl File Reference
fwAlarmHandlingScreen.ctl File Reference
Functions
fwAlarmHandlingScreen_readFilter (dyn_dyn_anytype &aesFilter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_showFilter (dyn_dyn_anytype aesFilter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_loadFilter (string fwAesConfigDp, dyn_dyn_anytype &aesFilter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_saveFilter (string fwAesConfigDp, dyn_dyn_anytype aesFilter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_applyFilter (string pvssAesPropertiesDp, dyn_dyn_anytype aesFilter, dyn_string &exceptionInfo, bool updateAes=TRUE)
fwAlarmHandlingScreen_evaluateDpFilter (dyn_dyn_anytype aesFilter, dyn_string &evaluatedFilter, dyn_string &exceptionInfo)
_fwAlarmHandlingScreen_removeAsteriskFilters (dyn_string &filter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_evaluateSeverityFilter (dyn_dyn_anytype aesFilter, string &evaluatedFilter, dyn_string &exceptionInfo, int localOrGlobal=0)
_fwAlarmHandling_convertSeverityRangeToList (string severityRange, string &severityList, dyn_string &exceptionInfo)
_fwAlarmHandlingScreen_getDefaultFilter (dyn_dyn_anytype &aesFilter, dyn_string &exceptionInfo)
_fwAlarmHandlingScreen_getDefaultMode (dyn_anytype &aesMode, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_readMode (dyn_anytype &aesMode, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_showMode (dyn_anytype &aesMode, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_applyMode (string pvssAesPropertiesDp, dyn_anytype aesMode, dyn_string &exceptionInfo, bool updateAes=TRUE)
_fwAlarmHandlingScreen_convertFilterToDollar (dyn_dyn_anytype aesFilter, string &dollarValue, dyn_string &exceptionInfo)
_fwAlarmHandlingScreen_convertDollarToFilter (string dollarValue, dyn_dyn_anytype &aesFilter, dyn_string &exceptionInfo)
_fwAlarmHandlingScreen_showHideColumn (string pvssAesPropertiesDp, string columnName, bool visible, dyn_string &exceptionInfo, bool updateAes=FALSE)
_fwAlarmHandlingScreen_showHideColumns (string pvssAesPropertiesDp, dyn_string columnName, dyn_bool visible, dyn_string &exceptionInfo, bool updateAes=FALSE)
fwAlarmHandlingScreen_getColumnWidths (dyn_string &columnsName, dyn_bool &columnsVisible, dyn_int &columnsWidth, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setColumnWidths (dyn_string columnsName, dyn_bool columnsVisible, dyn_int columnsWidth, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setDescriptionColumnBehaviour (int columnBehaviour, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setOneRowPerAlarm (bool oneRowPerAlarm, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getOneRowPerAlarm (bool &oneRowPerAlarm, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getDescriptionColumnBehaviour (int &columnBehaviour, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getRowColourBehaviour (bool &colourWholeRow, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setRowColourBehaviour (bool colourWholeRow, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setScrollLockTimeout (int scrollLockTimeout, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getScrollLockTimeout (int &scrollLockTimeout, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setReductionMode (string pvssAesPropertiesDp, int reductionMode, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getReductionMode (string pvssAesPropertiesDp, int &reductionMode, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setAccessControlOptions (dyn_string accessRights, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getAccessControlOptions (dyn_string &accessRights, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getDefaultFilterName (string &defaultFilter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getRightClickConfig (dyn_string &menuItems, dyn_string &menuFunctions, dyn_string &menuAlertTypes, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setDefaultFilterName (string defaultFilter, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getOnlineValueUpdateRate (float &updateRate, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setOnlineValueUpdateRate (float updateRate, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getIdleTimeout (int &idleTimeout, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setIdleTimeout (float idleTimeout, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setHistoricalMaxLines (int maxLines, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getHistoricalMaxLines (int &maxLines, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_saveQuickFilterOptions (string fwAesConfigDp, bool isQuickFilter, string accessRight, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_loadQuickFilterOptions (string fwAesConfigDp, bool &isQuickFilter, string &accessRight, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_getDistSystemDisplayOption (bool &displayDetails, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_setDistSystemDisplayOption (bool displayDetails, dyn_string &exceptionInfo)
fwAlarmHandlingScreen_saveColumnWidths (dyn_string columnNames, dyn_int columnWidths, dyn_string &exceptionInfo)
_fwAlarmHandlingScreen_rightClickFunction (const string propDp, const int tabType, const string tableName)
_fwAlarmHandling_showHelp (mapping rowHeaderMapping, int row, string propDp, int tabType, string tableName, dyn_string &exceptionInfo)
_fwAlarmHandling_showTrend (mapping rowHeaderMapping, int row, string propDp, int tabType, string tableName, dyn_string &exceptionInfo)
_fwAlarmHandling_showDetails (mapping rowHeaderMapping, int row, string propDp, int tabType, string tableName, dyn_string &exceptionInfo)
_fwAlarmHandling_showFsmPanel (mapping rowHeaderMapping, int row, string propDp, int tabType, string tableName, dyn_string &exceptionInfo)
Variables
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_DP_NAME = 1
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_DP_ALIAS = 2
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_DP_TYPE = 3
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_DP_LIST = 4
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_SYSTEM = 5
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_LOCAL_OR_GLOBAL = 6
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_SEVERITY = 7
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_ALERT_TEXT = 8
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_DESCRIPTION = 9
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_SUMMARIES = 10
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_ALERT_STATE = 11
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_SIZE = 10
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_TYPE = 1
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_START_TIME = 2
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_END_TIME = 3
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_MAX_LINES = 4
const unsigned fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_SIZE = 3
const unsigned fwAlarmHandlingScreen_SEVERITY_FILTER_OBJECT_WARNING = 1
const unsigned fwAlarmHandlingScreen_SEVERITY_FILTER_OBJECT_ERROR = 2
const unsigned fwAlarmHandlingScreen_SEVERITY_FILTER_OBJECT_FATAL = 3
const unsigned fwAlarmHandlingScreen_ACCESS_ACKNOWLEDGE = 1
const unsigned fwAlarmHandlingScreen_ACCESS_COMMENT = 2
const unsigned fwAlarmHandlingScreen_ACCESS_RIGHT_CLICK = 3
const unsigned fwAlarmHandlingScreen_ACCESS_FILTER = 4
const unsigned fwAlarmHandlingScreen_ACCESS_MANAGE_DISPLAY = 5
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_DP_NAME = ".filter.dpName"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_DP_ALIAS = ".filter.dpAlias"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_DP_TYPE = ".filter.dpType"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_SYSTEM = ".filter.systems"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_LOCAL_OR_GLOBAL = ".filter.severity.localOrGlobal"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_WARNING = ".filter.severity.warning"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_ERROR = ".filter.severity.error"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_FATAL = ".filter.severity.fatal"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_ALERT_TEXT = ".filter.alertText"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_DESCRIPTION = ".filter.description"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_SUMMARIES = ".filter.summaries"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_ALERT_STATE = ".filter.alertState"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_QUICK_FILTER = ".showAsQuickFilter"
const string fwAlarmHandlingScreen_CONFIG_DP_FILTER_ACCESS_RIGHT = ".quickFilterAccessRight"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_SHORTCUT = ".Alerts.Filter.Shortcut"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_PRIORITY = ".Alerts.Filter.Prio"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_DP_LIST = ".Alerts.Filter.DpList"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_ALERT_TEXT = ".Alerts.Filter.AlertText"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_COMMENT = ".Alerts.Filter.DpComment"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_LOGIC = ".Alerts.Filter.LogicalCombine"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_SUMMARIES = ".Alerts.FilterTypes.AlertSummary"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_SYSTEMS = ".Both.Systems.Selections"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_ALL_SYSTEMS = ".Both.Systems.CheckAllSystems"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_ALERT_STATE = ".Alerts.FilterState.State"
const string fwAlarmHandlingScreen_PVSS_DP_FILTER_ONE_ROW = ".Alerts.FilterState.OneRowPerAlert"
const string fwAlarmHandlingScreen_PVSS_CONFIG_DP = "_AESConfig"
const string fwAlarmHandlingScreen_PVSS_CONFIG_COLUMN_NAMES = ".tables.alertTable.columns.name"
const string fwAlarmHandlingScreen_PVSS_CONFIG_COLUMN_FUNCTIONS = ".tables.alertTable.columns.value.functionName"
const string fwAlarmHandlingScreen_PVSS_CONFIG_COLUMN_BACKCOL = ".tables.alertTable.columns.useAlertClassBackColor"
const string fwAlarmHandlingScreen_FILTER_DP_TYPE = "_FwAesConfig"
const string fwAlarmHandlingScreen_FILTER_DP_PREFIX = "_FwAesConfig_"
const string fwAlarmHandlingScreen_PVSS_PROPERTIES_DP = "fwAES_Alerts"
const string fwAlarmHandlingScreen_HISTORICAL_TIME_FORMAT = "%d/%m/%Y %H:%M:%S"
const string fwAlarmHandlingScreen_ENABLED_BUTTON = "_ButtonShadow"
const string fwAlarmHandlingScreen_DISABLED_BUTTON = "_3DFace"
const string fwAlarmHandlingScreen_COLUMN_DP_NAME = "elementName"
const string fwAlarmHandlingScreen_COLUMN_LOGICAL_NAME = "logicalName"
const string fwAlarmHandlingScreen_COLUMN_DESCRIPTION = "description"
const string fwAlarmHandlingScreen_COLUMN_SHORT_SIGN = "abbreviation"
const string fwAlarmHandlingScreen_COLUMN_PRIORITY = "priority"
const string fwAlarmHandlingScreen_COLUMN_ACKNOWLEDGE = "acknowledge"
const string fwAlarmHandlingScreen_COLUMN_COMMENT = "nofComments"
const string fwAlarmHandlingScreen_COLUMN_ONLINE_VALUE = "onlineValue"
const string fwAlarmHandlingScreen_COLUMN_ALERT_VALUE = "value"
const string fwAlarmHandlingScreen_COLUMN_TIME_STANDARD = "timeStr"
const string fwAlarmHandlingScreen_COLUMN_TIME_CAME = "cameTime"
const string fwAlarmHandlingScreen_DPE_LIST_DIVIDER = ","
const string fwAlarmHandlingScreen_PANEL_NAME = "fwAlarmHandling/fwAlarmHandlingScreen.pnl"
const int fwAlarmHandling_BEHAVIOUR_DESCRIPTION_ONLY = 0
const int fwAlarmHandling_BEHAVIOUR_DESCRIPTION_OR_DP_NAME = 1
const int fwAlarmHandling_BEHAVIOUR_DESCRIPTION_OR_ALIAS_OR_DP_NAME = 2
const int fwAlarmHandling_BEHAVIOUR_TIME_CAME_WENT = 0
const int fwAlarmHandling_BEHAVIOUR_TIME_ALWAYS_CAME = 1
const int fwAlarmHandlingScreen_COLUMN_ID_DP_NAME = 1
const int fwAlarmHandlingScreen_COLUMN_ID_LOGICAL_NAME = 2
const int fwAlarmHandlingScreen_COLUMN_ID_DESCRIPTION = 3
const int fwAlarmHandlingScreen_COLUMN_ID_ALERT_VALUE = 4
const int fwAlarmHandlingScreen_COLUMN_ID_ONLINE_VALUE = 5
const int fwAlarmHandlingScreen_COLUMN_ID_TIME_STANDARD = 6
const int fwAlarmHandlingScreen_COLUMN_ID_TIME_CAME = 7
const unsigned fwAlarmHandlingScreen_DATA_UPDATE_RATE = 2
string fwAlarmHandlingScreen_COLOUR_BUTTON_NEEDS_PRESSING = "<{0,255,0},4,_3DFace,4,{0,0,0},0,{0,0,0},0,{0,0,0},0,{0,0,0},0>"
Detailed Description
This library contains functions for the internal workings of the JCOP Alarm Screen.
Creation Date
02/02/2006
Modification History
2011/03/21 Marco
Fix for bug #78859: filters for dpNames can now accept multiple items.
2010/04/13 Marco
Fix for bug #42996: commented out the convertion from * to full list of dist system names.
2010/04/07 Marco
Fix for bug #55217: commented out the use of function _fwAlarmHandling_convertSeverityRangeToList.
2010/03/26 Marco
Added Local/Global alarm filtering (based on class priority - thanks Oliver Holme).
Added possibility to set a maximum number of historical alerts to be displayed (functions fwAlarmHandlingScreen_setHistoricalMaxLines, fwAlarmHandlingScreen_getHistoricalMaxLines).
Created function _fwAlarmHandlingScreen_showHideColumns: handles table much more efficiently.
Constraints
Usage
Internal
PVSS managers
VISION
Author:
Oliver Holme (IT-CO)
Function Documentation
_fwAlarmHandlingScreen_convertDollarToFilter (string dollarValue, dyn_dyn_anytype & aesFilter, dyn_string & exceptionInfo)
This function converts a string representation of a filter into a filter object. To decode the string back into a filter object, use _fwAlarmHandlingScreen_convertFilterToDollar().
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dollarValue The string equivalent of the filter object is passed here
aesFilter The filter object with the filter data is returned here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
_fwAlarmHandlingScreen_convertFilterToDollar (dyn_dyn_anytype aesFilter, string & dollarValue, dyn_string & exceptionInfo)
This function converts a filter configuration object into a string value that can be passed as a dollar parameter. To decode the string back into a filter ibject, use _fwAlarmHandlingScreen_convertDollarToFilter().
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
aesFilter The filter object with the filter data is passed here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
dollarValue The string value to be passed as a dollar parameter is returned here
exceptionInfo Details of any exceptions are returned here
_fwAlarmHandlingScreen_getDefaultFilter (dyn_dyn_anytype & aesFilter, dyn_string & exceptionInfo)
Gets a filter object configured with the default filter criteria (basically ALL)
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
aesFilter The filter object is returned here with the default filter criteria Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
References fwAlarmHandlingScreen_loadFilter().
Referenced by fwAlarmHandling_openScreen(), and fwAlarmHandling_openScreenWithDpeList().
_fwAlarmHandlingScreen_getDefaultMode (dyn_anytype & aesMode, dyn_string & exceptionInfo)
Gets a mode object configured with the default mode options for the alarm screen
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
aesMode The mode object is returned here with the default filter criteria Use the fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
_fwAlarmHandlingScreen_removeAsteriskFilters (dyn_string & filter, dyn_string & exceptionInfo)
Sets any "*" filters to "". The PVSS alarm screen requires "" instead of "*" to mean ALL for some filtering criteria. If any other criteria are given as well as a "*", then they are ignored as everything will already meet the "*" criteria.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
filter Input/Output - The filter to reduce and make ready for the PVSS alarm screen
exceptionInfo Details of any exceptions are returned here
Referenced by fwAlarmHandlingScreen_applyFilter().
_fwAlarmHandlingScreen_showHideColumn (string pvssAesPropertiesDp, string columnName, bool visible, dyn_string & exceptionInfo, bool updateAes = FALSE)
Changes the visibility of the named column in the Alarm Screen. The given PVSS runtime dp should be the one that corresponds to the alarm screen display you want to update. This can be obtained using "aes_getPropDpName()" and the dp should be of type "_AESProperties".
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
pvssAesPropertiesDp The PVSS runtime properties dp for the given alarm screen
columnName The name of the column to be hidden/shown
visible TRUE to show column, FALSE to hide columns
exceptionInfo Details of any exceptions are returned here
updateAes OPTIONAL PARAMETER - default value TRUE If TRUE, perform aes_doRestart after setting the new filter If FALSE, do not perform aes_doRestart
_fwAlarmHandlingScreen_showHideColumns (string pvssAesPropertiesDp, dyn_string columnName, dyn_bool visible, dyn_string & exceptionInfo, bool updateAes = FALSE)
Changes the visibility of the named columns in the Alarm Screen. The given PVSS runtime dp should be the one that corresponds to the alarm screen display you want to update. This can be obtained using "aes_getPropDpName()" and the dp should be of type "_AESProperties".
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
pvssAesPropertiesDp The PVSS runtime properties dp for the given alarm screen
columnName The array of names of the columns to be hidden/shown
visible The array of values for the columns: TRUE to show column, FALSE to hide column
exceptionInfo Details of any exceptions are returned here
updateAes OPTIONAL PARAMETER - default value TRUE If TRUE, perform aes_doRestart after setting the new filter If FALSE, do not perform aes_doRestart
fwAlarmHandlingScreen_applyFilter (string pvssAesPropertiesDp, dyn_dyn_anytype aesFilter, dyn_string & exceptionInfo, bool updateAes = TRUE)
Applies the given filter options to the given PVSS runtime properties dp. The given PVSS runtime dp should be the one that corresponds to the alarm screen display you want to update. This can be obtained using "aes_getPropDpName()" and the dp should be of type "_AESProperties".
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pvssAesPropertiesDp The PVSS runtime properties dp for the given alarm screen
aesFilter The filter object with the filter data is passed here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
updateAes OPTIONAL PARAMETER - default value TRUE If TRUE, perform aes_doRestart after setting the new filter If FALSE, do not perform aes_doRestart
References _fwAlarmHandlingScreen_removeAsteriskFilters(), fwAlarmHandlingScreen_evaluateDpFilter(), and fwAlarmHandlingScreen_evaluateSeverityFilter().
fwAlarmHandlingScreen_applyMode (string pvssAesPropertiesDp, dyn_anytype aesMode, dyn_string & exceptionInfo, bool updateAes = TRUE)
Applies the given mode options to the given PVSS runtime properties dp. The given PVSS runtime dp should be the one that corresponds to the alarm screen display you want to update. This can be obtained using "aes_getPropDpName()" and the dp should be of type "_AESProperties".
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pvssAesPropertiesDp The PVSS runtime properties dp for the given alarm screen
aesMode The mode object with the mode data is passed here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
updateAes OPTIONAL PARAMETER - default value TRUE If TRUE, perform aes_doRestart after setting the new mode If FALSE, do not perform aes_doRestart
fwAlarmHandlingScreen_evaluateDpFilter (dyn_dyn_anytype aesFilter, dyn_string & evaluatedFilter, dyn_string & exceptionInfo)
Calculates from the given filter options, the most compact filter to pass to the PVSS runtime properties dp. For simple filters, this could involve just the DP name filter - e.g. "CAEN/*". However, for more complex filters, it will usually be a list of DPs that match all the filter criteria.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
aesFilter The filter object with the filter data is passed here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
evaluatedFilter The most compact form to express the result of the filter is returned here
exceptionInfo Details of any exceptions are returned here
References fwAlarmHandling_getDpsMatchingCriteria().
Referenced by fwAlarmHandlingScreen_applyFilter().
fwAlarmHandlingScreen_evaluateSeverityFilter (dyn_dyn_anytype aesFilter, string & evaluatedFilter, dyn_string & exceptionInfo, int localOrGlobal = 0)
Calculates from the given filter options, the priority filter which needs to be passed to the PVSS runtime properties dp. This function basically converts from FW severity (W,E,F) to PVSS priorities (40-59,60-79,80-255)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
aesFilter The filter object with the filter data is passed here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
evaluatedFilter The priority filter for the PVSS alarm screen is returned here
exceptionInfo Details of any exceptions are returned here
localOrGlobal Optional parameter - default value 0 If 0, show all alerts in ranges (e.g. 40-59 for WARNING) If 1, show upper part of ranges - assumed to be global alerts (e.g. 50-59 for WARNING) If 2, show lower part of ranges - assumed to be local alerts (e.g. 40-49 for WARNING)
Referenced by fwAlarmHandlingScreen_applyFilter().
fwAlarmHandlingScreen_getColumnWidths (dyn_string & columnsName, dyn_bool & columnsVisible, dyn_int & columnsWidth, dyn_string & exceptionInfo)
Reads the column names, visibility and widths of the alarm screen table in the current panel.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
columnsName The list of names of the columns that are in the current alarm screen table.
columnsVisible The list of BOOLEANs representing the current visible state of each column. TRUE to show column, FALSE to hide columns
columnsWidth The list of the current widths of each column.
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_getDescriptionColumnBehaviour (int & columnBehaviour, dyn_string & exceptionInfo)
Gets the current behaviour of the description column. If no description exists on the alarm dpe, or the root dpe of the dp, then either an empty string or the dpe name can be shown.
Constraints
Must close and reopen the Alarm Screen to see the effect
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
columnBehaviour any of the constants fwAlarmHandling_BEHAVIOUR_...
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_getOneRowPerAlarm (bool & oneRowPerAlarm, dyn_string & exceptionInfo)
Gets one line per alarm or one line per event (i.e. one line per CAME, one line per WENT).
Constraints
Must close and reopen the Alarm Screen to see the effect
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
oneRowPerAlarm output, TRUE - one line per alarm. CAM or WENT is shown, with the last timestamp. FALSE - one line for CAME, one line for WENT.
exceptionInfo output, Details of any exceptions are returned here
Referenced by fwAlarmHandlingScreen_setOneRowPerAlarm().
fwAlarmHandlingScreen_loadFilter (string fwAesConfigDp, dyn_dyn_anytype & aesFilter, dyn_string & exceptionInfo)
Reads the filter options from the given filter configuration data point
Constraints
Only works with JCOP FW Alarm filter configuration DPs (DPT="fwAlarmHandlingScreen_FILTER_DP_TYPE")
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
fwAesConfigDp The filter configuration data point to read from
aesFilter The filter object with the filter data is returned here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
Referenced by _fwAlarmHandlingScreen_getDefaultFilter(), and fwAlarmHandling_openScreenWithSavedFilter().
fwAlarmHandlingScreen_readFilter (dyn_dyn_anytype & aesFilter, dyn_string & exceptionInfo)
Reads the filter options from the alarm screen filter graphical objects
Constraints
The function can only be called from within the JCOP FW Alarm Screen
Usage
Public
PVSS managers
VISION
Parameters:
aesFilter The filter object is returned here with the filter as defined in the graphical objects Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_readMode (dyn_anytype & aesMode, dyn_string & exceptionInfo)
Reads the mode options from the alarm screen mode graphical objects
Constraints
The function can only be called from within the JCOP FW Alarm Screen
Usage
Public
PVSS managers
VISION
Parameters:
aesMode The mode object is returned here with the mode criteria as defined in the graphical objects Use the fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_saveFilter (string fwAesConfigDp, dyn_dyn_anytype aesFilter, dyn_string & exceptionInfo)
Saves the filter options to the given filter configuration data point
Constraints
Only works with JCOP FW Alarm filter configuration DPs (DPT="fwAlarmHandlingScreen_FILTER_DP_TYPE")
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
fwAesConfigDp The filter configuration data point to write to
aesFilter The filter object with the filter data is passed here Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_setColumnWidths (dyn_string columnsName, dyn_bool columnsVisible, dyn_int columnsWidth, dyn_string & exceptionInfo)
Sets the column visibility and widths of the given columns in the alarm screen table in the current panel.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
columnsName The list of names of the columns to configure.
columnsVisible The list of BOOLEANs representing the desired visible state of each column. TRUE to show column, FALSE to hide columns
columnsWidth The list of desired widths of each column.
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_setDescriptionColumnBehaviour (int columnBehaviour, dyn_string & exceptionInfo)
Sets the behaviour of the description column. If no description exists on the alarm dpe, or the root dpe of the dp, then either an empty string or the dpe name can be shown.
Constraints
Must close and reopen the Alarm Screen to see the effect
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
columnBehaviour any of the constants fwAlarmHandling_BEHAVIOUR_...
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_setOneRowPerAlarm (bool oneRowPerAlarm, dyn_string & exceptionInfo)
Sets one line per alarm or one line per event (i.e. one line per CAME, one line per WENT).
Constraints
Must close and reopen the Alarm Screen to see the effect
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
oneRowPerAlarm input, TRUE - one line per alarm. CAM or WENT is shown, with the last timestamp. FALSE - one line for CAME, one line for WENT.
exceptionInfo output, Details of any exceptions are returned here
References fwAlarmHandlingScreen_getOneRowPerAlarm().
fwAlarmHandlingScreen_showFilter (dyn_dyn_anytype aesFilter, dyn_string & exceptionInfo)
Shows the given filter options in the alarm screen filter graphical objects
Constraints
The function can only be called from within the JCOP FW Alarm Screen
Usage
Public
PVSS managers
VISION
Parameters:
aesFilter The filter object with the filter data to display in the graphical objects Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here
fwAlarmHandlingScreen_showMode (dyn_anytype & aesMode, dyn_string & exceptionInfo)
Shows the given mode options in the alarm screen mode graphical objects
Constraints
The function can only be called from within the JCOP FW Alarm Screen
Usage
Public
PVSS managers
VISION
Parameters:
aesMode The mode object with the mode data to display in the graphical objects Use the fwAlarmHandlingScreen_CONFIG_OBJECT_MODE_XXX constants to interpret the object
exceptionInfo Details of any exceptions are returned here