fwTrending.ctl File Reference
fwTrending.ctl File Reference
Functions
string fwTrending_getColRow (dyn_string plotsList, int column, int row)
void fwTrending_setColRow (dyn_string &plotsList, int column, int row, string plotName)
fwTrending_getAllPlots (dyn_string &plotDpNames, dyn_string &exceptionInfo)
fwTrending_getPlotDpNames (dyn_string &plotDpNames, dyn_string &exceptionInfo, string pattern="*:*")
fwTrending_getAllPages (dyn_string &pageDpNames, dyn_string &exceptionInfo)
fwTrending_getPageDpNames (dyn_string &pageDpNames, dyn_string &exceptionInfo, string pattern="*:*")
fwTrending_deletePlot (string sPlotName, dyn_string &exceptionInfo)
fwTrending_deletePage (string sPageName, dyn_string &exceptionInfo)
fwTrending_createPlot (string sPlotName, dyn_string &exInfo, string model=fwTrending_YT_PLOT_MODEL)
fwTrending_createPage (string sPageName, dyn_string &exInfo, string model=fwTrending_YT_PAGE_MODEL)
void fwTrending_newPage (string _pageName, string model=fwTrending_YT_PAGE_MODEL)
void fwTrending_newPlot (string _plotName, string model=fwTrending_YT_PLOT_MODEL)
void fwTrending_copyPageData (string _from, string _to)
void fwTrending_copyPlotData (string _from, string _to)
void fwTrending_copyPage (string _from, string _to)
void fwTrending_copyPlot (string _from, string _to)
fwTrending_initControlTrendButtons (int currentTimeRange, string sRef, string sDpName, string sTrendLog, bool bCallBack=true)
fwTrending_getDaysHoursMinutesFromTimeRange (int timeRange, int &days, int &hours, int &minutes, dyn_string &exceptionInfo)
fwTrending_getTimeRangeFromDaysHoursMinutes (int &timeRange, int days, int hours, int minutes, dyn_string &exceptionInfo)
fwTrending_initControlHistogramButtons (string ref, string sDpName, dyn_string plotData, bool trendRunning, dyn_string exceptionInfo, bool bCallBack=true)
_fwTrending_initGenericTrendControls (string ref, string sDpName, string showGrid, string showLegend, dyn_string &exceptionInfo, bool bCallBack=true)
fwTrending_initControlTrendXYButtons (int currentTimeRange, string sRef, string sDpName, string sTrendLog)
_fwTrending_initTimeRange (int currentTimeRange, string ref, dyn_string &exceptionInfo)
_fwTrending_initTrendCaption (int curveNumber, dyn_string dsDpe, dyn_dyn_string ddsCurveParams, dyn_string legendObj, dyn_string valueObj, string visibilityObj, dyn_string dsUnit, dyn_string unitObj, bool visibility, dyn_string curveTimeObj, bool bEnabledVisibility)
_fwTrending_initCurve (string curveName, int curveNumber, dyn_string dsLegendObj, dyn_string dsValueObj, dyn_string dsCurveDPE, dyn_string dsCurveLegend, dyn_string dsCurveToolTip, string curveColor, dyn_string dsCurveRange, dyn_bool dbScaleVisibility, dyn_bool dbIsLogTrend, string curveVisibilityObj, dyn_string dsUnit, dyn_string dsUnitObj, bool curveVisibility, dyn_float fForLog, string trendShape, int curvesType, dyn_string dsCurveTimeObj, bool bInitCaption, dyn_string &exceptionInfo, int markerType=0, dyn_int diCurveScalePos=0, dyn_int diCurveLink=0, string sCurveStyle=fwTrending_DEFAULT_CURVE_STYLE, dyn_string dsAxiiXFormat=fwTrending_DEFAULT_AXII_X_FORMAT, string sLegendValFormat=fwTrending_DEFAULT_LEGEND_VALUE_FORMAT, string sAxiiYFormat=fwTrending_DEFAULT_AXII_Y_FORMAT, bool bAlarmLimitsVisible=FALSE)
fwTrending_clearAlarmLimits (shape trendShape, string curveName, dyn_string exceptionInfo)
fwTrending_toggleAlarmLimits (string curveName, string curveDpeName, bool curveLimitsVisibility, shape trendShape, dyn_string exceptionInfo, string sCurveStyle=fwTrending_DEFAULT_CURVE_STYLE, bool clearLimits=FALSE)
fwTrending_initTrendWithObject (string sRef, string trendName, dyn_string trendShapeStr, dyn_dyn_string plotExtendedObject, bool runTrend, bool bInitCaption, dyn_string &exceptionInfo, bool passingCurveVisible=FALSE)
fwTrending_initHistogramWithObject (string sRef, string trendName, dyn_dyn_string plotExtendedObject, bool runTrend, dyn_string &exceptionInfo)
fwTrending_controlBarOnOff (string ref, int visible)
fwTrending_toggleControlBar (string ref)
_fwTrending_connectToAlarmHandling (string ref, dyn_dyn_string plotData)
fwTrending_showStandardTrend (bool visibility, string standardStr, string logStr, dyn_dyn_string plotData="")
fwTrending_disconnectActiveTrend (dyn_string dsCurveDPE, string activeTrend)
fwTrending_ShowCurve (string ref, string trendName, int curveNumber, bool visibility)
fwTrending_getPage (string pageDp, dyn_dyn_string &pageData, dyn_string &exceptionInfo)
fwTrending_setPage (string pageDp, dyn_dyn_string pageData, dyn_string &exceptionInfo)
fwTrending_getPlot (string plotDp, dyn_dyn_string &plotData, dyn_string &exceptionInfo)
fwTrending_setPlot (string plotDp, dyn_dyn_string plotData, dyn_string &exceptionInfo)
fwTrending_getPlotExtended (string plotDp, string refName, dyn_dyn_string &plotExtendedData, dyn_string &exceptionInfo, bool returnCurveVisible=FALSE)
fwTrending_getPlotData (string ref, string sDpName, dyn_string &returnValue)
fwTrending_getPlotDataDpeData (string sPlotDpe, string &sDpe, string &sUnit, string &sDescription)
fwTrending_editPlot (string sDpName)
fwTrending_editPage (string sDpName)
fwTrending_getTitle (string sDpName, string &sTitle, dyn_string &exceptionInfo)
fwTrending_getPlotTitle (string sDpPlotName, string &sPlotTitle)
fwTrending_getPageTitle (string sDpPageName, string &sPageTitle)
fwTrending_getPlotIsTemplate (string sDpPlotName, string &bIsTemplate)
fwTrending_setPlotIsTemplate (string sDpPlotName, string bIsTemplate)
fwTrending_showPlot (int iNumberOfPlots, dyn_string dsPlotName, dyn_string &dsReference, dyn_string templateParameters)
fwTrending_getPagePlotDps (string sPageName, dyn_string &dsPlotDps)
fwTrending_simplifyPagePlotList (dyn_string dsRawPlotList, int rows, int columns, dyn_string &dsSimplePlotList, dyn_string &exceptionInfo)
_fwTrending_openProgressBar (string sHeader, string sIcon, string text1, string text2, string text3, int iSliderType)
_fwTrending_closeProgressBar ()
void fwTrending_changeTrendTimeRange (string ref, int range, string refControl, string localTimeRangeObjValue, int itemPos, string itemText)
_fwTrending_gotoNow (shape trendName, int range)
fwTrending_trendZoomX (string ref, bool bZoomIn)
fwTrending_trendZoomY (string ref, bool bZoomIn)
fwTrending_trendRun (string ref, bool bRunTrend, string refControl)
fwTrending_gridOnOff (string ref, bool bShowGrid, string refControl, dyn_string &exceptionInfo)
fwTrending_markersOnOff (string ref, int markerType, string refControl, dyn_string &exceptionInfo)
fwTrending_legendOnOff (string ref, bool bShowLegend, string refControl, dyn_string &exceptionInfo)
fwTrending_trendUnzoom (string ref)
fwTrending_trendRefresh (string ref)
fwTrending_trendTimeBack (string ref, bool bTimeBack)
fwTrending_setTimeScaleFormat (string trendName, dyn_string &exceptionInfo)
fwTrending_pageSavePlotSettings (string ref)
fwTrending_saveCurrentSettings (string ref, string sDpName, string sDpType, bool createNewDpIfRequired, bool overwriteExisting, dyn_string &exceptionInfo, bool useDpNameForTitle=FALSE)
fwTrending_pageExportTrend (dyn_string dsRef, string templateParameters)
fwTrending_exportTrend (string fileName, dyn_string dsCurveDPE, dyn_string dsLegendCurve, dyn_time dtStart, dyn_time dtEnd, string templateParameters, dyn_string &exceptionInfo, bool fillEmptyCells=FALSE)
fwTrending_eventsSort (dyn_dyn_time ddt, dyn_dyn_bool &events, dyn_time &times)
fwTrending_convertStringToDyn (string valueString, dyn_anytype &valueList, dyn_string &exceptionInfo)
fwTrending_convertDynToString (dyn_anytype valueList, string &valueString, dyn_string &exceptionInfo)
fwTrending_getAllTemplateParametersForConfiguration (dyn_dyn_string configurationData, string configurationType, dyn_string &templateParameters, dyn_string &exceptionInfo)
_fwTrending_evaluateTemplate (string givenParametersString, dyn_string &expressionList, dyn_string &exceptionInfo)
fwTrending_rebuildDpeUNICOS (dyn_string dpes, dyn_string &fileDpe)
fwTrending_convertUnicosDpeStringToPvssDpeString (string unicosDpes, string &pvssDpes, dyn_string &exceptionInfo)
fwTrending_convertPvssDpeListToUnicosDpeList (dyn_string pvssDpes, dyn_string &unicosDpes, dyn_string &exceptionInfo)
fwTrending_convertUnicosDpeListToPvssDpeList (dyn_string unicosDpes, dyn_string &pvssDpes, dyn_string &exceptionInfo)
fwTrending_checkCurveName (string dpe, bool &tempBool, dyn_string &exceptionInfo)
_fwTrending_splitParameters (string parameters, dyn_dyn_string &dsParameters)
fwTrending_checkAndGetAllTemplateParameters (string uniqueIdentifier, dyn_dyn_string configurationData, string configurationType, string &currentParameters, dyn_string &exceptionInfo, bool relativePosition=FALSE, bool returnDefaultIfCancel=FALSE)
fwTrending_modifyAllTemplateParameters (string uniqueIdentifier, dyn_dyn_string configurationData, string configurationType, string &currentParameters, dyn_string &exceptionInfo, bool relativePosition=FALSE)
fwTrending_checkAllTemplateParameters (dyn_string &requiredParameters, string givenParameterString, bool &gotValuesForAll, dyn_string &exceptionInfo)
fwTrending_mergeParameterLists (string firstList, string secondList, string &returnedList, dyn_string &exceptionInfo)
_fwTrending_findTemplateParameters (dyn_dyn_string data, dyn_string &parametersFound, dyn_string &exceptionInfo)
fwTrending_setRuntimePlotDataWithExtendedObject (string refName, string isRunning, dyn_dyn_string plotExtendedObject, dyn_string &exceptionInfo, bool runningInsideTrend=TRUE)
fwTrending_setRuntimePlotDataWithStrings (string refName, string isRunning, dyn_string plotData, dyn_string &exceptionInfo, bool runningInsideTrend=TRUE)
fwTrending_setRuntimePageDataWithObject (dyn_dyn_string pageObject, dyn_string &exceptionInfo)
fwTrending_getRuntimePageDataWithObject (dyn_dyn_string &pageObject, dyn_string &exceptionInfo)
fwTrending_setRuntimePageDataWithStrings (dyn_string pageData, dyn_string &exceptionInfo)
fwTrending_getRuntimePageDataWithStrings (dyn_string &pageData, dyn_string &exceptionInfo)
fwTrending_getRuntimePlotDataWithStrings (string refName, string &isRunning, dyn_string &plotShapes, dyn_string &plotData, dyn_string &exceptionInfo, bool runningInsideTrend=TRUE)
fwTrending_getRuntimePlotDataWithExtendedObject (string refName, string &isRunning, dyn_string &plotShapes, dyn_dyn_string &plotExtendedObject, dyn_string &exceptionInfo, bool runningInsideTrend=TRUE)
_fwTrending_syncDifferentRangeFormats (string &minRange, string &maxRange, string &combinedRange, dyn_string &exceptionInfo)
_fwTrending_switchCurvesHiddenVisible (dyn_string &currentCurveStatus, dyn_string &exceptionInfo)
fwTrending_getNumberOfCurves (string plotDp, int &numberOfCurves, dyn_string &exceptionInfo)
fwTrending_getFirstFreeCurve (string plotDp, int &position, dyn_string &exceptionInfo)
fwTrending_getFreeCurves (string plotDp, dyn_int &positions, dyn_string &exceptionInfo)
fwTrending_setCurve (string plotDp, dyn_string curveData, int curveToSet, dyn_string &exceptionInfo)
fwTrending_setManyCurves (string plotDp, dyn_dyn_string curvesData, dyn_int curvesToSet, dyn_string &exceptionInfo)
fwTrending_getCurve (string plotDp, bool &isCurveDefined, dyn_string &curveData, int curveToGet, dyn_string &exceptionInfo)
fwTrending_appendCurve (string plotDp, dyn_string curveData, dyn_string &exceptionInfo)
fwTrending_appendManyCurves (string plotDp, dyn_dyn_string curvesData, dyn_string &exceptionInfo)
fwTrending_insertCurveAt (string plotDp, dyn_string curveData, int position, dyn_string &exceptionInfo, bool forceInsert=FALSE)
fwTrending_deleteCurve (string plotDp, int curveToDelete, dyn_string &exceptionInfo)
fwTrending_deleteManyCurves (string plotDp, dyn_int curvesToDelete, dyn_string &exceptionInfo)
fwTrending_removeCurve (string plotDp, int curveToRemove, dyn_string &exceptionInfo)
_fwTrending_checkCurveData (dyn_string &curveData, int position, dyn_string &exceptionInfo)
int _fwTrending_getCurveObjectIndexes (dyn_int &curveObjectIndexes, dyn_int &plotObjectIndexes, dyn_string &exceptionInfo)
fwTrending_openPlotDisplay (string sPlotDpName, string sPanelFileName, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, unsigned x=0, unsigned y=0, string sResizeMode="")
_fwTrending_isSystemForDpeConnected (string curveDpe, bool &isConnected, dyn_string &exceptionInfo)
_fwTrending_isSystemConnected (string systemName, bool &isConnected, dyn_string &exceptionInfo)
_fwTrending_getConnectedSystemIds (dyn_int &systemIds, dyn_string &exceptionInfo)
_fwTrending_updateHistogram (string dpa, dyn_float value)
_fwTrending_convertPlotDataToDollars (dyn_dyn_string plotData, dyn_string &dollarParameters, dyn_string &exceptionInfo)
_fwTrending_preparePlotObjectForDisplay (dyn_dyn_string &plotData, string parameterString, dyn_string &exceptionInfo)
fwTrending_addQuickFaceplate (string moduleName, string panelName, string refName, dyn_string dpesToPlot, int x, int y, dyn_string &exceptionInfo, string plotDpName="_FwTrendingQuickPlotDefaults", float xScale=1.0, float yScale=1.0)
fwTrending_addFaceplate (string moduleName, string panelName, string refName, string plotDpName, dyn_string templateParameterNames, dyn_string templateParameterValues, int x, int y, dyn_string &exceptionInfo, float xScale=1.0, float yScale=1.0)
fwTrending_removeFaceplate (string moduleName, string panelName, string refName, dyn_string &exceptionInfo)
bool _fwTrending_isUnicosEnvironment (dyn_string &exceptionInfo)
_fwTrending_convertFrameworkToPvssMarkerType (int frameworkType, int &pvssType, dyn_string &exceptionInfo)
Variables
const string fwTrending_ON_VAL = ":_online.._value"
const string fwTrending_OFF_VAL = ":_offline.._value"
const string fwTrending_ORIG_VAL = ":_original.._value"
const string fwTrending_YT_PAGE_MODEL = "Value over time"
const string fwTrending_XY_PAGE_MODEL = "Value over value"
const string fwTrending_YT_PLOT_MODEL = "Value over time"
const string fwTrending_XY_PLOT_MODEL = "Value over value"
const string fwTrending_HISTOGRAM_PLOT_MODEL = "Histogram"
const string fwTrending_PAGE = "FwTrendingPage"
const string fwTrending_PAGE_MODEL = ".model"
const string fwTrending_PAGE_TITLE = ".pageTitle"
const string fwTrending_PAGE_NCOLS = ".nColumns"
const string fwTrending_PAGE_NROWS = ".nRows"
const string fwTrending_PAGE_PLOTS = ".plots"
const string fwTrending_PAGE_CONTROLS = ".controls"
const string fwTrending_PAGE_PLOT_TEMPLATE_PARAMETERS = ".plotTemplateParams"
const string fwTrending_PAGE_ACCESS_CONTROL_SAVE = ".accessControl.save"
const int fwTrending_PAGE_OBJECT_MODEL = 1
const int fwTrending_PAGE_OBJECT_TITLE = 2
const int fwTrending_PAGE_OBJECT_NCOLS = 3
const int fwTrending_PAGE_OBJECT_NROWS = 4
const int fwTrending_PAGE_OBJECT_PLOTS = 5
const int fwTrending_PAGE_OBJECT_CONTROLS = 6
const int fwTrending_PAGE_OBJECT_PLOT_TEMPLATE_PARAMETERS = 7
const int fwTrending_PAGE_OBJECT_ACCESS_CONTROL_SAVE = 8
const string fwTrending_PLOT = "FwTrendingPlot"
const string fwTrending_PLOT_MODEL = ".model"
const string fwTrending_PLOT_TITLE = ".plotTitle"
const string fwTrending_PLOT_LEGEND_ON = ".legend"
const string fwTrending_PLOT_BACK_COLOR = ".plotBackColor"
const string fwTrending_PLOT_FORE_COLOR = ".plotForeColor"
const string fwTrending_PLOT_DPES = ".dpes"
const string fwTrending_PLOT_DPES_X = ".xDpes"
const string fwTrending_PLOT_LEGENDS = ".legendTexts"
const string fwTrending_PLOT_LEGENDS_X = ".xLegendTexts"
const string fwTrending_PLOT_COLORS = ".colors"
const string fwTrending_PLOT_AXII = ".axii"
const string fwTrending_PLOT_AXII_X = ".xAxii"
const string fwTrending_PLOT_IS_TEMPLATE = ".isTemplate"
const string fwTrending_PLOT_CURVES_HIDDEN = ".curvesHidden"
const string fwTrending_PLOT_RANGES_MIN = ".yRangeMin"
const string fwTrending_PLOT_RANGES_MAX = ".yRangeMax"
const string fwTrending_PLOT_RANGES_MIN_X = ".xRangeMin"
const string fwTrending_PLOT_RANGES_MAX_X = ".xRangeMax"
const string fwTrending_PLOT_TYPE = ".plotType"
const string fwTrending_PLOT_TIME_RANGE = ".timeRange"
const string fwTrending_PLOT_TEMPLATE_NAME = ".templateName"
const string fwTrending_PLOT_IS_LOGARITHMIC = ".isLogarithmic"
const string fwTrending_PLOT_GRID = ".grid"
const string fwTrending_PLOT_CURVE_TYPES = ".curveTypes"
const string fwTrending_PLOT_MARKER_TYPE = ".markerType"
const string fwTrending_PLOT_ACCESS_CONTROL_SAVE = ".accessControl.save"
const string fwTrending_PLOT_CONTROL_BAR_ON = ".controlBar"
const string fwTrending_PLOT_AXII_POS = ".axiiPos"
const string fwTrending_PLOT_AXII_LINK = ".axiiLink"
const string fwTrending_PLOT_DEFAULT_FONT = ".defaultFont"
const string fwTrending_PLOT_CURVE_STYLE = ".curveStyle"
const string fwTrending_PLOT_AXII_X_FORMAT = ".xAxiiFormat"
const string fwTrending_PLOT_AXII_Y_FORMAT = ".yAxiiFormat"
const string fwTrending_PLOT_LEGEND_VALUES_FORMAT = ".legendValuesFormat"
const string fwTrending_PLOT_ALARM_LIMITS_SHOW = ".alarmLimitsVisible"
const string fwTrending_CURVE_TYPES = ".curveTypes"
const int fwTrending_PLOT_OBJECT_MODEL = 1
const int fwTrending_PLOT_OBJECT_TITLE = 2
const int fwTrending_PLOT_OBJECT_LEGEND_ON = 3
const int fwTrending_PLOT_OBJECT_BACK_COLOR = 4
const int fwTrending_PLOT_OBJECT_FORE_COLOR = 5
const int fwTrending_PLOT_OBJECT_DPES_X = 6
const int fwTrending_PLOT_OBJECT_DPES = 7
const int fwTrending_PLOT_OBJECT_LEGENDS_X = 8
const int fwTrending_PLOT_OBJECT_LEGENDS = 9
const int fwTrending_PLOT_OBJECT_COLORS = 10
const int fwTrending_PLOT_OBJECT_AXII_X = 11
const int fwTrending_PLOT_OBJECT_AXII = 12
const int fwTrending_PLOT_OBJECT_IS_TEMPLATE = 13
const int fwTrending_PLOT_OBJECT_CURVES_HIDDEN = 14
const int fwTrending_PLOT_OBJECT_RANGES_MIN_X = 15
const int fwTrending_PLOT_OBJECT_RANGES_MAX_X = 16
const int fwTrending_PLOT_OBJECT_RANGES_MIN = 17
const int fwTrending_PLOT_OBJECT_RANGES_MAX = 18
const int fwTrending_PLOT_OBJECT_TYPE = 19
const int fwTrending_PLOT_OBJECT_TIME_RANGE = 20
const int fwTrending_PLOT_OBJECT_TEMPLATE_NAME = 21
const int fwTrending_PLOT_OBJECT_IS_LOGARITHMIC = 22
const int fwTrending_PLOT_OBJECT_GRID = 23
const int fwTrending_PLOT_OBJECT_CURVE_TYPES = 24
const int fwTrending_PLOT_OBJECT_MARKER_TYPE = 25
const int fwTrending_PLOT_OBJECT_ACCESS_CONTROL_SAVE = 26
const int fwTrending_PLOT_OBJECT_CONTROL_BAR_ON = 27
const int fwTrending_PLOT_OBJECT_AXII_POS = 28
const int fwTrending_PLOT_OBJECT_AXII_LINK = 29
const int fwTrending_PLOT_OBJECT_DEFAULT_FONT = 30
const int fwTrending_PLOT_OBJECT_CURVE_STYLE = 31
const int fwTrending_PLOT_OBJECT_AXII_X_FORMAT = 32
const int fwTrending_PLOT_OBJECT_AXII_Y_FORMAT = 33
const int fwTrending_PLOT_OBJECT_LEGEND_VALUES_FORMAT = 34
const int fwTrending_PLOT_OBJECT_LEGEND_DATE_FORMAT = 35
const int fwTrending_PLOT_OBJECT_LEGEND_DATE_ON = 36
const int fwTrending_PLOT_OBJECT_ALARM_LIMITS_SHOW = 37
const int fwTrending_PLOT_OBJECT_EXT_MIN_FOR_LOG = 38
const int fwTrending_PLOT_OBJECT_EXT_MAX_PERCENTAGE_FOR_LOG = 39
const int fwTrending_PLOT_OBJECT_EXT_UNITS_X = 40
const int fwTrending_PLOT_OBJECT_EXT_UNITS = 41
const int fwTrending_PLOT_OBJECT_EXT_TOOLTIPS_X = 42
const int fwTrending_PLOT_OBJECT_EXT_TOOLTIPS = 43
const int fwTrending_PLOT_OBJECT_EXT_MIN_MAX_RANGE_X = 44
const int fwTrending_PLOT_OBJECT_EXT_MIN_MAX_RANGE = 45
const int fwTrending_CURVE_OBJECT_DPE = 1
const int fwTrending_CURVE_OBJECT_TYPE = 2
const int fwTrending_CURVE_OBJECT_COLOR = 3
const int fwTrending_CURVE_OBJECT_LEGEND = 4
const int fwTrending_CURVE_OBJECT_AXIS = 5
const int fwTrending_CURVE_OBJECT_HIDDEN = 6
const int fwTrending_CURVE_OBJECT_Y_MIN = 7
const int fwTrending_CURVE_OBJECT_Y_MAX = 8
const int fwTrending_LINEAR_TREND_NAME = 1
const int fwTrending_LOG_TREND_NAME = 2
const int fwTrending_ACTIVE_TREND_NAME = 3
const int fwTrending_PLOT_TYPE_POINTS = 0
const int fwTrending_PLOT_TYPE_STEPS = 1
const int fwTrending_PLOT_TYPE_LINEAR = 2
const int fwTrending_PLOT_TYPE_INDIVIDUAL = 99
const int fwTrending_PLOT_TYPE_STANDARD = 1
const int fwTrending_DOMAIN = 1
const int fwTrending_PRIVILEDGE_PLOT_CHANGE = 2
const int fwTrending_PRIVILEDGE_PAGE_CHANGE = 2
const int fwTrending_PRIVILEDGE_ARCHIVE_CHANGE = 3
const int fwTrending_MAX_NUM_CURVES = 8
const int fwTrending_Y_VALUE = 1
const int fwTrending_X_VALUE = 2
const float fwTrending_MIN_FOR_LOG = 1e-1
const float fwTrending_MAX_PERCENTAGE_FOR_LOG = 5
const int fwTrending_TRENDING_MAX_CURVE = 8
const int fwTrending_ZOOMED_WINDOW_MAX_LEGEND_SIZE = 7
const int fwTrending_SIZE_PLOT_OBJECT = 45
const int fwTrending_SIZE_PAGE_OBJECT = 8
const int fwTrending_SIZE_CURVE_OBJECT = 8
const int fwTrending_getPlotData_LEN_RETURN_DATA = 45
const int fwTrending_TREND_CONTROL_Y_OFFSET = 20
const int fwTrending_ONE_ROW = 0
const int fwTrending_ONE_COLUMN = 0
const int fwTrending_TWO_ROW_1 = 0
const int fwTrending_TWO_ROW_2 = 417
const int fwTrending_TWO_COLUMN_1 = 0
const int fwTrending_TWO_COLUMN_2 = 635
const int fwTrending_THREE_ROW_1 = 0
const int fwTrending_THREE_ROW_2 = 280
const int fwTrending_THREE_ROW_3 = 560
const string fwTrending_AXIS_LIMITS_DIVIDER = ":"
const string fwTrending_CONTENT_DIVIDER = ";"
const string fwTrending_NOTHING_IN_TREND = ";;;;;;;;"
const int fwTrending_MAX_ROWS = 6
const int fwTrending_MAX_COLS = 6
const float fwTrending_TIME_BACK_RESOLUTION = 0.8
const float fwTrending_TIME_FORWARD_RESOLUTION = 0.8
const string fwTrending_DEFAULT_FONT = "MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0"
const string fwTrending_DEFAULT_CURVE_STYLE = "[solid,oneColor,JoinMiter,CapButt,0]"
const string fwTrending_DEFAULT_AXII_X_FORMAT = "%c"
const string fwTrending_DEFAULT_AXII_Y_FORMAT = ""
const string fwTrending_DEFAULT_LEGEND_VALUE_FORMAT = ""
const string fwTrending_TEMPLATE_OPEN = "{"
const string fwTrending_TEMPLATE_CLOSE = "}"
const string fwTrending_TEMPLATE_DIVIDER = ","
const int fwTrending_SECONDS_IN_ONE_MINUTE = 60
const int fwTrending_SECONDS_IN_ONE_HOUR = 3600
const int fwTrending_SECONDS_IN_ONE_DAY = 86400
const string fwTrending_PANEL_PLOT_ZOOMED = "fwTrending/fwTrendingZoomedWindow.pnl"
const string fwTrending_PANEL_PLOT_STANDARD = "fwTrending/fwTrendingPlot.pnl"
const string fwTrending_PANEL_PLOT_FACEPLATE = "objects/fwTrending/fwTrendingFaceplate.pnl"
const string fwTrending_PANEL_PLOT_FACEPLATE_FULLCAPTION = "objects/fwTrending/fwTrendingFaceplateFullCaption.pnl"
const string fwTrending_EXPORT_DATA_PATH = "data/export_CSV/"
const int fwTrending_MARKER_TYPE_FILLED_CIRCLE = 0
const int fwTrending_MARKER_TYPE_UNFILLED_CIRCLE = 1
const int fwTrending_MARKER_TYPE_NONE = 2
const string fwTrending_QUICKPLOT_DEFAULTS = "_FwTrendingQuickPlotDefaults"
const string fwTrending_PLOT_DEFAULTS = "_FwTrendingPlotDefaults"
const string fwTrending_PAGE_DEFAULTS = "_FwTrendingPageDefaults"
const int fwTrending_HIDE_CONTROL_BAR = 1
const int fwTrending_HIDE_CAPTIONS = 2
const int fwTrending_HIDE_NONE = 0
Detailed Description
This library contains utility functions for the Trending Tool.
Creation Date
19/12/2002
Modification History
12/11/2010: Marco
fix for bug #75191: Customizable default plot setting. Modified fwTrending_newPlot(): it checks now if a default settings dpe (fwTrending_PLOT_DEFAULTS) exists. If yes, apply those settings to new plots. If not, apply coded settings.
11/11/2010: Marco
fix for bug #71141: Uncaught exception during install of trending tool. The SCALE_LEFT constant is probably imported from some library only by the UI manager. This is probably why the CTRL manager does not know it.
27/10/2010: Marco
IS-294 (back-compatibility with un functions). Modified functions fwTrending_setPlot(), fwTrending_setPage(). It writes the new settings only after checking they are passed as parameters.
27/10/2010: Marco
fix for bug #74445 (Hide/show legend also on trend pages). Modified function fwTrending_controlBarOnOff() It now handles the references to the different trend plots in the trend pages.
05/10/2010: Marco
fix for bug #73928 (Y scale format error when applying settings). Modified function fwTrending_showStandardTrend()
fix for bug #73592 (Y axis: custom format not correctly set).
20/08/2010: Marco
fix for ENS-1707 (zoom in/out was not possible using the CTRL-# key shortcuts). The hidden buttons for zooming in/out were disabled by _fwTrending_initGenericTrendControls(). Disabling is now removed. Furthermore, the buttons were using native trend widget methods. They now use the functions fwTrending_trendZoomX(), fwTrending_trendZoomY().
20/08/2010: Marco
fix for ENS-1520 (X axis scale information disappear): for some reason PVSS does not handle well the default value format (empty-string format): it is correctly shown only if inside a range that does not trigger the format overriding (PVSS overrides the scale format for some time ranges, i.e. very deep zoom in, or extensive zoom-out). I've added a default value ("%c") to be used if the received value is empty string.
04/08/2010: Marco
fix for bug ENS-1045 (log scale): when activating the Log scale, now the function fwTrending_showStandardTrend() accepts optional parameter plotData. With this it can access the scale formats and toggle automatically engineering format (if Log) or default/custom format (if linear).
30/07/2010: Marco
fix for bug #68678 (Plot alarm limits): the limits of the alarm of the plotted value can be plotted on the trend. This info is on fwTrending_PLOT_OBJECT_ALARM_LIMITS_SHOW. On the panels, this parameter is appended to the param $dsCurveVisible. Positions: 1-8: the curve visibility 9-16: the curve alarms visibility
30/06/2010: Marco
fix for bug #68333: exporting curves to CSV now has option to exclude hidden curves.
fix for bug #69566: for each curve, the value format on the scale can be customized. This info is on fwTrending_PLOT_OBJECT_LEGEND_AXII_Y_FORMAT. On the panels, this parameter is appended to the param $dsCurveScaleVisible. Positions: 1-8: the scale visibility 9-16: the scale position 17-24: the scale link 25-32: the scale format
fix for bug #69424: for each curve, value format on the legend can be customized. This info is on fwTrending_PLOT_OBJECT_LEGEND_VALUE_FORMAT. On the panels, this parameter is appended to the param $sLegends. Positions: 1-8: the legends texts 9-16: the legend values format
fix for bug #68074: date format for the X axis can be customized. This info is on fwTrending_PLOT_OBJECT_AXII_X_FORMAT. On the panels, this parameter is appended to the param $sTimeRange. Positions: 1 timeRange 2 format for time on x axis - first line 3 format for time on x axis - second line
26/05/2010: Marco
fix for bug #55166: curves line can be modified in width and style. This info is on fwTrending_PLOT_OBJECT_CURVE_STYLE. On the panels, this parameter is appended to the param $iMarkerType.
fix for bug #67907: fonts can be modified. This info is on fwTrending_PLOT_OBJECT_DEFAULT_FONT. On the panels, this parameter is appended to the param $sForeColor.
fix for bug #55167, #66698: curves can be linked to each other. Each curve has a new property: id number (1-8) of the curve to be linked to. This info is on fwTrending_PLOT_OBJECT_AXII_LINK. On the panels, this parameter is appended to the param $dsCurveScaleVisible after the scale position.
29/04/2010: Marco
fix for bug #66064, #66488: a new function fwTrending_controlBarOnOff() toggles the control menu bar and the captions bar. If the bar is hidden, the trending area is expanded. The captions can be hidden, the trending area is expanded.
fix for bug #35454: scale position: the trending can now show the scale of a curve at the left or at the right. Such information is stored into the index fwTrending_PLOT_OBJECT_AXII_POS. It is passed to the trending panels through the already existing parameter $dsCurveScaleVisible (the 8 values are appended to the parameter).
removed fix for bug #65392: the function _fwTrending_gotoNow() does just .gotoNow().
06/04/2010: Marco
fix for bug #65392: a new function _fwTrending_gotoNow() shows the last value using a different procedure depending on the PVSS version. Replaced all the .gotoNow() with _fwTrending_gotoNow().
25/03/2010: Marco
fix for bug #40368: added a check for empty values of datapoints to _fwTrending_updateHistogram(). Now, if there is no value in the dpe to plot, the histogram is cleaned.
fix for bug #55165: skip evaluation of parameters when calling _fwTrending_evaluateTemplate() passing the string "parameterValues" as given parameter.
fix for bug #64959: _fwTrending_updateHistogram() could not load dpe from template "{}". Fixed.
02/07/2008: Herve (ref. in the code start/end 02/07/2008: Herve)
bug in fwTrending_ShowCurve commented out the lines yAxisControl = getShape(ref + "YAxiiCascadeButton"); and yAxisControl.enableItem(curveNumber-1, visibility);
to keep consistency: in fwTrending_initControlTrendButtons the YAxiiCascadeButton cascade item is not disabled if the curve is not visible.
20/05/2008: Herve (ref. in the code start/end 20/05/2008: Herve)
in fwTrending_initTrendWithObject, fwTrending_legendOnOff: comment out all manageLegend call
in _fwTrending_initCurve: add curveLegendShowDate, curveLegendShowDate curveLegendShowMilli curveLegendFormat, curveLegendUnit bug exp --> convert to n.10f (n=nb of digit from the format of the DPE, ex: 2.3e converted to 2.10f markerType = 0 (POINT_NONE) by default reset exceptionInfo in case of UNICOS installation move curveScaleVisibility after connectDirectly
fwTrending_initTrendWithObject, fwTrending_showStandardTrend, fwTrending_changeTrendTimeRange, fwTrending_trendZoomX, fwTrending_trendZoomY, fwTrending_gridOnOff, fwTrending_legendOnOff, fwTrending_trendUnzoom, fwTrending_trendRefresh fwTrending_setRuntimePlotDataWithStrings, fwTrending_getRuntimePlotDataWithStrings: comment out any reference to logTrendShape
10/06/2003: Herve added several functions 12/06/2003: Herve in the fwTrending_getPlotData function . add a check of dynlen(dsAxii) >= i before adding dsAxii[i]+";" othervise add to returnValue[12] to "FALSE;" because the axii may be empty if the axii visibility was never modified. . add a check of dynlen(dsLeg) >= i before adding dsLeg[i]+";" othervise add to returnValue[5] to ";" because the legend may be empty if the it was never modified. If the legend is empty the set it to dpe. in the function fwTrending_getPlotTitle . if the title is "", set t=it to sPlotName add the function fwTrending_showPlot: to show one or many plots and also the constant for plots position 17/06/2003: Herve added several functions modify the signature of fwTrending_showPlot: add dsReference as output param. 10/07/2003: Sascha - new functions and some modifications to some 14/07/2003: Sascha - some more modifications 17/07/2003: Sascha modify the functions fwTrending_getAllPlots and fwTrending_getAllPages to work in a distributed environment 10/09/2003: Herve add two internal function _fwTrending_openProgressBar and _fwTrending_closeProgressBar add in fwTrending_exportTrend the _fwTrending_openProgressBar and _fwTrending_closeProgressBar function call 20/01/2004: Sascha some modifications and deleted two functions deleted the function fwTrending_savePlotTitle: save the title of a plot deleted the function fwTrending_savePageTitle: save the title of a page
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author:
Oliver Holme, Sascha Schmeling, Herve Milcent, Piotr Starzyk (IT-CO)
Function Documentation
_fwTrending_checkCurveData (dyn_string & curveData, int position, dyn_string & exceptionInfo)
Checks curve object and fills in any missing values with default data.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
curveData input/output, the curve object to check
position input, the intended position of the curve (used for making default data e.g. curve colour)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_insertCurveAt(), and fwTrending_setManyCurves().
_fwTrending_closeProgressBar ()
Close the progress bar opend as a child panel. This function is the same as the closeProgressBar from std.ctl. The difference between this function and the closeProgressBar function is the dpSet of "_VarTrendOpen.PanelName:_original.._value" where "ProgressBar" is replaced byt myModuleName()
Constraints
None
Usage
Internal
PVSS managers
VISION
Referenced by fwTrending_pageExportTrend().
_fwTrending_connectToAlarmHandling (string ref, dyn_dyn_string plotData)
Sets the text box txtCurvesDpes with the list of dpes which are plotted together with alarms This is used to change online the value of the plotted limits in case the alarm handling setting is changed by the user.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
plotData input, details of the plot (see fwTrending_PLOT_OBJECT.... constants for info on what needs to be passed as well as fwTrending_PLOT_OBJECT_EXT.... constants)
References fwTrending_convertStringToDyn().
_fwTrending_convertPlotDataToDollars (dyn_dyn_string plotData, dyn_string & dollarParameters, dyn_string & exceptionInfo)
Convert a plotData object to a list of $params ready to pass to a trend display.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
plotData The plot data object (dyn_dyn_string)
dollarParameters The list of $ parameters to be passed to a trend display based on the data in plotData
exceptionInfo output, details of any exceptions are returned here
References fwTrending_convertDynToString().
Referenced by fwTrending_addFaceplate().
_fwTrending_evaluateTemplate (string givenParametersString, dyn_string & expressionList, dyn_string & exceptionInfo)
Substitute the values of template parameters into a given list of string.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
givenParametersString input, the string which contains the definitions of the template parameters
expressionList input/output, the list of values that might need substitutions is passed and the version with the necessary substitutions is returned.
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_findTemplateParameters(), and _fwTrending_splitParameters().
Referenced by _fwTrending_preparePlotObjectForDisplay(), _fwTrending_updateHistogram(), fwTrending_exportTrend(), fwTrending_getPlotDataDpeData(), fwTrending_initControlTrendButtons(), and fwTrending_pageExportTrend().
_fwTrending_findTemplateParameters (dyn_dyn_string data, dyn_string & parametersFound, dyn_string & exceptionInfo)
Find the template parameters required for a given plot or page configuration.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
data input, the configuration data to find the parameters in
parametersFound output, a list of all the template parameters which were found
exceptionInfo output, details of any exceptions are returned here
Referenced by _fwTrending_evaluateTemplate(), and fwTrending_getAllTemplateParametersForConfiguration().
_fwTrending_getConnectedSystemIds (dyn_int & systemIds, dyn_string & exceptionInfo)
Get a list of the IDs of all connected systems (including local system)
Constraints
None
Usage
DEPCRECATED - Use unDistributedControl DPs and functions instead
PVSS managers
VISION, CTRL
Parameters:
systemIds output, list of IDs of all connected systems
exceptionInfo output, details of any exceptions are returned here
int _fwTrending_getCurveObjectIndexes (dyn_int & curveObjectIndexes, dyn_int & plotObjectIndexes, dyn_string & exceptionInfo)
This function returns two lists of integers representing certain indexes of the curveData object and the plotData object. All the curveData object indexes are returned, and the corresponding indexes of the plotData object where the curveData should be stored are also returned.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
curveObjectIndexes The indexes of the curveData object are returned here
plotObjectIndexes The corresponding indexes of the plotData object are returned here
exceptionInfo output, details of any exceptions are returned here
Returns:
The length of the curveData object is returned here
Referenced by fwTrending_deleteManyCurves(), fwTrending_getCurve(), fwTrending_insertCurveAt(), fwTrending_removeCurve(), and fwTrending_setManyCurves().
_fwTrending_gotoNow (shape trendName, int range)
go to the current value of the trend. Use different functions depending on the PVSS version.
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Internal
PVSS managers
VISION
Parameters:
trendName input, reference of the trend
range input, the time range in seconds
Referenced by fwTrending_changeTrendTimeRange(), and fwTrending_initTrendWithObject().
_fwTrending_initCurve (string curveName, int curveNumber, dyn_string dsLegendObj, dyn_string dsValueObj, dyn_string dsCurveDPE, dyn_string dsCurveLegend, dyn_string dsCurveToolTip, string curveColor, dyn_string dsCurveRange, dyn_bool dbScaleVisibility, dyn_bool dbIsLogTrend, string curveVisibilityObj, dyn_string dsUnit, dyn_string dsUnitObj, bool curveVisibility, dyn_float fForLog, string trendShape, int curvesType, dyn_string dsCurveTimeObj, bool bInitCaption, dyn_string & exceptionInfo, int markerType = 0, dyn_int diCurveScalePos = 0, dyn_int diCurveLink = 0, string sCurveStyle = fwTrending_DEFAULT_CURVE_STYLE, dyn_string dsAxiiXFormat = fwTrending_DEFAULT_AXII_X_FORMAT, string sLegendValFormat = fwTrending_DEFAULT_LEGEND_VALUE_FORMAT, string sAxiiYFormat = fwTrending_DEFAULT_AXII_Y_FORMAT, bool bAlarmLimitsVisible = FALSE)
Purpose: initialize the curve of the active trend, the other trend will have no data.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
curveName input, name of the curve
curveNumber input, curve number
dsLegendObj input names of legend graphical objects
dsValueObj input, names of the valueCurve graphical objects
dsCurveDPE input, DPEs connected to the curves
dsCurveLegend input, legend of the DPEs
dsCurveToolTip input, tool tip text of the DPEs
curveColor input, color of the curve
dsCurveRange input, min:max of the curves, format min:max
dbScaleVisibility input, visibility state of the scale of the curves
dbIsLogTrend input, true if log trends
curveVisibilityObj input, name of the visibility check box graphical object
dsUnit input, units of the DPEs
dsUnitObj input, names of the unit graphical objects
curveVisibility input, visibility state of the scale of the curve
fForLog input, [1]minimum for log scale, [2] max percentage for log
trendShape input, name of the active trend graphical object
curvesType input, type of the curve
dsCurveTimeObj input, names of the curveTime graphical objects
bInitCaption input, true to initialize the caption
exceptionInfo output, the exception is returned here
markerType input, optional, type of marker (default value = 7 - filled circle);
diCurveScalePos input, optional, SCALE_LEFT if the scale must be on the left, SCALE_RIGHT if must be on the right
diCurveLink input, optional, list of indexes of the curves to be linked to, i.e.: if curve 1 must be linked to curve 4, and curve 3 to 4, then it should be 4,0,4,0,0,0,0,0
sCurveStyle input, optional, line style for the curves (default value = fwTrending_DEFAULT_CURVE_STYLE).
dsAxiiXFormat input, optional, time format for the X axis.
sLegendValFormat input, optional, numeric format of the value shown on the legend. Updated only after value changed.
sAxiiYFormat input, optional, numeric format of the scale o the Y axis.
bAlarmLimitsVisible input, optional, TRUE = show the analog alarm limits values of the plotted item (default value = FALSE).
References _fwTrending_initTrendCaption(), _fwTrending_isSystemForDpeConnected(), and fwTrending_toggleAlarmLimits().
Referenced by fwTrending_initTrendWithObject().
_fwTrending_initGenericTrendControls (string ref, string sDpName, string showGrid, string showLegend, dyn_string & exceptionInfo, bool bCallBack = true)
Purpose: Do some setup of the trend display. This function works for both Value over time and Value over value plots.
Constraints
This function is only for use with the standard trend panels as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
ref input, the reference given to with the addSymbol ("" if used directly as a plot or the symbol name in a page)
sDpName input, the plot DP or "" if using the $params to pass configure the plot
showGrid input, TRUE if grid is visible, else FALSE.
showLegend input, TRUE if legend is visible, else FALSE.
exceptionInfo output, any exceptions are returned here
Referenced by fwTrending_initControlTrendButtons(), and fwTrending_initControlTrendXYButtons().
_fwTrending_initTimeRange (int currentTimeRange, string ref, dyn_string & exceptionInfo)
This functions sets the time range cascade button, the time range element (to the right of the trend controls) as well a hidden value text field. This function takes the given currentTimeRange in seconds and sets the graphical items in the display accordingly.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
currentTimeRange input, the time range at startup
ref input, the reference given to with the addSymbol ("" if used directly as a plot or the symbol name in a page)
exceptionInfo output, any exceptions are returned here
Referenced by fwTrending_initControlTrendButtons(), and fwTrending_initControlTrendXYButtons().
_fwTrending_initTrendCaption (int curveNumber, dyn_string dsDpe, dyn_dyn_string ddsCurveParams, dyn_string legendObj, dyn_string valueObj, string visibilityObj, dyn_string dsUnit, dyn_string unitObj, bool visibility, dyn_string curveTimeObj, bool bEnabledVisibility)
Purpose: set all the data of the trend caption, the caption contains 8 times: one per curvex (x from 1 to 8) . curveTimex . Textx: legend of the curve DPE . valueCurvex: value of the DPE . unitx: unit of the DPE . visibilityx: check box, visibility state of the curve The trend caption must have the name trendCaption. curveTimex and valueCurvex are set by the trend
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
curveNumber input, curve number
dsDpe input, DPE connected to the curve
ddsCurveParams input, curve parameters: [1]: legend of the DPE [2]: tool tip text of the DPE [3]: color of the curve
legendObj input, name of the legend graphical object
valueObj input, name of the valueCurve graphical object
visibilityObj input, name of the visibility check box graphical object
dsUnit input, unit of the DPE
unitObj input, name of the unit graphical object
visibility input, visibility state of curve
curveTimeObj input, name of the curveTime graphical object
bEnabledVisibility input, enable/disable the visibility check box
Referenced by _fwTrending_initCurve().
_fwTrending_isSystemConnected (string systemName, bool & isConnected, dyn_string & exceptionInfo)
Check if the given system ID is of a system which is connected or not
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
systemName input, name of the system that you want to access
isConnected output, TRUE if required system is connected, else FALSE
exceptionInfo output, details of any exceptions are returned here
Referenced by _fwTrending_isSystemForDpeConnected().
_fwTrending_isSystemForDpeConnected (string curveDpe, bool & isConnected, dyn_string & exceptionInfo)
Check if the system that a dpe is on is connected or not
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
curveDpe input, the data point element that you want to access
isConnected output, TRUE if required system is connected, else FALSE
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_isSystemConnected().
Referenced by _fwTrending_initCurve(), fwTrending_getAllTemplateParametersForConfiguration(), and fwTrendingTree_checkIfNeedsTemplateParameters().
bool _fwTrending_isUnicosEnvironment (dyn_string & exceptionInfo)
This function checks if the Trending Tool is running in a project where UNICOS FW is installed.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
exceptionInfo output, details of any exceptions are returned here
Returns:
Return value - TRUE if UNICOS is installed, else FALSE
_fwTrending_openProgressBar (string sHeader, string sIcon, string text1, string text2, string text3, int iSliderType)
Opens a progressBar as a childPanel. This function is the same as the openProgressBar from std.ctl but it opens the progress bar as a childPanel. The difference between this function and the openProgressBar function is the dpSet of "_VarTrendOpen.PanelName:_original.._value" where "ProgressBar" is replaced byt myModuleName() and the ModuleOnWithPanel replaced with ChildPanelOnCentral().
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
sHeader input, the hearder of the progress bar
sIcon input, the icon to show in the progress bar
text1 input, text to show in the progress bar
text2 input, text to show in the progress bar
text3 input, text to show in the progress bar
iSliderType input, the slider type, 0.. no slider, 1.. permanent slider, 2..normal slider
Referenced by fwTrending_pageExportTrend().
_fwTrending_preparePlotObjectForDisplay (dyn_dyn_string & plotData, string parameterString, dyn_string & exceptionInfo)
Prepare a plot data object to display. This involves: 1) Substituting the template parameters for the known values. 2) Re-getting the extended plot information. This updates the legend texts, units and descriptions with the latest values of the template parameters. 3) Converting any UNICOS style DPEs to PVSS DPEs
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
plotData The plot data object (dyn_dyn_string)
parameterString The string containing the template parameters and values
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_evaluateTemplate(), fwTrending_convertUnicosDpeListToPvssDpeList(), and fwTrending_getPlotDataDpeData().
_fwTrending_splitParameters (string parameters, dyn_dyn_string & dsParameters)
Split the template parameter definition string into a list of template parameter names and values
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
parameters input, the list which contains the definitions of the template parameters
dsParameters output, dsParameters[1] = list of names of parameters dsParameters[2] = list of values of parameters
Referenced by _fwTrending_evaluateTemplate(), fwTrending_checkAllTemplateParameters(), fwTrending_getAllTemplateParametersForConfiguration(), and fwTrending_mergeParameterLists().
_fwTrending_switchCurvesHiddenVisible (dyn_string & currentCurveStatus, dyn_string & exceptionInfo)
In some situations, curve visibility is used and in some curve hidden state is given. These are logical opposites. This function swtiches between the two, by inverting all the entries in the given list.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
currentCurveStatus input/output, the list of values is passed here and is returned inverted
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_getPlotData(), fwTrending_getPlotExtended(), and fwTrending_saveCurrentSettings().
_fwTrending_syncDifferentRangeFormats (string & minRange, string & maxRange, string & combinedRange, dyn_string & exceptionInfo)
The min max range is stored in two ways in the plot object for legacy reasons. One way is with the min and max ranges stored in two different places, the second is with both min and max ranges combined together. This functions ensures that the data in consistent between the two places. By passing fwTrending_CONTENT_DIVIDER seperated lists of the minranges, maxranges and combined min:maxranges the function makes them consistent.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
minRange input, fwTrending_CONTENT_DIVIDER seperated list of min ranges
maxRange input, fwTrending_CONTENT_DIVIDER seperated list of max ranges
combinedRange input, fwTrending_CONTENT_DIVIDER seperated list of combined min/max ranges
exceptionInfo output, details of any exceptions are returned here
References fwTrending_convertDynToString(), and fwTrending_convertStringToDyn().
Referenced by fwTrending_setRuntimePlotDataWithStrings().
_fwTrending_updateHistogram (string dpa, dyn_float value)
Work function called to update the histogram display when the data source dyn_dpe is modified.
Constraints
Not for reuse, only used by Histogram display as a callback function.
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpa The name of the dpa that changed
value The new value of the dpe
References _fwTrending_evaluateTemplate(), and fwTrending_getRuntimePlotDataWithExtendedObject().
fwTrending_addFaceplate (string moduleName, string panelName, string refName, string plotDpName, dyn_string templateParameterNames, dyn_string templateParameterValues, int x, int y, dyn_string & exceptionInfo, float xScale = 1.0, float yScale = 1.0)
This function provides an easy way of adding a faceplate to show a given predefined plot dp to a panel as a symbol (instead of using addSymbol() directly).
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
moduleName the name of the module on which the faceplate should be added
panelName the name of the module on which the faceplate should be added
refName the reference name of the new symbol to be added to the panel (can not be "") This name is used as the faceplate plot title
plotDpName the plot data point to use for the configuration of the faceplate
templateParameterNames a list of any template parameters that you wish to pass
templateParameterValues a list of value for template parameters named in templateParameterNames
x the x position on the panel to add the symbol
y the y position on the panel to add the symbol
exceptionInfo output, details of any exceptions are returned here
xScale optional, scaling factor for x (default=1)
yScale optional, scaling factor for y (default=1)
References _fwTrending_convertPlotDataToDollars(), and fwTrending_getPlotExtended().
Referenced by fwTrending_addQuickFaceplate().
fwTrending_addQuickFaceplate (string moduleName, string panelName, string refName, dyn_string dpesToPlot, int x, int y, dyn_string & exceptionInfo, string plotDpName = "_FwTrendingQuickPlotDefaults", float xScale = 1.0, float yScale = 1.0)
This function provides an easy way of adding a faceplate to plot a given list of dpes to a panel as a symbol (instead of using addSymbol() directly).
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
moduleName the name of the module on which the faceplate should be added
panelName the name of the module on which the faceplate should be added
refName the reference name of the new symbol to be added to the panel (can not be "") This name is used as the faceplate plot title
dpesToPlot the list of dpes to show in the plot
x the x position on the panel to add the symbol
y the y position on the panel to add the symbol
exceptionInfo output, details of any exceptions are returned here
plotDpName OPTIONAL PARAMETER: The plot dp name to use a a template from which the plot configuration is read (all configuration of the plot except the dpes to plot). If not specified the standard QuickPlot defaults data point is used.
xScale OPTIONAL PARAMETER: A scaling factor to be applied in the X axis, default value 1.0
yScale OPTIONAL PARAMETER: A scaling factor to be applied in the Y axis, default value 1.0
References fwTrending_addFaceplate().
fwTrending_appendCurve (string plotDp, dyn_string curveData, dyn_string & exceptionInfo)
Appends a curve configuration to the first undefined curve position of a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curveData input, a curve data object (as defined by fwTrending_CURVE_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
References fwTrending_appendManyCurves().
fwTrending_appendManyCurves (string plotDp, dyn_dyn_string curvesData, dyn_string & exceptionInfo)
Appneds many curve configurations to the first undefined curve positions of a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curvesData input, a list of curve data objects (as defined by fwTrending_CURVE_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getFreeCurves(), and fwTrending_setManyCurves().
Referenced by fwTrending_appendCurve().
void fwTrending_changeTrendTimeRange (string ref, int range, string refControl, string localTimeRangeObjValue, int itemPos, string itemText)
Change the time range of the trend which is currently being displayed. The time range of the inactive trend is also updated.
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
range input, the time range in seconds
refControl input, reference of the trendControl
localTimeRangeObjValue input, the value in string format of the current time
itemPos input, position of the text in the cascade button that has to be modified
itemText input, the text to set for the entry in the cascade button
References _fwTrending_gotoNow(), fwTrending_getRuntimePlotDataWithStrings(), and fwTrending_setRuntimePlotDataWithStrings().
fwTrending_checkAllTemplateParameters (dyn_string & requiredParameters, string givenParameterString, bool & gotValuesForAll, dyn_string & exceptionInfo)
Compare the list of the required template parameters with the contents of the $templateParameters
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
requiredParameters input/output, the list of required template parameters
givenParameterString input, the contents of $templateParameter in the standard string format
gotValuesForAll output, the configuration data to find the parameters in
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_splitParameters().
Referenced by fwTrending_checkAndGetAllTemplateParameters().
fwTrending_checkAndGetAllTemplateParameters (string uniqueIdentifier, dyn_dyn_string configurationData, string configurationType, string & currentParameters, dyn_string & exceptionInfo, bool relativePosition = FALSE, bool returnDefaultIfCancel = FALSE)
Compare the template parameters required by the given configuration with the current defined template parameters
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
uniqueIdentifier input, a unique identifier for this plot on the panel. e.g. the reference name
configurationData input, the configuration data for the plot or page
configurationType input, the type of configuration, either fwTrending_PLOT or fwTrending_PAGE
currentParameters input/output, the currently defined template parameters is passed here in string format the updated list is returned here when the function is finished
exceptionInfo output, details of any exceptions are returned here
relativePosition input, Optional parameter - default value = FALSE FALSE - show the dialog in the centre TRUE - show the dialog relative to the calling object
returnDefaultIfCancel input, Optional parameter - default value = FALSE FALSE - if the user presses cancel, leave currentParameters as it was passed TRUE - if the user presses cancel, set each parameter to its default value (i.e. the name of the parameter)
References fwTrending_checkAllTemplateParameters(), and fwTrending_getAllTemplateParametersForConfiguration().
Referenced by fwTrendingTree_getTemplateParameters().
fwTrending_checkCurveName (string dpe, bool & tempBool, dyn_string & exceptionInfo)
Check a given curve name is a legal data point name. Template parameter markers are allowed.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe input, the dpe name to check
tempBool output, TRUE if valid, else FALSE
exceptionInfo output, details of any exceptions are returned here
fwTrending_clearAlarmLimits (shape trendShape, string curveName, dyn_string exceptionInfo)
Remove all the alarm limits from the trending area.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Public
PVSS managers
VISION
Parameters:
trendShape input, name of the active trend graphical object
curveName input, name of the curve for which to clear the alarms
exceptionInfo output, the exception is returned here
Referenced by fwTrending_initTrendWithObject(), and fwTrending_toggleAlarmLimits().
fwTrending_controlBarOnOff (string ref, int visible)
Show / hide the control menu bar and the bottom caption bar
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
visible input, visibility state of the control bar. It is used as a bit mask (bit 0 = control bar, bit 1 = caption bar). 0=visible, 1=hidden. int values: 0: control bar and caption bar visible (default) 1: control bar hidden, caption bar visible 2: control bar visible, caption bar hidden 3: control bar hidden, caption bar hidden
References fwTrending_getRuntimePlotDataWithStrings(), and fwTrending_setRuntimePlotDataWithStrings().
Referenced by fwTrending_initTrendWithObject(), and fwTrending_toggleControlBar().
fwTrending_convertDynToString (dyn_anytype valueList, string & valueString, dyn_string & exceptionInfo)
Convert a dyn_string to a string which is seperated by the fwTrending_CONTENT_DIVIDER. The resulting string will always have at least fwTrending_TRENDING_MAX_CURVE dividers.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
valueList input, the dyn_string to be put into the string
valueString output, the fwTrending_CONTENT_DIVIDER seperated string
exceptionInfo output, details of any exceptions are returned here
Referenced by _fwTrending_convertPlotDataToDollars(), _fwTrending_syncDifferentRangeFormats(), fwTrending_convertUnicosDpeStringToPvssDpeString(), fwTrending_getPlotData(), fwTrending_setRuntimePageDataWithObject(), and fwTrending_setRuntimePlotDataWithExtendedObject().
fwTrending_convertPvssDpeListToUnicosDpeList (dyn_string pvssDpes, dyn_string & unicosDpes, dyn_string & exceptionInfo)
Convert a list of PVSS style dpes to a list of UNICOS style dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pvssDpes input, a list of PVSS style dpes
unicosDpes output, a list of UNICOS dpes is returned here
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_rebuildDpeUNICOS().
fwTrending_convertStringToDyn (string valueString, dyn_anytype & valueList, dyn_string & exceptionInfo)
Convert a string which is seperated by the fwTrending_CONTENT_DIVIDER into a dyn_string. The resulting dyn_string will always have at least fwTrending_TRENDING_MAX_CURVE entries.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
valueString input, string to be split
valueList output, the dyn_string containing the parts of the original string
exceptionInfo output, details of any exceptions are returned here
Referenced by _fwTrending_connectToAlarmHandling(), _fwTrending_syncDifferentRangeFormats(), fwTrending_convertUnicosDpeStringToPvssDpeString(), fwTrending_getPlotExtended(), fwTrending_getRuntimePageDataWithObject(), fwTrending_getRuntimePlotDataWithExtendedObject(), fwTrending_initControlTrendButtons(), fwTrending_pageExportTrend(), fwTrending_ShowCurve(), and fwTrending_showStandardTrend().
fwTrending_convertUnicosDpeListToPvssDpeList (dyn_string unicosDpes, dyn_string & pvssDpes, dyn_string & exceptionInfo)
Convert a list of UNICOS style dpes to a list of PVSS style dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
unicosDpes input, a list of UNICOS dpes
pvssDpes output, a list of PVSS style dpes is returned here
exceptionInfo output, details of any exceptions are returned here
Referenced by _fwTrending_preparePlotObjectForDisplay(), fwTrending_convertUnicosDpeStringToPvssDpeString(), and fwTrending_exportTrend().
fwTrending_convertUnicosDpeStringToPvssDpeString (string unicosDpes, string & pvssDpes, dyn_string & exceptionInfo)
Convert a fwTrending_CONTENT_DIVIDER seperated string of UNICOS style dpes to a fwTrending_CONTENT_DIVIDER seperated string of PVSS style dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
unicosDpes input, the fwTrending_CONTENT_DIVIDER seperated string of UNICOS dpes
pvssDpes output, a fwTrending_CONTENT_DIVIDER seperated string of PVSS style dpes is returned here
exceptionInfo output, details of any exceptions are returned here
References fwTrending_convertDynToString(), fwTrending_convertStringToDyn(), and fwTrending_convertUnicosDpeListToPvssDpeList().
Referenced by fwTrending_initControlTrendButtons(), and fwTrending_pageExportTrend().
void fwTrending_copyPage (string _from, string _to)
Creates a new page and copies all the configuration data from a source page to the new page.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
_from the data point name of the source page
_to the data point name of the page to create
References fwTrending_copyPageData(), and fwTrending_createPage().
void fwTrending_copyPageData (string _from, string _to)
Copies all the configuration data from a source page to a target page that already exists.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
_from the data point name of the source page
_to the data point name of the target page
References fwTrending_getPage(), and fwTrending_setPage().
Referenced by fwTrending_copyPage().
void fwTrending_copyPlot (string _from, string _to)
Creates a new plot and copies all the configuration data from a source plot to the new plot.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
_from the data point name of the source plot
_to the data point name of the plot to create
References fwTrending_copyPlotData(), and fwTrending_createPlot().
void fwTrending_copyPlotData (string _from, string _to)
Copies all the configuration data from a source plot to a target plot that already exists.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
_from the data point name of the source plot
_to the data point name of the target plot
References fwTrending_getPlot(), and fwTrending_setPlot().
Referenced by fwTrending_copyPlot().
fwTrending_createPage (string sPageName, dyn_string & exInfo, string model = fwTrending_YT_PAGE_MODEL)
Creates a page data point. The page configuration is initialised to default values. Checks are carried out if the name is valid or if it already exists.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPageName the data point name of the page to create
exInfo details of any exceptions are returned here
model OPTIONAL PARAMETER - default value fwTrending_YT_PAGE_MODEL (value over time plot) Defines the type of plot to be created, e.g. fwTrending_YT_PAGE_MODEL fwTrending_XY_PAGE_MODEL
References fwTrending_newPage().
Referenced by fwTrending_copyPage(), and fwTrending_saveCurrentSettings().
fwTrending_createPlot (string sPlotName, dyn_string & exInfo, string model = fwTrending_YT_PLOT_MODEL)
Creates a plot data point. Checks are carried out if the name is valid or if it already exists.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPlotName the data point name of the plot to create
exInfo details of any exceptions are returned here
model OPTIONAL PARAMETER - default value fwTrending_YT_PLOT_MODEL (value over time plot) Defines the type of plot to be created, e.g. fwTrending_YT_PLOT_MODEL fwTrending_XY_PLOT_MODEL fwTrending_HISTOGRAM_PLOT_MODEL
References fwTrending_newPlot().
Referenced by fwTrending_copyPlot(), and fwTrending_saveCurrentSettings().
fwTrending_deleteCurve (string plotDp, int curveToDelete, dyn_string & exceptionInfo)
Delete a curve configuration from the specified curve position of a plot configuration data point.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curveToDelete input, the position of the curve to delete
exceptionInfo output, details of any exceptions are returned here
References fwTrending_deleteManyCurves().
fwTrending_deleteManyCurves (string plotDp, dyn_int curvesToDelete, dyn_string & exceptionInfo)
Delete many curve configurations from the specified curve positions of a plot configuration data point.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curvesToDelete input, the positions of the curves to delete
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_getCurveObjectIndexes(), and fwTrending_setManyCurves().
Referenced by fwTrending_deleteCurve().
fwTrending_deletePage (string sPageName, dyn_string & exceptionInfo)
Deletes a given plot data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPageName the data point name of the plot to delete
exceptionInfo details of any exceptions are returned here
fwTrending_deletePlot (string sPlotName, dyn_string & exceptionInfo)
Deletes a given plot data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPlotName the data point name of the plot to delete
exceptionInfo details of any exceptions are returned here
fwTrending_disconnectActiveTrend (dyn_string dsCurveDPE, string activeTrend)
Purpose: disconnect the curves of the active trend, this function is called when switching from standard to log and vice-versa, the non active trend is disconnected to the DPEs
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
dsCurveDPE input, list of 8 DPEs connected to the curves of the plot
activeTrend input, name of the active trend graphical element (with any reference name included e.g. ref.standardTrend)
fwTrending_editPage (string sDpName)
Open a configuration panel to edit the given plot
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
sDpName input, the data point name of the the plot to configure
fwTrending_editPlot (string sDpName)
Open a configuration panel to edit the given plot
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
sDpName input, the data point name of the the plot to configure
fwTrending_eventsSort (dyn_dyn_time ddt, dyn_dyn_bool & events, dyn_time & times)
Sort the data of multiple dpGetPeriod calls. Data is reorganised into order of time stamp.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
ddt input, list of the time stamps from each dpGetPeriod call
events output, a 2-dimensional giving a dyn_bool for each timestamp in 'times'. Each dyn_bool contains a list of bools, one for each dpGetPeriod to say if the dpGetPeriod returned data for that given timestamp and hence which dpe had a value at that timestamp.
times output, a sorted list of the timestamps in ddt
Referenced by fwTrending_exportTrend().
fwTrending_exportTrend (string fileName, dyn_string dsCurveDPE, dyn_string dsLegendCurve, dyn_time dtStart, dyn_time dtEnd, string templateParameters, dyn_string & exceptionInfo, bool fillEmptyCells = FALSE)
Export the history of the given dpes, between the given times to a CSV file
Constraints
Can be slow if lots of data is returned and put in the file
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
fileName input: file name to export the data to
dsCurveDPE input, list of DPEs to export the data from
dsLegendCurve input, list of associated legends to use a headers in the file
dtStart input, start time for the query of the DPEs (one time per dpe)
dtEnd input, end time for the query of the DPEs (one time per dpe)
templateParameters input, any template parameter substitutions
exceptionInfo output, details of any exceptions are returned here
fillEmptyCells input, Optional parameter - default FALSE FALSE - just put data from history into file TRUE - apply 0th order interpolation to fill all cells in file (easier for automatic analysis)
References _fwTrending_evaluateTemplate(), fwTrending_convertUnicosDpeListToPvssDpeList(), fwTrending_eventsSort(), and fwTrending_rebuildDpeUNICOS().
Referenced by fwTrending_pageExportTrend().
fwTrending_getAllPages (dyn_string & pageDpNames, dyn_string & exceptionInfo)
Get all the page DP names on all systems
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pageDpNames the list of page dp names is returned here
exceptionInfo details of any exceptions are returned here
References fwTrending_getPageDpNames().
fwTrending_getAllPlots (dyn_string & plotDpNames, dyn_string & exceptionInfo)
Get all the plot DP names on all systems
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDpNames the list of plot dp names is returned here
exceptionInfo details of any exceptions are returned here
References fwTrending_getPlotDpNames().
fwTrending_getAllTemplateParametersForConfiguration (dyn_dyn_string configurationData, string configurationType, dyn_string & templateParameters, dyn_string & exceptionInfo)
Find all the template parameters required to display a given plot or page.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
configurationData input, the configuration data for the plot or page
configurationType input, the type of configuration, either fwTrending_PLOT or fwTrending_PAGE
templateParameters output, the list of required template parameters is returned here
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_findTemplateParameters(), _fwTrending_isSystemForDpeConnected(), _fwTrending_splitParameters(), and fwTrending_getPlot().
Referenced by fwTrending_checkAndGetAllTemplateParameters(), fwTrending_modifyAllTemplateParameters(), and fwTrendingTree_checkIfNeedsTemplateParameters().
string fwTrending_getColRow (dyn_string plotsList, int column, int row)
Read the relevant plot name from the dyn_string containing a list of the plots on a page by giving the column and row of the plot.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotsList input, the list of plots on a page
column input, the column of the plot to read
row input, the row of the plot to read
Returns:
The name of the plot at this position on the page is returned
fwTrending_getCurve (string plotDp, bool & isCurveDefined, dyn_string & curveData, int curveToGet, dyn_string & exceptionInfo)
Get the curve configuration from a specified curve position of a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
isCurveDefined output, TRUE is curve is defined, else FALSE
curveData output, the curve data configuration object is returned here (as defined by fwTrending_CURVE_OBJECT_... constants)
curveToGet input, the position of the curve to get
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_getCurveObjectIndexes(), and fwTrending_getPlot().
fwTrending_getDaysHoursMinutesFromTimeRange (int timeRange, int & days, int & hours, int & minutes, dyn_string & exceptionInfo)
Purpose: get the amount of days, hours minutes from a specified time range (in s) to be shown on the trend.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
timeRange input, the time range (in seconds) to be converted.
days output, the amount of days in the time range
hours output, the amount of hours in the time range
minutes output, the amount of minutes in the time range
exceptionInfo output, any exceptions are returned here
fwTrending_getFirstFreeCurve (string plotDp, int & position, dyn_string & exceptionInfo)
Gets the position of the first undefined curve in a plot configuration data point. If there are no free curves, the position -1 is returned.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
position output, the position of first undefined curve in the configuration is returned here
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getFreeCurves().
fwTrending_getFreeCurves (string plotDp, dyn_int & positions, dyn_string & exceptionInfo)
Gets a list of the positions of undefined curves in a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
positions output, a list of the positions of undefined curve in the configuration is returned here
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getPlot().
Referenced by fwTrending_appendManyCurves(), fwTrending_getFirstFreeCurve(), and fwTrending_insertCurveAt().
fwTrending_getNumberOfCurves (string plotDp, int & numberOfCurves, dyn_string & exceptionInfo)
Gets the number of curves that are defined in a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
numberOfCurves output, the number of defined curves in the configuration is returned here
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getPlot().
Referenced by fwTrending_removeCurve().
fwTrending_getPage (string pageDp, dyn_dyn_string & pageData, dyn_string & exceptionInfo)
Reads all the page configuration from a page datapoint.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pageDp input, the page data point to read
pageData output, details of the page are returned here (see fwTrending_PAGE_OBJECT.... constants for info on what is returned)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_copyPageData(), fwTrending_getPagePlotDps(), fwTrendingTree_checkIfNeedsTemplateParameters(), fwTrendingTree_getTemplateParameters(), fwTrendingTree_showNavigatorPanel(), and TrendTree_nodeParameters().
fwTrending_getPageDpNames (dyn_string & pageDpNames, dyn_string & exceptionInfo, string pattern = "*:*")
Get all the page DP names that match the given pattern
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pageDpNames the list of page dp names is returned here
exceptionInfo details of any exceptions are returned here
pattern Optional parameter, default value "*:*" (all page on all systems). Specify a filter to search for page.
Referenced by fwTrending_getAllPages().
fwTrending_getPagePlotDps (string sPageName, dyn_string & dsPlotDps)
Get the list of plot dps that belong to a page
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPageName input, the page DP name
dsPlotDps output, the list of plot DP Names of type FwTrendingPlot the dps are ordered by column: plots of column 1, followed by plots of column 2, etc. with no "" between
References fwTrending_getPage(), and fwTrending_simplifyPagePlotList().
fwTrending_getPageTitle (string sDpPageName, string & sPageTitle)
Get the title of the given page data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sDpPageName input, the data point name of the page to read the title from
sPageTitle output, the title is returned here
References fwTrending_getTitle().
fwTrending_getPlot (string plotDp, dyn_dyn_string & plotData, dyn_string & exceptionInfo)
Reads all the plot configuration from a plot datapoint.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the plot data point to read
plotData output, details of the plot are returned here (see fwTrending_PLOT_OBJECT.... constants for info on what is returned)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_copyPlotData(), fwTrending_getAllTemplateParametersForConfiguration(), fwTrending_getCurve(), fwTrending_getFreeCurves(), fwTrending_getNumberOfCurves(), fwTrending_getPlotData(), fwTrending_insertCurveAt(), fwTrending_newPlot(), fwTrending_removeCurve(), fwTrending_setManyCurves(), fwTrendingTree_checkIfNeedsTemplateParameters(), fwTrendingTree_getTemplateParameters(), fwTrendingTree_showNavigatorPanel(), and TrendTree_nodeParameters().
fwTrending_getPlotData (string ref, string sDpName, dyn_string & returnValue)
Get the data from the DP of type FwTrendingPlot and return it in the format for the fwTrending/fwTrendingTrend.pnl If ref is "" then the legend is taken but if it is not then we assume that this is a multiple plot panel and therefore the legend is set to the leaf DPE if any.
Please do not call this function directly. Instead, please use fwTrending_getPlot or fwTrending_getPlotExtended
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
ref input, reference used in the addSymbol function, this is considered when getting the legend.
sDpName input, the plot data point to read
returnValue output, details of the plot are returned here
References _fwTrending_switchCurvesHiddenVisible(), fwTrending_convertDynToString(), fwTrending_getPlot(), and fwTrending_getPlotDataDpeData().
Referenced by fwTrending_getPlotExtended().
fwTrending_getPlotDataDpeData (string sPlotDpe, string & sDpe, string & sUnit, string & sDescription)
Get the data related to a specific dpe to be plotted (real DPE, description and unit). This function is able to deal with DPE or UNICOS format DPE: systemName:AliasName.DPELeaf
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPlotDpe input, dpe of the FwTrendingPlot DP, real DP or UNICOS format DPE: systemName:AliasName.DPELeaf
sDpe output, real DPE
sUnit output, unit of the DPE
sDescription output, description of the DPE DPE
References _fwTrending_evaluateTemplate().
Referenced by _fwTrending_preparePlotObjectForDisplay(), and fwTrending_getPlotData().
fwTrending_getPlotDpNames (dyn_string & plotDpNames, dyn_string & exceptionInfo, string pattern = "*:*")
Get all the plot DP names that match the given pattern
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDpNames the list of plot dp names is returned here
exceptionInfo details of any exceptions are returned here
pattern Optional parameter, default value "*:*" (all plots on all systems). Specify a filter to search for plots.
Referenced by fwTrending_getAllPlots().
fwTrending_getPlotExtended (string plotDp, string refName, dyn_dyn_string & plotExtendedData, dyn_string & exceptionInfo, bool returnCurveVisible = FALSE)
Reads all the plot configuration from a plot datapoint and does some additional processing to get all the data required to draw a plot.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the plot data point to read
refName input, reference used in the addSymbol function, this is considered when getting the legend.
plotExtendedData output, details of the plot are returned here (see fwTrending_PLOT_OBJECT.... constants for info on what is returned as well as fwTrending_PLOT_OBJECT_EXT.... constants)
exceptionInfo output, details of any exceptions are returned here
returnCurveVisible input {OPTIONAL - default = FALSE}, TRUE to return curve visible state FALSE to return curve hidden state
References _fwTrending_switchCurvesHiddenVisible(), fwTrending_convertStringToDyn(), and fwTrending_getPlotData().
Referenced by fwTrending_addFaceplate().
fwTrending_getPlotIsTemplate (string sDpPlotName, string & bIsTemplate)
Get the template status of the given plot data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sDpPlotName input, the data point name of the plot to check if template
bIsTemplate output, returns if the plot is flagged as template. TRUE = is template
fwTrending_getPlotTitle (string sDpPlotName, string & sPlotTitle)
Get the title of the given plot data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sDpPlotName input, the data point name of the plot to read the title from
sPlotTitle output, the title is returned here
References fwTrending_getTitle().
fwTrending_getRuntimePageDataWithObject (dyn_dyn_string & pageObject, dyn_string & exceptionInfo)
Get the runtime page data
Constraints
Dependant on graphical objects of standard page panel
Usage
Public
PVSS managers
VISION
Parameters:
pageObject output, the runtime data is returned in this page object (as defined by fwTrending_PAGE_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
References fwTrending_convertStringToDyn(), and fwTrending_getRuntimePageDataWithStrings().
Referenced by fwTrending_saveCurrentSettings().
fwTrending_getRuntimePageDataWithStrings (dyn_string & pageData, dyn_string & exceptionInfo)
Get the runtime page data
Constraints
Dependant on graphical objects of standard page panel
Usage
Public
PVSS managers
VISION
Parameters:
pageData output, the runtime data is returned here in dyn_string format (as defined by fwTrending_PAGE_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_getRuntimePageDataWithObject().
fwTrending_getRuntimePlotDataWithExtendedObject (string refName, string & isRunning, dyn_string & plotShapes, dyn_dyn_string & plotExtendedObject, dyn_string & exceptionInfo, bool runningInsideTrend = TRUE)
Get the runtime plot data
Constraints
Dependant on graphical objects of standard plot panel
Usage
Public
PVSS managers
VISION
Parameters:
refName input, the reference name of the trend
isRunning output, "TRUE" if the plot is be running, else "FALSE"
plotShapes output, the list of plot shapes is returned here - standard, log and active
plotExtendedObject output, the plot object is returned here (as defined by fwTrending_PLOT_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
runningInsideTrend input, Optional parameter - default TRUE TRUE if call is from within the same referecne as the trend, else FALSE
References fwTrending_convertStringToDyn(), and fwTrending_getRuntimePlotDataWithStrings().
Referenced by _fwTrending_updateHistogram(), and fwTrending_saveCurrentSettings().
fwTrending_getRuntimePlotDataWithStrings (string refName, string & isRunning, dyn_string & plotShapes, dyn_string & plotData, dyn_string & exceptionInfo, bool runningInsideTrend = TRUE)
Get the runtime plot data
Constraints
Dependant on graphical objects of standard plot panel
Usage
Public
PVSS managers
VISION
Parameters:
refName input, the reference name of the trend
isRunning output, "TRUE" if the plot is be running, else "FALSE"
plotShapes output, the list of plot shapes is returned here - standard, log and active
plotData output, the plot data is returned here (in dyn_string format) (as defined by fwTrending_PLOT_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
runningInsideTrend input, Optional parameter - default TRUE TRUE if call is from within the same referecne as the trend, else FALSE
Referenced by fwTrending_changeTrendTimeRange(), fwTrending_controlBarOnOff(), fwTrending_getRuntimePlotDataWithExtendedObject(), fwTrending_gridOnOff(), fwTrending_initControlTrendButtons(), fwTrending_initControlTrendXYButtons(), fwTrending_legendOnOff(), fwTrending_markersOnOff(), fwTrending_pageExportTrend(), fwTrending_ShowCurve(), fwTrending_toggleControlBar(), fwTrending_trendRefresh(), fwTrending_trendRun(), fwTrending_trendTimeBack(), fwTrending_trendUnzoom(), fwTrending_trendZoomX(), and fwTrending_trendZoomY().
fwTrending_getTimeRangeFromDaysHoursMinutes (int & timeRange, int days, int hours, int minutes, dyn_string & exceptionInfo)
Purpose: get the time range (in s) to be shown on the trend from a specified amount of days, hours minutes.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
timeRange output, the time range in seconds.
days input, the amount of days in the time range
hours input, the amount of hours in the time range
minutes input, the amount of minutes in the time range
exceptionInfo output, any exceptions are returned here
fwTrending_getTitle (string sDpName, string & sTitle, dyn_string & exceptionInfo)
Get the title of the given plot or page data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sDpName input, the data point name of the plot or page to read the title from
sTitle output, the title is returned here
exceptionInfo details of any exceptions are returned here
Referenced by fwTrending_getPageTitle(), and fwTrending_getPlotTitle().
fwTrending_gridOnOff (string ref, bool bShowGrid, string refControl, dyn_string & exceptionInfo)
Show or hide the grid of the trend
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
bShowGrid input, TRUE to show grid, FALSE to hide grid
refControl input, reference of the trendControl
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getRuntimePlotDataWithStrings(), and fwTrending_setRuntimePlotDataWithStrings().
fwTrending_initControlHistogramButtons (string ref, string sDpName, dyn_string plotData, bool trendRunning, dyn_string exceptionInfo, bool bCallBack = true)
Purpose: set the button state and value of the fwTrending/fwTrendingHistogramControl.pnl. This function is called by the initScript of the fwTrending/fwTrendingHistogram.pnl. The sRef is mandatory in case of multiple plot sRef must be the reference given in the addSymbol function. The fwTrending/fwTrendingHistogram.pnl reference must be sRef+"trend". If the sDpName is "" or not of type _FwTrendingPlot, the option other->Plot configuration and Save settings is disabled If the access control is not used or not defined the option other->Plot configuration and Save settings is enabled as described above. If the access control is used and defined the option other->Plot configuration and Save settings is enabled as described above if the user loged in has the second level of priviledge of the first domain.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
ref input, the reference given to with the addSymbol ("" if used directly as a plot or the symbol name in a page)
sDpName input, the plot DP or "" if using the $params to pass configure the plot
plotData input, the plot object that is being displayed in the display (contents of trendInfo object).
trendRunning input, TRUE if the trend is running, else FALSE.
exceptionInfo output, any exceptions are returned here
fwTrending_initControlTrendButtons (int currentTimeRange, string sRef, string sDpName, string sTrendLog, bool bCallBack = true)
Purpose: set the button state and value of the fwTrending/fwTrendingTrendControl.pnl. This function is called by the initScript of the fwTrending/fwTrendingTrend.pnl. The sRef is mandatory in case of multiple plot sRef must be the reference given in the addSymbol function. The fwTrending/fwTrendingTrend.pnl reference must be sRef+"trend". If the sDpName is "" or not of type FwTrendingPlot, the option other->Plot configuration and Save settings is disabled If the access control is not used or not defined the option other->Plot configuration and Save settings is enabled as described above. If the access control is used and defined the option other->Plot configuration and Save settings is enabled as described above if the user loged in has the second level of priviledge of the first domain.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. The runtime data must have been transferred to the 'trendInfo' list object before calling this function. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
currentTimeRange input, the time range at startup
sRef input, the reference given to with the addSymbol ("" if used directly as a plot or the symbol name in a page)
sDpName input, the plot DP or "" if using the $params to pass configure the plot
sTrendLog input, TRUE if this is a log trend.
References _fwTrending_evaluateTemplate(), _fwTrending_initGenericTrendControls(), _fwTrending_initTimeRange(), fwTrending_convertStringToDyn(), fwTrending_convertUnicosDpeStringToPvssDpeString(), and fwTrending_getRuntimePlotDataWithStrings().
fwTrending_initControlTrendXYButtons (int currentTimeRange, string sRef, string sDpName, string sTrendLog)
Purpose: set the button state and value of the fwTrending/fwTrendingTrendXYControl.pnl. This function is called by the initScript of the fwTrending/fwTrendingTrendXY.pnl. The sRef is mandatory in case of multiple plot sRef must be the reference given in the addSymbol function. The fwTrending/fwTrendingTrendXY.pnl reference must be sRef+"trend". If the sDpName is "" or not of type FwTrendingPlot, the option other->Plot configuration and Save settings is disabled If the access control is not used or not defined the option other->Plot configuration and Save settings is enabled as described above. If the access control is used and defined the option other->Plot configuration and Save settings is enabled as described above if the user loged in has the second level of priviledge of the first domain.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. The runtime data must have been transferred to the 'trendInfo' list object before calling this function. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
currentTimeRange input, the time range at startup
sRef input, the reference given to with the addSymbol ("" if used directly as a plot or the symbol name in a page)
sDpName input, the plot DP or "" if using the $params to pass configure the plot
sTrendLog input, TRUE if this is a log trend.
References _fwTrending_initGenericTrendControls(), _fwTrending_initTimeRange(), and fwTrending_getRuntimePlotDataWithStrings().
fwTrending_initHistogramWithObject (string sRef, string trendName, dyn_dyn_string plotExtendedObject, bool runTrend, dyn_string & exceptionInfo)
Purpose: initialize the histogram. This function is called from the initScript of the fwTrending/fwTrendingHistogram.pnl. It configure the trend with the configuration passed in plotExtendedObject.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
sRef input, reference given when adding the corresponding panel, the panel containing the fwTrending/fwTrendingHistogram.pnl and a caption or fwTrending/fwTrendingHistogram.pnl must have the reference name of sRef+"trend"
trendName input, active trend name
plotExtendedObject input, details of the plot are returned here (see fwTrending_PLOT_OBJECT.... constants for info on what needs to be passed as well as fwTrending_PLOT_OBJECT_EXT.... constants)
runTrend input, "TRUE" if the trend must be in running mode, else FALSE
exceptionInfo output, the exception is returned here
fwTrending_initTrendWithObject (string sRef, string trendName, dyn_string trendShapeStr, dyn_dyn_string plotExtendedObject, bool runTrend, bool bInitCaption, dyn_string & exceptionInfo, bool passingCurveVisible = FALSE)
Purpose: initialize the trends. This function is called from the initScript of the fwTrending/fwTrendingTrend.pnl and the log check box of fwTrending/fwTrendingTrendControl.pnl. It stops the standard and log trend, sets the time range of both trends, initializes all the curves of the active trend and starts if necessary the active trend.
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Internal
PVSS managers
VISION
Parameters:
sRef input, reference given when adding the corresponding panel, the panel containing the fwTrending/fwTrendingTrend.pnl and a caption or fwTrending/fwTrendingTrend.pnl must have the reference name of sRef+"trend"
trendName input, active trend name
trendShapeStr input, name of the trend graphical objects, [1]: standard trend [2]: log trend [3]: active trend
plotExtendedObject input, details of the plot are returned here (see fwTrending_PLOT_OBJECT.... constants for info on what needs to be passed as well as fwTrending_PLOT_OBJECT_EXT.... constants)
runTrend input, "TRUE" if the trend must be in running mode
bInitCaption input, "TRUE" if the trend caption should be initialised
exceptionInfo output, the exception is returned here
passingCurveVisible input {OPTIONAL - default = FALSE}, TRUE if passing curve visible state FALSE if passing curve hidden state
References _fwTrending_gotoNow(), _fwTrending_initCurve(), fwTrending_clearAlarmLimits(), and fwTrending_controlBarOnOff().
fwTrending_insertCurveAt (string plotDp, dyn_string curveData, int position, dyn_string & exceptionInfo, bool forceInsert = FALSE)
Inserts a given curve configuration to a certain curve position of a plot configuration data point. The previous curve from that position and curves from later positions are moved one position along to provide space for the new curve. Similar in concept to dynInsertAt().
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curveData input, a curve data object (as defined by fwTrending_CURVE_OBJECT_... constants)
position input, the position in which to insert this curve
exceptionInfo output, details of any exceptions are returned here
forceInsert OPTIONAL PARAMETER - default value FALSE If TRUE, if the 8th curve is in use, it will be lost when the new curve is inserted If FALSE, if the 8th curve is in use, an exception will be raised and no curve inserted
References _fwTrending_checkCurveData(), _fwTrending_getCurveObjectIndexes(), fwTrending_getFreeCurves(), fwTrending_getPlot(), and fwTrending_setPlot().
fwTrending_legendOnOff (string ref, bool bShowLegend, string refControl, dyn_string & exceptionInfo)
Show or hide the legend of the trend
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
bShowLegend input, TRUE to show legend, FALSE to hide legend
refControl input, reference of the trendControl
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getRuntimePlotDataWithStrings(), and fwTrending_setRuntimePlotDataWithStrings().
fwTrending_markersOnOff (string ref, int markerType, string refControl, dyn_string & exceptionInfo)
Show or hide the markers of all the curves in the trend
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
markerType input, type of markers: fwTrending_MARKER_TYPE_FILLED_CIRCLE fwTrending_MARKER_TYPE_UNFILLED_CIRCLE fwTrending_MARKER_TYPE_NONE
refControl input, reference of the trendControl
exceptionInfo output, details of any exceptions are returned here
References fwTrending_getRuntimePlotDataWithStrings(), and fwTrending_setRuntimePlotDataWithStrings().
fwTrending_mergeParameterLists (string firstList, string secondList, string & returnedList, dyn_string & exceptionInfo)
Merge two lists of template parameters into a single string. If a value is specified in both lists, the value from the first list has precedence, unless the value in the first list starts with { and ends with } (i.e. is an undefined template parameter)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
firstList input, one list of template parameters in string format
secondList input, another list of template parameters in string format
returnedList output, the merged list is returned here is string format
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_splitParameters().
fwTrending_modifyAllTemplateParameters (string uniqueIdentifier, dyn_dyn_string configurationData, string configurationType, string & currentParameters, dyn_string & exceptionInfo, bool relativePosition = FALSE)
Allows for modification of the values of the template parameters.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
uniqueIdentifier input, a unique identifier for this plot on the panel. e.g. the reference name
configurationData input, the configuration data for the plot or page
configurationType input, the type of configuration, either fwTrending_PLOT or fwTrending_PAGE
currentParameters input/output, the currently defined template parameters is passed here in string format the updated list is returned here when the function is finished
exceptionInfo output, details of any exceptions are returned here
relativePosition input, Optional parameter - default value = FALSE FALSE - show the dialog in the centre TRUE - show the dialog relative to the calling object
References fwTrending_getAllTemplateParametersForConfiguration().
Referenced by TrendTree_nodeParameters().
void fwTrending_newPage (string _pageName, string model = fwTrending_YT_PAGE_MODEL)
Creates a page data point. The page configuration is initialised to default values. THIS IS AN INTERNAL FUNCTION - If you want to create a page use fwTrending_createPage
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
_pageName the data point name of the page to create
model OPTIONAL PARAMETER - default value fwTrending_YT_PAGE_MODEL (value over time plot) Defines the type of plot to be created, e.g. fwTrending_YT_PAGE_MODEL fwTrending_XY_PAGE_MODEL
References fwTrending_setPage().
Referenced by fwTrending_createPage().
void fwTrending_newPlot (string _plotName, string model = fwTrending_YT_PLOT_MODEL)
Creates a plot data point. The plot configuration is initialised to default values. THIS IS AN INTERNAL FUNCTION - If you want to create a plot use fwTrending_createPlot
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
_plotName the data point name of the plot to create
model OPTIONAL PARAMETER - default value fwTrending_YT_PLOT_MODEL (value over time plot) Defines the type of plot to be created, e.g. fwTrending_YT_PLOT_MODEL fwTrending_XY_PLOT_MODEL fwTrending_HISTOGRAM_PLOT_MODEL
References fwTrending_getPlot(), and fwTrending_setPlot().
Referenced by fwTrending_createPlot().
fwTrending_openPlotDisplay (string sPlotDpName, string sPanelFileName, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, unsigned x = 0, unsigned y = 0, string sResizeMode = "")
Opens a plot display with various options as to how it is opened.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sPlotDpName input, the plot data point name to show
sPanelFileName input, the file name of the panel to use (use constants such as fwTrending_PANEL_PLOT_STANDARD)
bAsNewModule input, should the display be opened in a new module, TRUE = new module, FALSE = child panel
bStayOnTopOrModal input, for a new module - TRUE = stay on top, FALSE = normal behaviour for a child panel - TRUE = modal child panel, FALSE = normal behaviour
sModuleName input, the name of the new module (if required)
sPanelName input, the name of the new panel
x input, Optional parameter - default value 0. X position of the new display
y input, Optional parameter - default value 0. Y position of the new display
sResizeMode input, Optional parameter - default value "". "" Default from the config file (see config entry visionResizeMode chapter User interface on PVSS Help) "None" ... Scaling not possible in the VISION module. "Scale" ... Scaling possible in the VISION module by changing the size of the window. "Zoom" ... Scaling only possible with the Navigator
fwTrending_pageExportTrend (dyn_string dsRef, string templateParameters)
Export the data displayed in all the plots of a page to a CSV file
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
dsRef input, list of reference of the trends
templateParameters input, any template parameter substitutions
References _fwTrending_closeProgressBar(), _fwTrending_evaluateTemplate(), _fwTrending_openProgressBar(), fwTrending_convertStringToDyn(), fwTrending_convertUnicosDpeStringToPvssDpeString(), fwTrending_exportTrend(), and fwTrending_getRuntimePlotDataWithStrings().
fwTrending_pageSavePlotSettings (string ref)
Save the plot settings of a plot
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
References fwTrending_saveCurrentSettings().
fwTrending_rebuildDpeUNICOS (dyn_string dpes, dyn_string & fileDpe)
Convert a list of PVSS style dpes to UNICOS style dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes input, list of PVSS dpes
fileDpe output, list of UNICOS format dpes
References fwTrending_convertPvssDpeListToUnicosDpeList().
Referenced by fwTrending_exportTrend().
fwTrending_removeCurve (string plotDp, int curveToRemove, dyn_string & exceptionInfo)
Remove a curve configuration from the specified curve position of a plot configuration data point. The curves from later positions are moved one position back to remove the space left by the removal of the curve. Similar in concept to dynRemove().
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curveToRemove input, the position of the curve to remove
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_getCurveObjectIndexes(), fwTrending_getNumberOfCurves(), fwTrending_getPlot(), and fwTrending_setPlot().
fwTrending_removeFaceplate (string moduleName, string panelName, string refName, dyn_string & exceptionInfo)
This function provides an easy way of removing a faceplate that was addded with the fwTrending_addFaceplate or fwTrending_addQuickFaceplate functions.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
moduleName the name of the module on which the faceplate is displayed
panelName the name of the module on which the faceplate is displayed
refName the reference name of the faceplate to remove
exceptionInfo output, details of any exceptions are returned here
fwTrending_saveCurrentSettings (string ref, string sDpName, string sDpType, bool createNewDpIfRequired, bool overwriteExisting, dyn_string & exceptionInfo, bool useDpNameForTitle = FALSE)
Save the current runtime plot configuration to a plot data point
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
sDpName input, the data point name to save the plot configuration to
sDpType input, the dp type of the data point to save the plot configuration to
createNewDpIfRequired input, TRUE to create new dp if sDpName does not exist, else FALSE
overwriteExisting input, TRUE to overwrite any existing contents of sDpName, else FALSE
exceptionInfo output, details of any exceptions are returned here
useDpNameForTitle input, Optional parameter - default FALSE FALSE - use plot title from currently displayed instance TRUE - change plot title of new plot to the same as sDpName
References _fwTrending_switchCurvesHiddenVisible(), fwTrending_createPage(), fwTrending_createPlot(), fwTrending_getRuntimePageDataWithObject(), fwTrending_getRuntimePlotDataWithExtendedObject(), fwTrending_setPage(), and fwTrending_setPlot().
Referenced by fwTrending_pageSavePlotSettings().
void fwTrending_setColRow (dyn_string & plotsList, int column, int row, string plotName)
Writes the given plot name to the dyn_string containing a list of the plots on a page by giving the column and row of the plot.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotsList the list of plots on a page is passed here and is updated by the function
column input, the column of the plot to read
row input, the row of the plot to read
plotName input, the name of the plot to add in the list of plots on a page
fwTrending_setCurve (string plotDp, dyn_string curveData, int curveToSet, dyn_string & exceptionInfo)
Sets a given curve configuration to certain curve position of a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curveData input, a curve data object (as defined by fwTrending_CURVE_OBJECT_... constants)
curveToSet input, the position in which to set this curve
exceptionInfo output, details of any exceptions are returned here
References fwTrending_setManyCurves().
fwTrending_setManyCurves (string plotDp, dyn_dyn_string curvesData, dyn_int curvesToSet, dyn_string & exceptionInfo)
Sets many curve configurations to certain curve positions of a plot configuration data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the name of the plot configuration data point
curvesData input, a list of curve data objects (as defined by fwTrending_CURVE_OBJECT_... constants)
curvesToSet input, the positions in which to set these curves
exceptionInfo output, details of any exceptions are returned here
References _fwTrending_checkCurveData(), _fwTrending_getCurveObjectIndexes(), fwTrending_getPlot(), and fwTrending_setPlot().
Referenced by fwTrending_appendManyCurves(), fwTrending_deleteManyCurves(), and fwTrending_setCurve().
fwTrending_setPage (string pageDp, dyn_dyn_string pageData, dyn_string & exceptionInfo)
Writes all the page configuration data to a page datapoint.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
pageDp input, the page data point to write to
pageData input, details of the page are passed here (see fwTrending_PAGE_OBJECT.... constants for info on what is returned)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_copyPageData(), fwTrending_newPage(), and fwTrending_saveCurrentSettings().
fwTrending_setPlot (string plotDp, dyn_dyn_string plotData, dyn_string & exceptionInfo)
Writes all the plot configuration data to a plot datapoint.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
plotDp input, the plot data point to write to
plotData input, details of the plot are passed here (see fwTrending_PLOT_OBJECT.... constants for info on what is returned)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_copyPlotData(), fwTrending_insertCurveAt(), fwTrending_newPlot(), fwTrending_removeCurve(), fwTrending_saveCurrentSettings(), and fwTrending_setManyCurves().
fwTrending_setPlotIsTemplate (string sDpPlotName, string bIsTemplate)
Set the template status of the given plot data point
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
sDpPlotName input, the data point name of the plot to check if template
bIsTemplate input, if the plot is flagged as template. TRUE = is template
fwTrending_setRuntimePageDataWithObject (dyn_dyn_string pageObject, dyn_string & exceptionInfo)
Set the runtime page data with the given page configuration
Constraints
Dependant on graphical objects of standard page panel
Usage
Public
PVSS managers
VISION
Parameters:
pageObject input, the page object to set as the runtime data (as defined by fwTrending_PAGE_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
References fwTrending_convertDynToString(), and fwTrending_setRuntimePageDataWithStrings().
fwTrending_setRuntimePageDataWithStrings (dyn_string pageData, dyn_string & exceptionInfo)
Set the runtime page data with the given page configuration (in dyn_string format)
Constraints
Dependant on graphical objects of standard page panel
Usage
Public
PVSS managers
VISION
Parameters:
pageData input, the page data to set as the runtime data (as defined by fwTrending_PAGE_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_setRuntimePageDataWithObject().
fwTrending_setRuntimePlotDataWithExtendedObject (string refName, string isRunning, dyn_dyn_string plotExtendedObject, dyn_string & exceptionInfo, bool runningInsideTrend = TRUE)
Set the runtime plot data with the given extended plot configuration.
Constraints
Dependant on graphical objects of standard plot panel
Usage
Public
PVSS managers
VISION
Parameters:
refName input, the reference name of the trend
isRunning input, "TRUE" if the plot should be running, else "FALSE"
plotExtendedObject input, the extended plot object to set as the runtime data (as defined by fwTrending_PLOT_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
runningInsideTrend input, Optional parameter - default TRUE TRUE if call is from within the same referecne as the trend, else FALSE
References fwTrending_convertDynToString(), and fwTrending_setRuntimePlotDataWithStrings().
fwTrending_setRuntimePlotDataWithStrings (string refName, string isRunning, dyn_string plotData, dyn_string & exceptionInfo, bool runningInsideTrend = TRUE)
Set the runtime plot data with the given plot configuration (in dyn_string format)
Constraints
Dependant on graphical objects of standard plot panel
Usage
Public
PVSS managers
VISION
Parameters:
refName input, the reference name of the trend
isRunning input, "TRUE" if the plot should be running, else "FALSE"
plotData input, the plot data to set as the runtime data (as defined by fwTrending_PLOT_OBJECT_... constants)
exceptionInfo output, details of any exceptions are returned here
runningInsideTrend input, Optional parameter - default TRUE TRUE if call is from within the same referecne as the trend, else FALSE
References _fwTrending_syncDifferentRangeFormats().
Referenced by fwTrending_changeTrendTimeRange(), fwTrending_controlBarOnOff(), fwTrending_gridOnOff(), fwTrending_legendOnOff(), fwTrending_markersOnOff(), fwTrending_setRuntimePlotDataWithExtendedObject(), and fwTrending_ShowCurve().
fwTrending_setTimeScaleFormat (string trendName, dyn_string & exceptionInfo)
Reads the current visible time range and picks a scale format (dates or times) that best suits the range. Currently the switch between times and dates occurs around a time range of 2 days.
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
trendName input, the name of the trend widget to work on
exceptionInfo input, details of any exceptions are returned here
fwTrending_ShowCurve (string ref, string trendName, int curveNumber, bool visibility)
Purpose: show/hide a curve, this fucntion is called from the caption.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
ref input, the name of reference within which the trend objects are being displayed
trendName input, name of the graphical element containing the name of the active trend (usually "trend.activeTrendText")
curveNumber input, curve number to act on (from 1 to 8)
visibility input, visibility state of the curve
References fwTrending_convertStringToDyn(), fwTrending_getRuntimePlotDataWithStrings(), fwTrending_setRuntimePlotDataWithStrings(), and fwTrending_toggleAlarmLimits().
fwTrending_showPlot (int iNumberOfPlots, dyn_string dsPlotName, dyn_string & dsReference, dyn_string templateParameters)
Show the plots at the necessary size and position on a page
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
iNumberOfPlots input, the number of plots which are to be shown on the current page
dsPlotName input, the list of plot DP Names for this page
dsReference output, list of references of the plot symbols which were added
templateParameters input, contains any template parameter substitutions to be passed to the plots
fwTrending_showStandardTrend (bool visibility, string standardStr, string logStr, dyn_dyn_string plotData = "")
Show the standard or log trend
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
visibility input, visibility state of the standard trend (TRUE to show standard trend, FALSE to show log trend)
standardStr input, name of the standard trend graphical element (with any reference name included e.g. ref.logTrend)
logStr input, name of the log trend graphical element (with any reference name included e.g. ref.standardTrend)
plotData optional input, plot data
References fwTrending_convertStringToDyn().
fwTrending_simplifyPagePlotList (dyn_string dsRawPlotList, int rows, int columns, dyn_string & dsSimplePlotList, dyn_string & exceptionInfo)
Simplify the list of plots that comes from the page configuration dp
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dsRawPlotList input, the raw plot list from the page configuration dp
rows input, the number of rows on the page
columns input, the number of columns on the page
dsSimplePlotList output, the simplfied list of plots on the page
exceptionInfo output, details of any exceptions are returned here
Referenced by fwTrending_getPagePlotDps().
fwTrending_toggleAlarmLimits (string curveName, string curveDpeName, bool curveLimitsVisibility, shape trendShape, dyn_string exceptionInfo, string sCurveStyle = fwTrending_DEFAULT_CURVE_STYLE, bool clearLimits = FALSE)
Show/hide the alarm limits related to a plotted dpe.
Constraints
This function shows only the alarm limits for analog alarms. Binary, discrete and summary alarms are not shown. This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Public
PVSS managers
VISION
Parameters:
curveName input, name of the curve
curveDpeName input, DPE connected to the curve
curveLimitsVisibility input, visibility state of the limits of the curve
trendShape input, name of the active trend graphical object
exceptionInfo output, the exception is returned here
sCurveStyle input, optional, style of the curve. For an example of style, look at fwTrending_DEFAULT_CURVE_STYLE
clearLimits input, optional, if TRUE, then all the limits on the plot area are erased before showing/hiding them
References fwTrending_clearAlarmLimits().
Referenced by _fwTrending_initCurve(), and fwTrending_ShowCurve().
fwTrending_toggleControlBar (string ref)
Show / hide the control menu bar and the bottom caption bar depending on last status
Constraints
This function is only for use with the standard trend panel as it makes direct reference to many of the graphical objects. Not for reuse.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
References fwTrending_controlBarOnOff(), and fwTrending_getRuntimePlotDataWithStrings().
fwTrending_trendRefresh (string ref)
Refreshes the data displayed by the trend
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
References fwTrending_getRuntimePlotDataWithStrings().
fwTrending_trendRun (string ref, bool bRunTrend, string refControl)
Run or Freeze the trend. The options in the trend controls are enabled/disable as appropriate
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
bRunTrend input, TRUE to run, FALSE to freeze
refControl input, reference of the trendControl
References fwTrending_getRuntimePlotDataWithStrings().
fwTrending_trendTimeBack (string ref, bool bTimeBack)
Set the time begin of a trend back or forward from the current time begin
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
bTimeBack input, true go back in time, false go forward in time back in time: newTimeBegin=currentTimeBegin-(period(currentTimeEnd)-period(currentTimeBegin))/fwTrending_TIME_BACK_RESOLUTION forward in time: newTimeBegin=currentTimeBegin+(period(currentTimeEnd)-period(currentTimeBegin))/fwTrending_TIME_FORWARD_RESOLUTION if newTYimeBegin > current time, no newTimeBegin is set.
References fwTrending_getRuntimePlotDataWithStrings().
fwTrending_trendUnzoom (string ref)
Reset the zoom of the trend (1:1)
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
References fwTrending_getRuntimePlotDataWithStrings().
fwTrending_trendZoomX (string ref, bool bZoomIn)
Zoom in or out on the X axis of the trend.
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
bZoomIn input, TRUE to zoom in, FALSE to zoom out
References fwTrending_getRuntimePlotDataWithStrings().
fwTrending_trendZoomY (string ref, bool bZoomIn)
Zoom in or out on the Y axis of the trend.
Constraints
Depends heavily on the standard trend window graphical objects.
Usage
Public
PVSS managers
VISION
Parameters:
ref input, reference of the trend
bZoomIn input, TRUE to zoom in, FALSE to zoom out
References fwTrending_getRuntimePlotDataWithStrings().