fwConfigs: fwAlertConfigDeprecated.ctl File Reference
fwAlertConfigDeprecated.ctl File Reference
Functions
fwAlertConfig_getMany (dyn_string dpes, dyn_bool &configExists, dyn_int &alertConfigType, dyn_dyn_string &alertTexts, dyn_dyn_float &alertLimits, dyn_dyn_string &alertClasses, dyn_dyn_string &summaryDpeList, dyn_string &alertPanel, dyn_dyn_string &alertPanelParameters, dyn_string &alertHelp, dyn_bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_get (string dpe, bool &configExists, int &alertConfigType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClasses, dyn_string &summaryDpeList, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_getDiscrete (string dpe, bool &configExists, int &alertConfigType, dyn_string &alertTexts, dyn_float &alertLimits, dyn_string &alertClasses, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, bool &discrete, bool &impulse, dyn_bool &discreteNegation, string &stateBits, dyn_string &stateMatch, dyn_string &exceptionInfo)
fwAlertConfig_setMultiple (dyn_string dpes, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE, bool discrete=FALSE, bool impulse=FALSE, dyn_bool discreteNegation=FALSE, string stateBits="", dyn_string stateMatch="")
fwAlertConfig_setMany (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_dyn_string summaryDpeList, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE, dyn_bool discrete=FALSE, dyn_bool impulse=FALSE, dyn_dyn_bool discreteNegation=FALSE, dyn_string stateBits="", dyn_dyn_string stateMatch="")
fwAlertConfig_setManyDiscrete (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, bool storeInParamHistory=TRUE, dyn_bool discrete=FALSE, dyn_bool impulse=FALSE, dyn_dyn_bool discreteNegation=FALSE, dyn_string stateBits="", dyn_dyn_string stateMatch="")
fwAlertConfig_set (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, string addDpeInSummary="", bool storeInParamHistory=TRUE, bool discrete=FALSE, bool impulse=FALSE, dyn_bool discreteNegation=FALSE, string stateBits="", dyn_string stateMatch="")
fwAlertConfig_setDiscrete (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE, bool fallBackToSet=FALSE, bool storeInParamHistory=TRUE, bool discrete=FALSE, bool impulse=FALSE, dyn_bool discreteNegation=FALSE, string stateBits="", dyn_string stateMatch="")
fwAlertConfig_setGeneral (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClass, string alertPanel, dyn_string alertPanelParameters, string help, bool alertRequest, dyn_string &exceptionInfo)
fwAlertConfig_setDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE)
fwAlertConfig_setAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE)
fwAlertConfig_setSummary (string dpe, dyn_string alertTexts, dyn_string dpElementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo, bool modifyOnly=FALSE)
fwAlertConfig_createSummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_modifySummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_createDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_modifyDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_createAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_modifyAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string &exceptionInfo)
fwAlertConfig_deleteSummary (string dpe, dyn_string &exceptionInfo)
fwAlertConfig_deleteAnalog (string dpe, dyn_string &exceptionInfo)
fwAlertConfig_deleteDigital (string dpe, dyn_string &exceptionInfo)
fwAlertConfig_getSummary (string dpe, bool &configExists, dyn_string &alertTexts, dyn_string &dpeList, string &alertPanel, dyn_string &alertPanelParameters, string &alertHelp, bool &isActive, dyn_string &exceptionInfo)
fwAlertConfig_getLimits (string dpe, dyn_int &limitNumbers, dyn_float &limitValues, dyn_string &exceptionInfo)
fwAlertConfig_setLimits (string dpe, dyn_int limitNumbers, dyn_float limitValues, dyn_string &exceptionInfo, bool checkBeforeSetting=FALSE, bool storeInParamHistory=TRUE)
Detailed Description
fwAlertConfigDeprecated.ctl This library contains deprecated functions associated with the alert handling config. Functions are provided for backward compatibility and are not being maintained.
Creation Date
14/09/2011
Constraints
Note: Deprecated functions, kept for backward compatibility only. It is recommended to use the new functions in fwAlertConfig.ctl: fwAlertConfig_objectSet(), fwAlertConfig_objectGet(), fwAlertConfig_objectSetMany(), fwAlertConfig_objectGetMany(). See the functions for use examples.
Usage
Public
PVSS managers
VISION, CTRL
Author
Marco Boccioli. Functions from Oliver Holme (IT-CO) based on original by Herve Milcent, Niko Karlsson based on libMLDBEH_ANLEGEN.ctl
/** Returns the details of any alert configuration on a given set of dpes. This function can handle digital, analog and summary alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectGetMany() instead.
Constraints
Can only get summary alerts of type dp list (not dp pattern)
Usage
Public
PVSS managers
VISION, CTRL
Function Documentation
fwAlertConfig_createAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to create an analog alert
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Usage
DEPRECATED
fwAlertConfig_createDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to create a digital alert
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Usage
DEPRECATED
fwAlertConfig_createSummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to create a summary alert
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Usage
DEPRECATED
fwAlertConfig_deleteAnalog (string dpe, dyn_string & exceptionInfo)
DEPRECATED - Function to delete an analog alert
Deprecated:
This function is deprecated. Use fwAlertConfig_delete() instead.
For new function see fwAlertConfig_delete
Usage
DEPRECATED
fwAlertConfig_deleteDigital (string dpe, dyn_string & exceptionInfo)
DEPRECATED - Function to delete a digital alert
Deprecated:
This function is deprecated. Use fwAlertConfig_delete() instead.
Usage
DEPRECATED
fwAlertConfig_deleteSummary (string dpe, dyn_string & exceptionInfo)
DEPRECATED - Function to delete a summary alert
Deprecated:
This function is deprecated. Use fwAlertConfig_delete() instead.
Usage
DEPRECATED
fwAlertConfig_get (string dpe, bool & configExists, int & alertConfigType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClasses, dyn_string & summaryDpeList, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, dyn_string & exceptionInfo)
Returns the details of any alert configuration on a given dpe.
This function can handle digital, analog and summary alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectGet() instead.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe Name of data point element to read from
configExists Return TRUE if dpe has an alert config, else FALSE
alertConfigType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts are returned here for all types of alert
alertLimits Alert limits are returned here for analog alerts
alertClasses Alert classes are returned here for digital and analog alertd
summaryDpeList If Summary alert, the dpeList is returned here If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
exceptionInfo Details of any exceptions are returned here
Referenced by fwAlertConfig_addDpInAlertSummary(), fwAlertConfig_checkIsDpInAlertSummary(), and fwAlertConfig_deleteDpFromAlertSummary().
fwAlertConfig_getDiscrete (string dpe, bool & configExists, int & alertConfigType, dyn_string & alertTexts, dyn_float & alertLimits, dyn_string & alertClasses, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, bool & discrete, bool & impulse, dyn_bool & discreteNegation, string & stateBits, dyn_string & stateMatch, dyn_string & exceptionInfo)
Returns the details of any alert configuration on a given dpe.
This function can handle digital, analog and summary alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectGet() instead.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe input, Name of data point element to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertConfigType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts are returned here for all types of alert
alertLimits Alert limits are returned here for analog alerts
alertClasses Alert classes are returned here for digital and analog alertd
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
discrete TRUE if alert is discrete else FALSE
impulse TRUE if alert is impulse alert else FALSE
discreteNegation for each match values, TRUE if the match is negated (i.e. "!=").
stateBits state bits of the discrete alert
stateMatch state bits of each value match
exceptionInfo Details of any exceptions are returned here
fwAlertConfig_getLimits (string dpe, dyn_int & limitNumbers, dyn_float & limitValues, dyn_string & exceptionInfo)
Gets the alert limits for the currently configured alert ranges on the given data point element.
Deprecated:
This function is deprecated. Use fwAlertConfig_objectGet() instead.
Constraints
Only works on data points that have an analog alert handling set up.
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe Data point element to read limits from
limitNumbers The numbers of the limits are returned here This is always a list of integers starting at 1 up to the number of (ranges - 1) e.g. For a 5 range alert the value returned will be {1,2,3,4}
limitValues The values of the limits are returned here The limits are always returned is ascending order
exceptionInfo Details of any exceptions are returned here
Referenced by _fwAlertConfig_get(), and _fwAlertConfig_getDiscrete().
fwAlertConfig_getMany (dyn_string dpes, dyn_bool & configExists, dyn_int & alertConfigType, dyn_dyn_string & alertTexts, dyn_dyn_float & alertLimits, dyn_dyn_string & alertClasses, dyn_dyn_string & summaryDpeList, dyn_string & alertPanel, dyn_dyn_string & alertPanelParameters, dyn_string & alertHelp, dyn_bool & isActive, dyn_string & exceptionInfo)
Parameters
dpes Name of data point elements to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertConfigType Type of alert on dpe: DPCONFIG_ALERT_BINARYSIGNAL if digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL if analog alert handling DPCONFIG_SUM_ALERT if summary alert handling
alertTexts Alert texts are returned here for all types of alert
alertLimits Alert limits are returned here for analog alerts
alertClasses Alert classes are returned here for digital and analog alertd
summaryDpeList If Summary alert, the dpeList is returned here If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
exceptionInfo Details of any exceptions are returned here
fwAlertConfig_getSummary (string dpe, bool & configExists, dyn_string & alertTexts, dyn_string & dpeList, string & alertPanel, dyn_string & alertPanelParameters, string & alertHelp, bool & isActive, dyn_string & exceptionInfo)
DEPRECATED - Returns the details of the summary alert configuration on a given dpe.
    This function raises an exception if the summary alert uses a DP pattern as this is not supported by the FW.
NOTE: THIS FUNCTION SHOULD NOT BE CALLED DIRECTLY
Deprecated:
This function is deprecated. Use fwAlertConfig_objectGet() instead.
Constraints
Can only get summary alerts of type dp list (not dp pattern)
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters
dpe Name of data point element to read from
configExists Return TRUE if dpe has a summary alert config, else FALSE
alertTexts Two alert texts will be returned if summary alert exists (alertText[1] = Good State Text, alertText[2] = Bad State Text)
dpeList The list of dp elements that are used in the alert summary If a DP pattern was specified, then this will be returned as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
isActive TRUE if alert is active else FALSE
exceptionInfo Details of any exceptions are returned here
fwAlertConfig_modifyAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to modify an analog alert
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Usage
DEPRECATED
fwAlertConfig_modifyDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to modify a digital alert
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Usage
DEPRECATED
fwAlertConfig_modifySummary (string dpe, dyn_string alertTexts, dyn_string dpelementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo)
DEPRECATED - Function to modify a summary alert
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Usage
DEPRECATED
fwAlertConfig_set (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE, bool discrete = FALSE, bool impulse = FALSE, dyn_bool discreteNegation = FALSE, string stateBits = "", dyn_string stateMatch = "")
Sets the alert configuration on a given dpe.
This function can handle digital, analog, discrete and summary alerts.
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
Can only get summary alerts of type dp list (not dp pattern)
For digital alerts: The length of the alertTexts and alertClasses dyn_strings must both be 2 For analog alerts: The length of the alertTexts and alertClasses dyn_strings must be equal The length of the alertLimits dyn_float must be one less than the length of alertTexts For summary alerts: The length of the alertTexts dyn_string must be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe Data point element
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling DPCONFIG_SUM_ALERT for summary alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
summaryDpeList If Summary alert, the dpeList is passed here (otherwise ignored). If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify one value (i.e. 000010011000) per alarm.
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
Referenced by fwAlertConfig_addDpInAlertSummary(), and fwAlertConfig_deleteDpFromAlertSummary().
fwAlertConfig_setAnalog (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE)
DEPRECATED
Creates analog alert handling on the given data point element without hysteresis. The alert texts, alert limits, alert classes and the alert and help panels are set.
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
The length of the alertTexts and alertClasses dyn_strings must be equal The length of the limits dyn_float must be one less than the length of alertTexts
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters
dpe Name of data point element to act on
alertTexts Alert texts for each range eg. makeDynString("Bad Text", "OK", "Bad Text")
limits The limits of each range given here eg. makeDynFloat(20, 60);
alertClasses Alert classes for each range eg. makeDynString("_fwErrorAck.", "" , "_fwErrorAck.") One of the items of the dyn_string must always be empty to indicate the valid state. The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. With TRUE this is equal to the functionality provided by fwAlertConfig_modifyAnalog With FALSE this is equal to the functionality provided by fwAlertConfig_createAnalog
fwAlertConfig_setDigital (string dpe, dyn_string alertTexts, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE)
DECPRECATED
Creates digital alert handling on the given data point element. The alert texts, alert class of the bad state and the alert and help panels are set.
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
The length of the alertTexts and alertClasses dyn_strings must both be 2
Usage
DECPRECATED
PVSS managers
VISION, CTRL
Parameters
dpe Name of data point element to act on
alertTexts Alert texts eg. makeDynString("Bad Text", "OK")
alertClasses Alert classes eg. makeDynString("_fwErrorAck.", "") One of the items of the dyn_string must always be empty to indicate the valid state The valid ranges becomes the state with no alert class given (the second in this case). Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. With TRUE this is equal to the functionality provided by fwAlertConfig_modifyDigital With FALSE this is equal to the functionality provided by fwAlertConfig_createDigital
fwAlertConfig_setDiscrete (string dpe, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, bool storeInParamHistory = TRUE, bool discrete = FALSE, bool impulse = FALSE, dyn_bool discreteNegation = FALSE, string stateBits = "", dyn_string stateMatch = "")
Sets the discrete alert configuration on a given dpe.
This function can handle discrete digital and discrete analog alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
This function can handle only discrete alerts
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe Data point element
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify one value (i.e. 000010011000) per alarm.
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
fwAlertConfig_setGeneral (string dpe, dyn_string alertTexts, dyn_float limits, dyn_string alertClass, string alertPanel, dyn_string alertPanelParameters, string help, bool alertRequest, dyn_string & exceptionInfo)
 DEPRECATED - Modifies an existing analog alert handling with 5 ranges on the given data point element.
The function has similar functionality to _fwAlertConfig_createAnalog5 except that the type of alert handling for the config are not altered. This avoids problems which occur when altering the type of the alert config when something is dpConencted to the config.
Deprecated:
THIS FUNCTION SHOULD NOT BE USED (see constraints below). Use fwAlertConfig_objectSet() instead.
Constraints
This is an internal function and should not be called directly To modify an analog alert with 5 ranges the function fwAlertConfig_set should be used
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters
dpe Name of data point element to act on
alertTexts Alert texts for each range
limits The limits of each range given here
alertClass Alert classes for each range One of the items of the dyn_string must always be empty to indicate the valid state. Don't forget to add the dot to the alert class names.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in alertPanel
help Help text or path to help file
alertRequest whether to delete (FALSE) or create/modify (TRUE) the alert config
exceptionInfo Details of any exceptions are returned here
fwAlertConfig_setLimits (string dpe, dyn_int limitNumbers, dyn_float limitValues, dyn_string & exceptionInfo, bool checkBeforeSetting = FALSE, bool storeInParamHistory = TRUE)
Sets the alert limits for the currently configured alert ranges on the given data point element.
The values in the same position in limitNumbers and limitValues form a pair of values. The pair consists of the limit number to act on and limit value to set.
Example usage: DEPRECATED
limitNumbers = {3,4,2}
                          limitValues = {30,50,10}
                          This will set the limit between Range 2 and 3 to 10
                          This will set the limit between Range 3 and 4 to 30
                          This will set the limit between Range 4 and 5 to 50
NOTE: Not all the limits need to be specified in the input parameters
NOTE: Values in limitNumbers must be between 1 and (number of ranges - 1)
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
Only works on data points that have an analog alert handling set up. This function can not change the number of ranges defined in the alert config. If only some limits are specified, the new limits must be consistent with the old values that will not be modified
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe Data point element to set the limits to
limitNumbers The numbers of the limits to be modified are passed here
limitValues The values of the limits to be modified are passed here The values in this list correspond to the limit numbers given in limitNumbers
exceptionInfo Details of any exceptions are returned here
checkBeforeSetting OPTIONAL PARAMETER - default value FALSE If TRUE, the new limit values are compared with the existing limits to check that the final configuration will be consistent (i.e. all the range limits are in ascending order with no duplicates). In case of inconsistencies, an exception will be raised. If FALSE, the new limits are not checked and an error will appear in the log when the dpSetWait is performed and an exception will be raised.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
fwAlertConfig_setMany (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_dyn_string summaryDpeList, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE, dyn_bool discrete = FALSE, dyn_bool impulse = FALSE, dyn_dyn_bool discreteNegation = FALSE, dyn_string stateBits = "", dyn_dyn_string stateMatch = "")
Sets the alert configuration on for a list of dpes.
This function can handle digital, analog, discrete and summary alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSetMany() instead.
Constraints
Can only set summary alerts of type dp list (not dp pattern)
For digital alerts: The length of the alertTexts and alertClasses dyn_strings must both be 2 For analog alerts: The length of the alertTexts and alertClasses dyn_strings must be equal The length of the alertLimits dyn_float must be one less than the length of alertTexts For summary alerts: The length of the alertTexts dyn_string must be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes List of data point elements
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling DPCONFIG_SUM_ALERT for summary alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
summaryDpeList If Summary alert, the dpeList is passed here (otherwise ignored) If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify a value (i.e. 000010011000)
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
fwAlertConfig_setManyDiscrete (dyn_string dpes, dyn_int alertConfigType, dyn_dyn_string alertTexts, dyn_dyn_float alertLimits, dyn_dyn_string alertClasses, dyn_string alertPanel, dyn_dyn_string alertPanelParameters, dyn_string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, bool storeInParamHistory = TRUE, dyn_bool discrete = FALSE, dyn_bool impulse = FALSE, dyn_dyn_bool discreteNegation = FALSE, dyn_string stateBits = "", dyn_dyn_string stateMatch = "")
Sets the alert configuration on for a list of dpes.
This function can handle discrete analog and discrete digital alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
This function can handle only discrete alerts
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes List of data point elements
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify one value (i.e. 000010011000) per alarm.
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
fwAlertConfig_setMultiple (dyn_string dpes, int alertConfigType, dyn_string alertTexts, dyn_float alertLimits, dyn_string alertClasses, dyn_string summaryDpeList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE, bool fallBackToSet = FALSE, string addDpeInSummary = "", bool storeInParamHistory = TRUE, bool discrete = FALSE, bool impulse = FALSE, dyn_bool discreteNegation = FALSE, string stateBits = "", dyn_string stateMatch = "")
Sets the alert configuration on for a list of dpes.
This function can handle digital, analog and summary alerts
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSetMany() instead.
Constraints
Can only set summary alerts of type dp list (not dp pattern)
For digital alerts: The length of the alertTexts and alertClasses dyn_strings must both be 2 For analog alerts: The length of the alertTexts and alertClasses dyn_strings must be equal The length of the alertLimits dyn_float must be one less than the length of alertTexts For summary alerts: The length of the alertTexts dyn_string must be 2
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes List of data point elements
alertConfigType Type of alert to set: DPCONFIG_ALERT_BINARYSIGNAL for digital alert handling DPCONFIG_ALERT_NONBINARYSIGNAL for analog alert handling DPCONFIG_SUM_ALERT for summary alert handling
alertTexts Alert texts are passed here for all types of alert
alertLimits Alert limits are passed here for analog alerts (otherwise ignored)
alertClasses Alert classes are passed here for digital and analog alerts (otherwise ignored)
summaryDpeList If Summary alert, the dpeList is passed here (otherwise ignored) If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to the given alertPanel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. This is much quicker, but the alert config must already exist, be an analog alert and have the same number of ranges as you want.
fallBackToSet Optional parameter - Default value FALSE. Used in combination with modifyOnly. If modifyOnly = TRUE and fallBackToSet = FALSE, then if the alert config is not compatible an exception is raised. If modifyOnly = TRUE and fallBackToSet = TRUE, then if the alert config is not compatible, modifyOnly is treated as if it was FALSE.
addDpeInSummary Optional parameter - Default value "". Used to add the new alert in a summary alert. Default value "" means do not add the new alert into a summary. You can specify either an absolute DPE name, or a relative path from the DP to which the new alert was saved. i.e. addDpeInSummary = "." will add the new alert on dpes[i] to the summary on the root of the datapoint to which dpes[i] belongs. addDpeInSummary = "MyDp.summaries" will add the new alert on dpes[i] to the summary on the dpe called "MyDp.summaries". Note: The summary alarms must already exist. If they does not exist, it WILL NOT be created.
storeInParamHistory OPTIONAL PARAMETER - default value = TRUE You can specify if the change should be stored in the Paramterisation History of PVSS
discrete Optional Parameter - default = FALSE If set to TRUE, the alarm is a Discrete alarm.
impulse Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If set to TRUE, and discrete=TRUE, the alarm is discrete and with impulse.
discreteNegation Optional Parameter - default = FALSE. Used only if discrete=TRUE, otherwise ignored. If alarm is Discrete, you can specify one value (TRUE or FALSE) per limit. FALSE = the alarm is triggered when the value matches the limit. TRUE = the alarm is triggered when the value does not match the limit.
stateBits Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Alarm State Bits. If alarm is Discrete, you can specify a value (i.e. 000010011000)
stateMatch Optional Parameter - default = "". Used only if discrete=TRUE, otherwise ignored. Value Match State Bit. If alarm is Discrete, you can specify one State Bits value (i.e. 00xxxxx0100110x) per limit. 0 = must be 0; 1 = must be 1; x = can be 0 or 1.
fwAlertConfig_setSummary (string dpe, dyn_string alertTexts, dyn_string dpElementList, string alertPanel, dyn_string alertPanelParameters, string alertHelp, dyn_string & exceptionInfo, bool modifyOnly = FALSE)
DEPRECATED
Creates summary alert handling on the given data point element.
Deprecated:
This function is deprecated. Use fwAlertConfig_objectSet() instead.
Constraints
The length of the alertTexts should be 2 Can only set summary alerts of type dp list (not dp pattern)
Usage
DEPRECATED
PVSS managers
VISION, CTRL
Parameters
dpe Name of data point element to act on
alertTexts Alert texts eg. makeDynString("OK", "Bad")
dpElementList List of dpes to include in summary alert. If you want to specify a DP pattern, then this should entered as the first item in this list.
alertPanel Panel to call from the alert screen
alertPanelParameters Parameters to pass to panel given in Alert Panel
alertHelp Help text or path to help file
exceptionInfo Details of any exceptions are returned here
modifyOnly Optional parameter - Default value FALSE. Set to TRUE to modify alert without setting "type" attributes. With TRUE this is equal to the functionality provided by fwAlertConfig_modifySummary With FALSE this is equal to the functionality provided by fwAlertConfig_createSummary