fwConfigs: fwOriginal.ctl File Reference
fwOriginal.ctl File Reference
Functions
fwOriginal_getMany (dyn_string &dpes, dyn_mixed &values, dyn_dyn_bool &infoBits, dyn_string &exceptionInfo)
fwOriginal_get (dyn_string dpe, anytype &value, dyn_mixed &infoBits, dyn_string &exceptionInfo)
fwOriginal_setMany (dyn_string &dpes, dyn_anytype &values, dyn_dyn_bool &infoBits, dyn_string &exceptionInfo, string mode="VALUE_VARIABLE_BITS_USER_BITS")
fwOriginal_set (dyn_string dpe, anytype value, dyn_bool infoBits, dyn_string &exceptionInfo, string mode="VALUE_VARIABLE_BITS_USER_BITS")
fwOriginal_setMultiple (dyn_string dpes, anytype value, dyn_bool infoBits, dyn_string &exceptionInfo, string mode="VALUE_VARIABLE_BITS_USER_BITS")
Detailed Description
This library contains function associated with the original value config. Functions allows to set, get and delete the original config of a dpe or multiple dpes
Creation Date
25/11/2005
Modification History
12/08/11 Marco Boccioli
#85462: Functions *_setMany and *_getMany with parameters as reference.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author
Oliver Holme (IT-CO)
Function Documentation
fwOriginal_get (dyn_string dpe, anytype & value, dyn_mixed & infoBits, dyn_string & exceptionInfo)
Get the Original config data from many data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to read
value input, original value for dpe returned here
infoBits input, info bits (active, invalid and user bits) for dpe returned here Use fwOriginal_DPE_OBJECT_BIT_XXX indexes (see fwConfigConstants.ctl) to retrieve data from dyn_bool
exceptionInfo output, details of any exceptions are returned here
References fwOriginal_getMany().
fwOriginal_getMany (dyn_string & dpes, dyn_mixed & values, dyn_dyn_bool & infoBits, dyn_string & exceptionInfo)
Get the Original config data from many data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes input, list of data point elements to read. Passed as reference only for performance reasons. Not modified.
values input, the list of original values for each dpe are returned here
infoBits input, the list of info bits (active, invalid and user bits) for each dpe are returned here Use fwOriginal_DPE_OBJECT_BIT_XXX indexes (see fwConfigConstants.ctl) to retrieve data from each dyn_bool
exceptionInfo output, details of any exceptions are returned here
References _fwConfigs_getConfigAttributes().
Referenced by fwOriginal_get().
fwOriginal_set (dyn_string dpe, anytype value, dyn_bool infoBits, dyn_string & exceptionInfo, string mode = "VALUE_VARIABLE_BITS_USER_BITS")
Set the Original config data to a data point element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to write to
value input, the original value to be set to dpe is passed here
infoBits input, the info bits (active, invalid and user bits) to be set to dpe are passed here Use fwOriginal_DPE_OBJECT_BIT_XXX indexes (see fwConfigConstants.ctl) to put data into each dyn_bool
exceptionInfo output, details of any exceptions are returned here
mode OPTIONAL PARAMETER: default means value, active, invalid and user bits are all written to original config Use fwOriginal_SET_XXX constants (see fwConfigConstants.ctl) to choose different modes that set only specific parts of the config
References fwOriginal_setMany().
fwOriginal_setMany (dyn_string & dpes, dyn_anytype & values, dyn_dyn_bool & infoBits, dyn_string & exceptionInfo, string mode = "VALUE_VARIABLE_BITS_USER_BITS")
Set the Original config data to many data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes input, list of data point elements to write to. Passed as reference only for performance reasons. Not modified.
values input, the list of original values for each dpe are passed here. Passed as reference only for performance reasons. Not modified.
infoBits input, the list of info bits (active, invalid and user bits) for each dpe are passed here Use fwOriginal_DPE_OBJECT_BIT_XXX indexes (see fwConfigConstants.ctl) to put data into each dyn_bool Passed as reference only for performance reasons. Not modified.
exceptionInfo output, details of any exceptions are returned here
mode OPTIONAL PARAMETER: default means value, active, invalid and user bits are all written to original config Use fwOriginal_SET_XXX constants (see fwConfigConstants.ctl) to choose different modes that set only specific parts of the config
References _fwConfigs_getConfigTypeAttribute(), and _fwConfigs_setConfigAttributes().
Referenced by fwOriginal_set(), and fwOriginal_setMultiple().
fwOriginal_setMultiple (dyn_string dpes, anytype value, dyn_bool infoBits, dyn_string & exceptionInfo, string mode = "VALUE_VARIABLE_BITS_USER_BITS")
Set the same Original config data to many data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes input, list of data point elements to write to
value input, the original value to be set to every dpe is passed here
infoBits input, the info bits (active, invalid and user bits) to be set to every dpe are passed here Use fwOriginal_DPE_OBJECT_BIT_XXX indexes (see fwConfigConstants.ctl) to put data into each dyn_bool
exceptionInfo output, details of any exceptions are returned here
mode OPTIONAL PARAMETER: default means value, active, invalid and user bits are all written to original config Use fwOriginal_SET_XXX constants (see fwConfigConstants.ctl) to choose different modes that set only specific parts of the config
References fwOriginal_setMany().