fwConfigs: fwPeriphAddressS7.ctl File Reference
fwPeriphAddressS7.ctl File Reference
Functions
_fwPeriphAddressS7_set (string dpe, dyn_anytype addressConfig, dyn_string &exceptionInfo)
fwPeriphAddress_checkS7Parameters (dyn_string dsParameters, dyn_string &exceptionInfo)
_fwPeriphAddressS7_get (string dpe, dyn_anytype &addressConfig, bool &isActive, dyn_string &exceptionInfo)
_fwPeriphAddressS7_delete (string dpe, dyn_string &exceptionInfo)
_fwPeriphAddressS7_initPanel (string dpe, dyn_string &exceptionInfo)
string _fwPeriphAddressS7_setValuesFromRef (string reference, string sSystemName)
int _fwPeriphAddressS7_getTransfo ()
string _fwPeriphAddressS7_encodeAddress ()
int _fwPeriphAddressS7_getDir (int directionModeS7, int receiveMode)
_fwPeriphAddressS7_setIOMode (int io, int im, string sSystemName)
Variables
const string fwPeriphAddress_TYPE_S7 = "S7"
const unsigned fwPeriphAddress_S7_LOWLEVEL = 11
const unsigned fwPeriphAddress_S7_SUBINDEX = 12
const unsigned fwPeriphAddress_S7_START = 13
const unsigned fwPeriphAddress_S7_INTERVAL = 14
const unsigned fwPeriphAddress_S7_POLL_GROUP = 15
const string UN_S7_FORMAT_BIT = "DBX"
const string UN_S7_FORMAT_BYTE = "DBB"
const string UN_S7_FORMAT_WORD = "DBW"
const string UN_S7_FORMAT_DOUBLE = "DBD"
const unsigned UN_S7_ADDR_MODE_INOUT_TSPP = 6
const unsigned UN_S7_ADDR_MODE_INOUT_POLL = 7
const unsigned UN_S7_ADDR_MODE_INOUT_SQ = 8
const string S7_PLC_INT_DPTYPE_CONN = "_S7_Conn"
Detailed Description
This library contains function associated with S7 addressing. Functions are provided to set, get and delete the addressing for a dpe
Creation Date
24/04/2005
Modification History
13/09/2011 Marco Boccioli
#49981: Poll groups for S7 driver: inconsistency in poll group name. On fwPeriphAddressS7_set(), the leading "</em>" is now added automatically if not specified.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author
Enrique BLANCO (AB-CO)
Function Documentation
_fwPeriphAddressS7_delete (string dpe, dyn_string & exceptionInfo)
Delete the S7 addressing
Note: This function should not be called directly. Call the fwPeriphAddress_delete instead.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to configure
exceptionInfo output, details of any exceptions are returned here
string _fwPeriphAddressS7_encodeAddress ()
Encode the S7 address
Note: This function encodes the S7 address introduced by the user in several fields of the fwPeriphAddressS7.pnl
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Returns
correct address S7 type. i.e.: "DB100.DBX200.1"
Referenced by _fwPeriphAddressS7_setValuesFromRef().
_fwPeriphAddressS7_get (string dpe, dyn_anytype & addressConfig, bool & isActive, dyn_string & exceptionInfo)
Get the S7 addressing
Note: This function should not be called directly. Call the fwPeriphAddress_get instead.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to read
addressConfig output, object containing address configuration details
isActive output, TRUE is addressing is active, else FALSE
exceptionInfo output, details of any exceptions are returned here
int _fwPeriphAddressS7_getDir (int directionModeS7, int receiveMode)
Get the S7 IO mode
Note: This function gets the IO mode from the user selection in the _fwPeriphAddressS7.pnl. new constants are defined to the In/out modes
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
directionModeS7 input, direction mode (Output, Input, Input/Output)
receiveMode input, type mode (TSPP, Polling, Single Query)
int _fwPeriphAddressS7_getTransfo ()
Recuperate transformation type
Note: This function recuperates the selected trasnforamtion type selected by the user in several fields of the fwPeriphAddressS7.pnl
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Returns
output, transformation type: i.e.: "701 &ndash;> int 16"
_fwPeriphAddressS7_initPanel (string dpe, dyn_string & exceptionInfo)
Initialise the graphics of the address panel symbol.
Note: This function should only be called from fwPeriphAddres.pnl.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters
dpe input, data point element to configure
exceptionInfo output, details of any exceptions are returned here
References _fwPeriphAddressS7_setIOMode(), _fwPeriphAddressS7_setValuesFromRef(), and fwPeriphAddress_get().
_fwPeriphAddressS7_set (string dpe, dyn_anytype addressConfig, dyn_string & exceptionInfo)
Set the S7 addressing
Note: This function should not be called directly. Call the fwPeriphAddress_set instead.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to configure
addressConfig input, object containing address configuration details
exceptionInfo output, details of any exceptions are returned here
References fwPeriphAddress_checkS7Parameters().
_fwPeriphAddressS7_setIOMode (int io, int im, string sSystemName)
Set the S7 IO mode
Note: This function sets the IO mode from the user selection. There is the case "1" which is also used to set up the INPUT mode when user introduce an PLC peripherial INPUT from the address field.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
io input, direction mode (Output, Input, Input/Output)
im input, type mode (TSPP, Polling, Single Query)
sSystemName input, system name
!!pollgroup
Referenced by _fwPeriphAddressS7_initPanel(), and _fwPeriphAddressS7_setValuesFromRef().
string _fwPeriphAddressS7_setValuesFromRef (string reference, string sSystemName)
Set S7 panel values
Note: This function fills the panel fields in funciton of the REFERENCE selected by the user in several fields of the fwPeriphAddressS7.pnl
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
reference input, user introduced reference
sSystemName input, system name
Returns
output, encoded S7 address
References _fwPeriphAddressS7_encodeAddress(), and _fwPeriphAddressS7_setIOMode().
Referenced by _fwPeriphAddressS7_initPanel().
fwPeriphAddress_checkS7Parameters (dyn_string dsParameters, dyn_string & exceptionInfo)
Check if data is Ok to set a S7 address
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsParameters parameters used to set the _address config (see constants definition)
exceptionInfo for any error. If a parameter is incorrect, exceptionInfo is not empty !
Referenced by _fwPeriphAddressS7_set().