fwConfigs: fwPeriphAddressCMW.ctl File Reference
fwPeriphAddressCMW.ctl File Reference
Functions
_fwPeriphAddressCMW_set (string dpe, dyn_anytype addressConfig, dyn_string &exceptionInfo)
_fwPeriphAddressCMW_get (string dpe, dyn_anytype &addressConfig, bool &isActive, dyn_string &exceptionInfo)
_fwPeriphAddressCMW_delete (string dpe, dyn_string &exceptionInfo)
_fwPeriphAddressCMW_initPanel (string dpe, dyn_string &exceptionInfo)
fwPeriphAddressCMW_check (dyn_string dsParameters, dyn_string &exceptionInfo)
fwPeriphAddressCMW_getTransformation (int cmw_direction, int iCmw_trans, string dpe)
fwPeriphAddressCMW_setTransformation (int &cmw_direction, int &cmw_mode, int &cmw_trans, bool &cmw_lowlevel, string dpe)
_fwPeriphAddressCMW_setTransformation (bool bMonitorOn, int &cmw_direction, int &cmw_mode, int &cmw_trans, bool &cmw_lowlevel, string dpe)
Variables
const string fwPeriphAddress_TYPE_CMW = "CMW"
const int CMW_DEFAULT_DRIVER_NUMBER = 2
const string CMW_DEFAULT_REFERENCE = "reference$property$tag"
const bool CMW_DEFAULT_ACTIVE = TRUE
const int CMW_DEFAULT_SUBINDEX = 0
const bool CMW_DEFAULT_LOWLEVEL = FALSE
const int CMW_DEFAULT_DIRECTION = 0
const int CMW_DEFAULT_MODE = 0
const int CMW_NO_MONITORON = 1000
const int CMW_TRANS_OFFSET = 1000
const unsigned fwPeriphAddress_CMW_LOWLEVEL = 11
const unsigned fwPeriphAddress_CMW_SUBINDEX = 12
const unsigned fwPeriphAddress_CMW_START = 13
const unsigned fwPeriphAddress_CMW_INTERVAL = 14
const unsigned fwPeriphAddress_CMW_POLL_GROUP = 15
const unsigned fwPeriphAddress_CMW_MODE = 16
Detailed Description
This library contains function associated with CMW addressing. Functions are provided to set, get and delete the addressing for a dpe
Creation Date
25/04/2005
Modification History
28/05/2008: Herve
new function: _fwPeriphAddressCMW_setTransformation identical to fwPeriphAddressCMW_setTransformation without reference to a graphical element.
fwPeriphAddressCMW_setTransformation call _fwPeriphAddressCMW_setTransformation
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author
Celine VUILLERMOZ (AB-CO)
Function Documentation
_fwPeriphAddressCMW_delete (string dpe, dyn_string & exceptionInfo)
Delete the CMW addressing
Note: This function should not be called directly. Call the fwPeriphAddress_delete instead.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to configure
exceptionInfo output, details of any exceptions are returned here
_fwPeriphAddressCMW_get (string dpe, dyn_anytype & addressConfig, bool & isActive, dyn_string & exceptionInfo)
Get the CMW addressing
Note: This function should not be called directly. Call the fwPeriphAddress_get instead.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to read
addressConfig output, object containing address configuration details
isActive output, TRUE is addressing is active, else FALSE
exceptionInfo output, details of any exceptions are returned here
_fwPeriphAddressCMW_initPanel (string dpe, dyn_string & exceptionInfo)
Initialise the graphics of the address panel symbol.
Note: This function should only be called from fwPeriphAddres.pnl.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters
dpe input, data point element to configure
exceptionInfo output, details of any exceptions are returned here
References fwPeriphAddress_get(), and fwPeriphAddressCMW_getTransformation().
_fwPeriphAddressCMW_set (string dpe, dyn_anytype addressConfig, dyn_string & exceptionInfo)
Set the CMW addressing
Note: This function should not be called directly. Call the fwPeriphAddress_set instead.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to configure
addressConfig input, object containing address configuration details
exceptionInfo output, details of any exceptions are returned here
References fwPeriphAddressCMW_check().
_fwPeriphAddressCMW_setTransformation (bool bMonitorOn, int & cmw_direction, int & cmw_mode, int & cmw_trans, bool & cmw_lowlevel, string dpe)
Set the transformation of CMW address
Constraints
None
Usage
Internal function
PVSS managers
VISION, CTRL
Parameters
bMonitorOn input, true=monitorOn/false=no monitorOn
cmw_direction output, direction of the driver
cmw_mode output, Receive mode
cmw_trans output, driver type tranformation
cmw_lowlevel output, is the low level comparison set ?
dpe input, data point element to configure
Referenced by fwPeriphAddressCMW_setTransformation().
fwPeriphAddressCMW_check (dyn_string dsParameters, dyn_string & exceptionInfo)
Check if data is Ok to set a CMW address
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsParameters parameters used to set the _address config (see constants definition)
exceptionInfo for any error. If a parameter is incorrect, exceptionInfo is not empty !
Referenced by _fwPeriphAddressCMW_set().
fwPeriphAddressCMW_getTransformation (int cmw_direction, int iCmw_trans, string dpe)
Calculate the transformation of CMW address
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
cmw_direction input, value used to know the direction of the driver
iCmw_trans input, driver type tranformation
dpe input, data point element to configure
Referenced by _fwPeriphAddressCMW_initPanel().
fwPeriphAddressCMW_setTransformation (int & cmw_direction, int & cmw_mode, int & cmw_trans, bool & cmw_lowlevel, string dpe)
Set the transformation of CMW address
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
cmw_direction output, direction of the driver
cmw_mode output, Receive mode
cmw_trans output, driver type tranformation
cmw_lowlevel output, is the low level comparison set ?
dpe input, data point element to configure
References _fwPeriphAddressCMW_setTransformation().