fwColourTable.ctl File Reference
fwColourTable.ctl File Reference
Functions
fwColourTable_connectCellBackColToStatus (dyn_string &exceptionInfo)
_fwColourTable_calculateColourWithAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive, string dpe3, bool dataInvalid)
_fwColourTable_calculateColourWithoutAlertCB (string dpe1, bool dataInvalid)
fwColourTable_connectCellBackColToValueStatus (dyn_string &exceptionInfo)
_fwColourTable_calculateColourWithAlertCBValue (string dpe1, string alertColour, string dpe2, bool alarmActive, string dpe3, bool dataInvalid, string dpe4, string valText)
_fwColourTable_calculateColourWithoutAlertCBValue (string dpe1, bool dataInvalid, string dpe2, string valText)
_fwColourTable_calculateColourWithSummaryAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive)
Detailed Description
This library is used to convert the given states of a device into the colour which represents this state. Funcitons are also available for dpConnecting the colour of graphical elements to a device state.
Creation Date
23/01/01
Author
Herve Milcent (IT-CO) origin: COMPASS: Oliver Holme (IT-CO)
Function Documentation
_fwColourTable_calculateColourWithAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive, string dpe3, bool dataInvalid)
This functions takes the given states of a data point element and calls a function which calcultes the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
alertColour a string containing the name of the current alert colour
dpe2 data point element
alarmActive a bit to represent if alert handling is active or not (TRUE = active, FALSE = inactive)
dpe3 data point element
dataInvalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
References fwColour_convertStatusToColour().
_fwColourTable_calculateColourWithAlertCBValue (string dpe1, string alertColour, string dpe2, bool alarmActive, string dpe3, bool dataInvalid, string dpe4, string valText)
This functions takes the given states of a data point element and calls a function which calcultes the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
alertColour a string containing the name of the current alert colour
dpe2 data point element
alarmActive a bit to represent if alert handling is active or not (TRUE = active, FALSE = inactive)
dpe3 data point element
dataInvalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
dpe4 data point element with value to display in the cell
valText value to display in the cell
References fwColour_convertStatusToColour().
_fwColourTable_calculateColourWithoutAlertCB (string dpe1, bool dataInvalid)
This functions takes the given states of a data point element and calls a function which calcultes the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
dataInvalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
References fwColour_convertStatusToColour().
Referenced by fwColourTable_connectCellBackColToStatus(), and fwColourTable_connectCellBackColToValueStatus().
_fwColourTable_calculateColourWithoutAlertCBValue (string dpe1, bool dataInvalid, string dpe2, string valText)
This functions takes the given states of a data point element and calls a function which calcultes the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element with quality of the data
dataInvalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
dpe2 data point element with value to display in the cell
valText value to display in the cell
References fwColour_convertStatusToColour().
_fwColourTable_calculateColourWithSummaryAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive)
This functions takes the given states of a summary alert on a given data point element and calls a function which calculates the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
alertColour a string containing the name of the current alert colour
dpe2 data point element
alarmActive a bit to represent if alert handling is active or not (TRUE = active, FALSE = inactive)
References fwColour_convertStatusToColour().
fwColourTable_connectCellBackColToStatus (dyn_string & exceptionInfo)
This function controls the background colour of the cell of a table from within which the function was called. The colour is controlled by dpConnecting to the invalid bit of the given data point element, and if it exists, the alert active bit and the alert colour are also connected to. When the function is called, and any time when the alert state or invalid state changes, a function is called which evaluates the current state, selects the relevant colour and sets the background colour of the graphical item.
Modification History
29/03/01 Oliver Holme Added functionality for connecting to dpes of type STRUCTURE This makes it possible to connect to the state of a summary alert
Usage
Public
PVSS managers
VISION
Parameters
exceptionInfo details of any exceptions are placed in here
References _fwColourTable_calculateColourWithoutAlertCB(), and fwException_raise().
fwColourTable_connectCellBackColToValueStatus (dyn_string & exceptionInfo)
This function controls the background colour of the cell of a table from within which the function was called. The colour is controlled by dpConnecting to the invalid bit of the given data point element, and if it exists, the alert active bit and the alert colour are also connected to. When the function is called, and any time when the alert state or invalid state changes, a function is called which evaluates the current state, selects the relevant colour and sets the background colour of the graphical item.
Modification History
29/03/01 Oliver Holme Added functionality for connecting to dpes of type STRUCTURE This makes it possible to connect to the state of a summary alert
Constraints
Usage
Public
PVSS managers
VISION
Parameters
exceptionInfo details of any exceptions are placed in here.
References _fwColourTable_calculateColourWithoutAlertCB(), and fwException_raise().