fwColour.ctl File Reference
fwColour.ctl File Reference
Functions
fwColour_connectItemBackColToStatus (string dpe, dyn_string &exceptionInfo)
_fwCalculateColourWithAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive, string dpe3, bool dataInvalid)
_fwCalculateColourWithSummaryAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive)
_fwCalculateColourWithoutAlertCB (string dpe1, bool dataInvalid)
fwColour_convertStatusToColour (string &elementColour, string alertColour, bool masked, bool invalid, dyn_string &exceptionInfo)
Detailed Description
This library is used to convert the given states of a device into the colour which represents this state. Funcitons are also available for dpConnecting the colour of graphical elements to a device state.
Creation Date
23/01/01
Modification History
02/05/01 Oliver Holme - Added support for connecting to summary alerts Created new function _fwCalculateColourWithSummaryAlertCB()
Constraints
Author
Oliver Holme (IT-CO)
Function Documentation
_fwCalculateColourWithAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive, string dpe3, bool dataInvalid)
This functions takes the given states of a data point element and calls a function which calcultes the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
alertColour a string containing the name of the current alert colour
dpe2 data point element
alarmActive a bit to represent if alert handling is active or not (TRUE = active, FALSE = inactive)
dpe3 data point element
dataInvalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
References fwColour_convertStatusToColour().
_fwCalculateColourWithoutAlertCB (string dpe1, bool dataInvalid)
This functions takes the given states of a data point element and calls a function which calcultes the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
dataInvalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
References fwColour_convertStatusToColour().
_fwCalculateColourWithSummaryAlertCB (string dpe1, string alertColour, string dpe2, bool alarmActive)
This functions takes the given state of a summary alert and calls a function which calculates the relevant colour. The function then set the background colour of graphical item "this" to that colour.
Constraints
This function is designed as a 'work' function and should only be used by giving it as the function name in a dpConnect statement
Usage
Private
PVSS managers
VISION
Parameters
dpe1 data point element
alertColour a string containing the name of the current alert colour
dpe2 data point element
alarmActive a bit to represent if alert handling is active or not (TRUE = active, FALSE = inactive)
References fwColour_convertStatusToColour().
fwColour_connectItemBackColToStatus (string dpe, dyn_string & exceptionInfo)
This function controls the background colour of the item from within which the function was called. The colour is controlled by dpConnecting to the invalid bit of the given data point element, and if it exists, the alert active bit and the alert colour are also connected to. When the function is called, and any time when the alert state or invalid state changes, a function is called which evaluates the current state, selects the relevant colour and sets the background colour of the graphical item.
Modification History
02/05/01 Oliver Holme - Added support for connecting to summary alerts If a summary alert exists, the _fwCalculateColourWithSummaryAlertCB is connected to. If no alert exists on a dpe of type structure, the OK colour is shown.
Constraints
This function can only be called from within a graphical interface
Usage
Public
PVSS managers
VISION
Parameters
dpe data point element
exceptionInfo details of any exceptions are placed in here.
References fwException_raise().
fwColour_convertStatusToColour (string & elementColour, string alertColour, bool masked, bool invalid, dyn_string & exceptionInfo)
This functions takes the given states of a data point element and calculates the appropriate colour which summarises its status.
Constraints
None
Usage
Private
PVSS managers
VISION
Parameters
elementColour the calculated status colour is returned here.
alertColour a string containing the name of the current alert colour
masked a bit to represent if alert is maksed or not (TRUE = masked, FALSE = unmasked)
invalid a bit to represent if data is invalid or not (TRUE = invalid, FALSE = valid)
exceptionInfo details of any exceptions are placed in here.
Referenced by _fwCalculateColourWithAlertCB(), _fwCalculateColourWithoutAlertCB(), _fwCalculateColourWithSummaryAlertCB(), _fwColourTable_calculateColourWithAlertCB(), _fwColourTable_calculateColourWithAlertCBValue(), _fwColourTable_calculateColourWithoutAlertCB(), _fwColourTable_calculateColourWithoutAlertCBValue(), and _fwColourTable_calculateColourWithSummaryAlertCB().