fwException.ctl File Reference
fwException.ctl File Reference
Functions
fwException_raise (dyn_string &exceptionInfo, string exceptionType, string exceptionText, string exceptionCode)
_fwException_initialise ()
_fwException_writeToPvssLog (dyn_string &exceptionInfo)
Variables
const string fwException_SETTINGS_DP = "_fwException"
Detailed Description
A library including the necessary functions to raise exceptions
Creation Date
4/12/00
Author
JCOP Framework Team
Function Documentation
fwException_raise (dyn_string & exceptionInfo, string exceptionType, string exceptionText, string exceptionCode)
Add the exception to the PVSS log in the form
    [exceptionType][exceptionText][Code: exceptionCode]
Also the exception details are appended to the dyn_string which is passed to the function
Three strings are appended to the dyn_string, firstly the exceptionType then the exceptionText
and finally a code which is associated with the exception (exceptionCode)
Usage
Public
PVSS managers
VISION, CTRL
Parameters
exceptionInfo details of exceptions are returned here
exceptionType type of exception
exceptionText text associated with exception
exceptionCode a code associated with the exception
Referenced by fwColour_connectItemBackColToStatus(), fwColourTable_connectCellBackColToStatus(), fwColourTable_connectCellBackColToValueStatus(), fwGeneral_getDpElements(), and fwGeneral_getSystemIpAddress().