DROP PACKAGE fwConfigurationDB;
DROP VIEW  v_recipesAll CASCADE CONSTRAINTS;
DROP TABLE recipe_tags CASCADE CONSTRAINTS;
DROP TABLE recipe_data CASCADE CONSTRAINTS;
DROP TABLE recipe_versions CASCADE CONSTRAINTS;
DROP TABLE recipes CASCADE CONSTRAINTS;
DROP TABLE references CASCADE CONSTRAINTS;

DROP TABLE tmp_item_props;
DROP TABLE CDB_API_PARAMS;

DROP VIEW V_REFERENCES;
DROP VIEW V_CONFIG_ITEMS;
DROP VIEW V_CONFIG_ALERTS;
DROP VIEW V_DEVICE_CONFIGS;
DROP VIEW V_DEVICE_CONFIGS_ALL;
DROP VIEW V_ITEM_PROPERTIES;
DROP VIEW V_ITEM_NAMES;
DROP VIEW V_ITEMS;

DROP TABLE CONFIG_GENERAL CASCADE CONSTRAINTS;
DROP TABLE CONFIG_UF CASCADE CONSTRAINTS;
DROP TABLE CONFIG_SMOOTHING CASCADE CONSTRAINTS;
DROP TABLE CONFIG_PVRANGES CASCADE CONSTRAINTS;
DROP TABLE CONFIG_CONVERSIONS CASCADE CONSTRAINTS;
DROP TABLE CONFIG_DPFUNCTIONS CASCADE CONSTRAINTS;
DROP TABLE CONFIG_ARCHIVING CASCADE CONSTRAINTS;
DROP TABLE CONFIG_ADDRESSES CASCADE CONSTRAINTS;
DROP TABLE CONFIG_SUMALERTS CASCADE CONSTRAINTS;
DROP TABLE CONFIG_DPEALERTS CASCADE CONSTRAINTS;
DROP TABLE CONFIG_ALERTS_MISC CASCADE CONSTRAINTS;
DROP TABLE CONFIG_ALERTS CASCADE CONSTRAINTS;
DROP TABLE CONFIG_DESC CASCADE CONSTRAINTS;
DROP TABLE CONFIG_TAGS CASCADE CONSTRAINTS;
DROP TABLE CONFIG_ITEM_PROPERTIES CASCADE CONSTRAINTS;
DROP TABLE CONFIG_ITEMS CASCADE CONSTRAINTS;
DROP TABLE DEVICE_TYPES CASCADE CONSTRAINTS;
DROP TABLE DEVICE_ELEMENTS CASCADE CONSTRAINTS;

DROP SEQUENCE CONF_ID_SEQ;
DROP SEQUENCE CITEM_ID_SEQ;
DROP SEQUENCE DEVELEM_ID_SEQ;
DROP SEQUENCE DPT_ID_SEQ;
DROP SEQUENCE IPROP_ID_SEQ;
DROP SEQUENCE items_id_seq;
DROP SEQUENCE RECIPES_RVER_SEQ;
DROP SEQUENCE RECIPES_TAGID_SEQ;
DROP SEQUENCE recipe_data_propid_seq;

DROP TABLE items CASCADE CONSTRAINTS;
DROP TABLE hierarchies CASCADE CONSTRAINTS;
DROP VIEW  v_confdb CASCADE CONSTRAINTS;
