main()
{
int stop = 1;
string status, action;

	if(dpExists("ToDo.action"))
	{
		dpSet("ToDo.action","Installing");
		dpGet("ToDo.status",status);
		if(status == "Installing")
			stop = 0;
	}
	if(stop)
	{
		fwInstallation_stopManagers(makeDynString("PVSS00dim"));
		DebugTN("fwDIM.init: Stopping PVSS00dim Managers");
	}
	else
	{
		DebugTN("fwDIM.init: PVSS00dim Managers already Stopped");
	}
}
