main()
{
int stop = 1;
string status, action;

	if(dpExists("ToDo.action"))
	{
		dpSet("ToDo.action","Installing");
		dpGet("ToDo.status",status);
		if(status == "Installing")
			stop = 0;
	}
	if(stop)
	{
		//fwInstallation_stopManagers(makeDynString("PVSS00dim"));
    fwInstallationManager_stopAllOfTypes(makeDynString("WCCOAdim"));
		DebugTN("fwDIM.init: Stopping WCCOAdim Managers");
	}
	else
	{
		DebugTN("fwDIM.init: WCCOAdim Managers already Stopped");
	}
}
