fwAlarmHandling.ctl File Reference
fwAlarmHandling.ctl File Reference
Functions
fwAlarmHandling_setCustomHelpFile (string dpe, string helpFilePath, dyn_string &exceptionInfo)
fwAlarmHandling_setMultipleCustomHelpFile (dyn_string dpes, string helpFilePath, dyn_string &exceptionInfo)
fwAlarmHandling_setManyCustomHelpFile (dyn_string dpes, dyn_string helpFilePaths, dyn_string &exceptionInfo)
fwAlarmHandling_deleteCustomHelpFile (string dpe, dyn_string &exceptionInfo)
fwAlarmHandling_deleteMultipleCustomHelpFile (dyn_string dpes, dyn_string &exceptionInfo)
fwAlarmHandling_deleteManyCustomHelpFile (dyn_string dpes, dyn_string &exceptionInfo)
bool fwAlarmHandling_getCustomHelpFile (string dpe, string &helpFilePath, dyn_string &exceptionInfo)
dyn_bool fwAlarmHandling_getManyCustomHelpFile (dyn_string dpes, dyn_string &helpFilePaths, dyn_string &exceptionInfo)
fwAlarmHandling_openHelpFile (string fileName, dyn_string &exceptionInfo)
_fwAlarmHandling_convertDpNameToFileName (string dpName, string &fileName, dyn_string &exceptionInfo)
fwAlarmHandling_findHelpFile (string dpe, string &fileName, dyn_string &exceptionInfo)
fwAlarmHandling_getDpsMatchingCriteria (dyn_string systemNameFilters, dyn_string dpNameFilters, dyn_string dpAliasFilters, dyn_string dpTypeFilters, dyn_string &matchingDps, dyn_string &exceptionInfo)
fwAlarmHandling_openScreen (bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string &exceptionInfo, unsigned x=0, unsigned y=0)
fwAlarmHandling_openScreenWithDpeList (dyn_string dpeList, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string &exceptionInfo, unsigned x=0, unsigned y=0)
fwAlarmHandling_openScreenWithSavedFilter (string filterName, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string &exceptionInfo, unsigned x=0, unsigned y=0)
fwAlarmHandling_openScreenWithFilter (dyn_dyn_anytype filter, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string &exceptionInfo, unsigned x=0, unsigned y=0, string sFilterName="")
fwAlarmHandling_getHelpFileFormats (dyn_string &fileExtensions, dyn_string &windowsCommand, dyn_string &linuxCommand, dyn_string &exceptionInfo)
fwAlarmHandling_setHelpFileFormats (dyn_string fileExtensions, dyn_string windowsCommand, dyn_string linuxCommand, dyn_string &exceptionInfo)
_fwAlarmHandling_createPlotDp (string plotName)
Variables
const int fwAlarmHandling_HELP_DEVICE_ELEMENT = 1
const int fwAlarmHandling_HELP_DEVICE = 2
const int fwAlarmHandling_HELP_DEVICE_TYPE_ELEMENT = 3
const int fwAlarmHandling_HELP_DEVICE_TYPE = 4
const int fwAlarmHandling_HELP_DEFAULT = 5
const string fwAlarmHandling_HELP_PATH_ROOT = "AlarmHelp/"
const string fwAlarmHandling_HELP_PATH_DEVICE_DESCRIPTION_ELEMENT = "DeviceDescriptionDPE/"
const string fwAlarmHandling_HELP_PATH_DEVICE_DESCRIPTION = "DeviceDescription/"
const string fwAlarmHandling_HELP_PATH_DEVICE_ALIAS_ELEMENT = "DeviceDescriptionDPE/"
const string fwAlarmHandling_HELP_PATH_DEVICE_ALIAS = "DeviceDescription/"
const string fwAlarmHandling_HELP_PATH_DEVICE_ELEMENT = "DeviceDPE/"
const string fwAlarmHandling_HELP_PATH_DEVICE = "Device/"
const string fwAlarmHandling_HELP_PATH_DEVICE_TYPE_ELEMENT = "DeviceTypeDPE/"
const string fwAlarmHandling_HELP_PATH_DEVICE_TYPE = "DeviceType/"
const string fwAlarmHandling_HELP_FILE_DEFAULT = "fwAlarmHandlingDefault.xml"
const string fwAlarmHandling_HELP_FORMAT_EXTENSIONS = "_FwAlarmHelpSettings.fileExtensions"
const string fwAlarmHandling_HELP_FORMAT_COMMANDS_WINDOWS = "_FwAlarmHelpSettings.openCommand.windows"
const string fwAlarmHandling_HELP_FORMAT_COMMANDS_LINUX = "_FwAlarmHelpSettings.openCommand.linux"
const string fwAlarmHandling_HELP_LOADER_PANEL = "fwAlarmHandling/fwAlarmHandlingHelpLoader.pnl"
const string fwAlarmHandling_HELP_PATH_ATTRIBUTE = ".._string_05"
Detailed Description
This library contains functions for handling JCOP framework alarms. There are functions for filtering data points which have alarms as well as functions to open the JCOP Alarm Screen
Creation Date
02/02/2006
Modification History
29/06/2011 Marco Boccioli
ENS-3073 (Alarm Screen with predefined quick filter): added new parameters, $iLocalOrGlobal, $sFilterName , new optional variable filterName in fwAlarmHandling_openScreenWithFilter() 2011-07-05 Marco Boccioli
#84051 (Sometimes, the alias name in the filter makes the AS crash): modified function: fwAlarmHandling_getDpsMatchingCriteria(). It checks now if the sys name is already specified in the dpe list, before adding it.
#83995 (Error when filtering with multiple device name including sys name): modified function: fwAlarmHandling_getDpsMatchingCriteria(). Removed the dynIntersect call.
Constraints
Usage
Public
PVSS managers
VISION, CTRL
Author:
Oliver Holme (IT-CO)
Function Documentation
fwAlarmHandling_getDpsMatchingCriteria (dyn_string systemNameFilters, dyn_string dpNameFilters, dyn_string dpAliasFilters, dyn_string dpTypeFilters, dyn_string & matchingDps, dyn_string & exceptionInfo)
Returns a list of data points that match the given criteria. The result returned is as follows: result = ((dps that meet ALL DP name filter) && (dps that meet ALL DP alias filters)) of ANY specified type, on ANY specified system
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
systemNameFilters A list of systems to search in. The criteria are OR'ed
dpNameFilters A list of criteria to filter on the dp name. The criteria are AND'ed.
dpAliasFilters A list of criteria to filter on the dp alias. The criteria are AND'ed.
dpTypeFilters A list of data point types to search. The criteria are ORed.
matchingDps The list of matching dps is returned here.
exceptionInfo Details of any exceptions are returned here
Referenced by fwAlarmHandlingScreen_evaluateDpFilter().
fwAlarmHandling_openScreen (bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string & exceptionInfo, unsigned x = 0, unsigned y = 0)
Opens a JCOP Alarm Screen with the default filter - filter shows ALL alarms in ALL systems.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
bAsNewModule input, should the display be opened in a new module, TRUE = new module, FALSE = child panel
bStayOnTopOrModal input, for a new module - TRUE = stay on top, FALSE = normal behaviour for a child panel - TRUE = modal child panel, FALSE = normal behaviour
sModuleName input, the name of the new module (if required)
sPanelName input, the name of the new panel
exceptionInfo Details of any exceptions are returned here
x input, Optional parameter - default value 0. X position of the new display
y input, Optional parameter - default value 0. Y position of the new display
References _fwAlarmHandlingScreen_getDefaultFilter(), and fwAlarmHandling_openScreenWithFilter().
fwAlarmHandling_openScreenWithDpeList (dyn_string dpeList, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string & exceptionInfo, unsigned x = 0, unsigned y = 0)
Opens a JCOP Alarm Screen to monitor a specific list of DPEs.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpeList input, the list of data points or data point elements that the alarm screen should monitor and display
bAsNewModule input, should the display be opened in a new module, TRUE = new module, FALSE = child panel
bStayOnTopOrModal input, for a new module - TRUE = stay on top, FALSE = normal behaviour for a child panel - TRUE = modal child panel, FALSE = normal behaviour
sModuleName input, the name of the new module (if required)
sPanelName input, the name of the new panel
exceptionInfo Details of any exceptions are returned here
x input, Optional parameter - default value 0. X position of the new display
y input, Optional parameter - default value 0. Y position of the new display
References _fwAlarmHandlingScreen_getDefaultFilter(), and fwAlarmHandling_openScreenWithFilter().
fwAlarmHandling_openScreenWithFilter (dyn_dyn_anytype filter, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string & exceptionInfo, unsigned x = 0, unsigned y = 0, string sFilterName = "")
Opens a JCOP Alarm Screen with the specified custom filter.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
filter input, the filter shoule be passed here, check the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants that define the filter object
bAsNewModule input, should the display be opened in a new module, TRUE = new module, FALSE = child panel
bStayOnTopOrModal input, for a new module - TRUE = stay on top, FALSE = normal behaviour for a child panel - TRUE = modal child panel, FALSE = normal behaviour
sModuleName input, the name of the new module (if required)
sPanelName input, the name of the new panel
exceptionInfo Details of any exceptions are returned here
x input, Optional parameter - default value 0. X position of the new display
y input, Optional parameter - default value 0. Y position of the new display
sFilterName input, Optional parameter - default value "". Filter name to be shown on the Quick Filters box
Referenced by fwAlarmHandling_openScreen(), fwAlarmHandling_openScreenWithDpeList(), and fwAlarmHandling_openScreenWithSavedFilter().
fwAlarmHandling_openScreenWithSavedFilter (string filterName, bool bAsNewModule, bool bStayOnTopOrModal, string sModuleName, string sPanelName, dyn_string & exceptionInfo, unsigned x = 0, unsigned y = 0)
Opens a JCOP Alarm Screen with the specified pre-saved filter.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
filterName input, the name of the pre-saved filter that should be loaded and displayed
bAsNewModule input, should the display be opened in a new module, TRUE = new module, FALSE = child panel
bStayOnTopOrModal input, for a new module - TRUE = stay on top, FALSE = normal behaviour for a child panel - TRUE = modal child panel, FALSE = normal behaviour
sModuleName input, the name of the new module (if required)
sPanelName input, the name of the new panel
exceptionInfo Details of any exceptions are returned here
x input, Optional parameter - default value 0. X position of the new display
y input, Optional parameter - default value 0. Y position of the new display
References fwAlarmHandling_openScreenWithFilter(), and fwAlarmHandlingScreen_loadFilter().