CREATE OR REPLACE VIEW fw_sys_stat_schema (version) AS
	SELECT '4.1.1'
	FROM dual;


ALTER TABLE FW_SYS_STAT_COMPUTER
ADD (FMC_ENABLE_ALARMS NUMBER,
	 FMC_ENABLE_ARCHIVING VARCHAR2(64));

ALTER TABLE FW_SYS_STAT_PVSS_PROJECT
ADD UPGRADE VARCHAR(16);
