--System Configuration DB Update patch v2.0.6
-- Changes w.r.t. v 2.0.5
-- 1.- Add fields to the FW_SYS_STAT_COMPUTER table to for the FMC configuration case.

--Update schema version
CREATE OR REPLACE VIEW fw_sys_stat_schema (version) AS
	SELECT '2.0.6'
	FROM dual;

ALTER TABLE FW_SYS_STAT_COMPUTER
ADD(ENABLE_IPMI NUMBER DEFAULT 0,
	IPMI_DEVICE_NAME VARCHAR(128),
	ENABLE_MONITORING NUMBER DEFAULT 0,
	MONITORING_LEVEL NUMBER DEFAULT 0,
	ENABLE_TM NUMBER DEFAULT 0,
	ENABLE_LOGGER NUMBER DEFAULT 0);
	
--DECLARE
--	NEW_HOSTNAME FW_SYS_STAT_COMPUTER.HOSTNAME%TYPE;
--BEGIN
--   	FOR REC IN (SELECT ID, HOSTNAME FROM FW_SYS_STAT_COMPUTER) LOOP
--   		NEW_HOSTNAME := UPPER (REC.HOSTNAME);
--   		UPDATE FW_SYS_STAT_COMPUTER SET HOSTNAME = NEW_HOSTNAME --WHERE ID = REC.ID;
--   	END LOOP;
--END;	
--/
--
--COMMIT;
