fwConfigs: fwDpFunction.ctl File Reference
fwDpFunction.ctl File Reference
fwDpFunction DPE Connection | fwDpFunction Statistical | fwDpFunction common functions and variables
Functions
Utility functions
Used to access the configuration object attributes (object of type dyn_anytype).
fwDpFunction_getDpeConnection (string dpe, bool &configExists, dyn_string &functionParams, dyn_string &functionGlobals, string &functionDefinition, dyn_string &exceptionInfo)
fwDpFunction_getDpeConnectionMany (dyn_string dpes, dyn_bool &configExists, dyn_dyn_string &functionParams, dyn_dyn_string &functionGlobals, dyn_string &functionDefinition, dyn_string &exceptionInfo)
fwDpFunction_setDpeConnectionMultiple (dyn_string dpes, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string &exceptionInfo, bool runChecks=TRUE)
fwDpFunction_setDpeConnectionMany (dyn_string dpes, dyn_dyn_string functionParams, dyn_dyn_string functionGlobals, dyn_string functionDefinition, dyn_string &exceptionInfo, bool runChecks=TRUE)
fwDpFunction_setDpeConnection (string dpe, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string &exceptionInfo, bool runChecks=TRUE)
_fwDpFunction_prepareSet (string dpe, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string &attributes, dyn_anytype &values, dyn_string &exceptionInfo, bool runChecks=TRUE, int functionType=DPCONFIG_DP_FUNCTION, dyn_int statTypes=makeDynInt(), int intervalS=-1, int delayS=-1, bool readArchive=false)
_fwDpFunction_checkFunction (string function, dyn_string parameters, dyn_string globals, bool &isOk, dyn_string &exceptionInfo)
fwDpFunction_objectCreateStatistical (dyn_mixed &functionObject, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_int statTypes, int intervalS, int delayS, bool readArchive, dyn_string &exceptionInfo, bool runChecks=true)
fwDpFunction_objectCreateDpeConnection (dyn_mixed &functionObject, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string &exceptionInfo, bool runChecks=true)
fwDpFunction_objectExtractStatistical (dyn_mixed functionObject, dyn_string &functionParams, dyn_string &functionGlobals, string &functionDefinition, dyn_int &statTypes, int &intervalS, int &delayS, bool &readArchive, dyn_string &exceptionInfo)
fwDpFunction_objectExtractDpeConnection (dyn_mixed functionObject, dyn_string &functionParams, dyn_string &functionGlobals, string &functionDefinition, dyn_string &exceptionInfo)
fwDpFunction_objectInitialize (dyn_mixed &functionObject)
int fwDpFunction_objectExtractType (dyn_mixed functionObject)
bool fwDpFunction_objectIsStatistical (dyn_mixed functionObject)
bool fwDpFunction_objectIsDpeConnection (dyn_mixed functionObject)
Set/Get functions
Used to set/get the dp function settings to/from the dpe. The settings are stored into the settings object.
fwDpFunction_deleteMultiple (dyn_string dpes, dyn_string &exceptionInfo)
fwDpFunction_deleteMany (dyn_string dpes, dyn_string &exceptionInfo)
fwDpFunction_delete (string dpe, dyn_string &exceptionInfo)
fwDpFunction_objectSet (string dpe, dyn_mixed functionObject, dyn_string &exceptionInfo, bool runChecks=TRUE)
fwDpFunction_objectSetMany (dyn_string &dpes, dyn_mixed &functionObjects, dyn_string &exceptionInfo, bool runChecks=TRUE)
fwDpFunction_objectGet (string dpe, bool &configExists, dyn_mixed &functionObject, dyn_string &exceptionInfo)
fwDpFunction_objectGetMany (dyn_string &dpes, dyn_bool &configExists, dyn_mixed &functionObjects, dyn_string &exceptionInfo)
Variables
Configuration object indexes
Used to access the configuration object attributes (object of type dyn_anytype).
const int fwDpFunction_OBJ_FUNCTION = 5
const int fwDpFunction_OBJ_PARAM = 6
const int fwDpFunction_OBJ_GLOBAL = 7
const int fwDpFunction_OBJ_TYPE = 8
const int fwDpFunction_OBJ_STAT_TYPE = 9
const int fwDpFunction_OBJ_STAT_INTERVAL = 10
const int fwDpFunction_OBJ_STAT_DELAY = 11
const int fwDpFunction_OBJ_STAT_READ_ARCHIVE = 12
Detailed Description
This library contains function associated the dp function config. Functions are provided for getting the current settings, deleting the config and setting the config.
Creation Date
    29/01/2004
Modification History
22/08/2011 Marco Boccioli
#85462: Functions *Many() with parameters as reference. This improves the performances (less memory consumption).
#85880: Improved performance for fwDpFunction_objectGetMany(). New function written, with identical signature. The old function is commented out.
23/06/2011 Marco Boccioli
ENS-3098: Improve performance in setting dpFunctions.
ENS-3174: Support for statistical dpFunctions. Added new functions: fwDpFunction_objectCreateDpeConnection() fwDpFunction_objectCreateStatistical() fwDpFunction_objectExtractDpeConnection() fwDpFunction_objectExtractStatistical() fwDpFunction_objectExtractType() fwDpFunction_objectGet() fwDpFunction_objectGetMany() fwDpFunction_objectInitialize() fwDpFunction_objectSet() fwDpFunction_objectSetMany() fwDpFunction_objectIsDpeConnection() fwDpFunction_objectIsStatistical() fwDpFunction_objectExtractType() Added documentation to new functions. Modified internal function signature: _fwDpFunction_prepareSet(): added new optional parameters. For an example on how to use the new functions, see fwDpFunction_objectSetMany().
Constraints
Functions are currently designed to work with dp function of type dpe connection and statistical. The statistical functions support a limited set of parameters (see Variables Documentation).
Usage
Public
PVSS managers
VISION, CTRL
Author
Geraldine Thomas, Oliver Holme (IT-CO)
Function Documentation
_fwDpFunction_checkFunction (string function, dyn_string parameters, dyn_string globals, bool & isOk, dyn_string & exceptionInfo)
This function is used to check that the given dp function only uses variables and globals that have been defined in the lists of available parameters and globals that are provided. This function is copied from para.ctl - paDpSetDpFct()
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
function the dp function to check
parameters the list of available function parameters
globals the list of available function globals
isOk Output - The value is set to TRUE if all the parameters and globals specified in the function are available in the parameter and globals lists. Else the value is set to FALSE.
exceptionInfo details of any errors are returned here
Referenced by _fwDpFunction_prepareSet().
_fwDpFunction_prepareSet (string dpe, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string & attributes, dyn_anytype & values, dyn_string & exceptionInfo, bool runChecks = TRUE, int functionType = DPCONFIG_DP_FUNCTION, dyn_int statTypes = makeDynInt(), int intervalS = -1, int delayS = -1, bool readArchive = false)
Prepares a list of attributes and a list of values to be used in a dpSetWait() call to set the config for the given dpe.
Constraints
This function is designed to work only with the dpe connection type of dp function. It does not support the statistical functions of the dp function config.
Usage
Internal
PVSS managers
VISION, CTRL
Parameters
dpe The data point element
functionParams The list of dp elements to be used as parameters in the dp function
functionGlobals The list of dp elements to be used as globals in the dp function
functionDefinition The dp function is given here (in terms of p's (parameters) and g's (globals))
attributes Output - the list of attributes that need to be set is returned here
values Output - the list of values that need to be set is returned here
exceptionInfo Details of any exceptions are returned here
runChecks Optional parameter - default TRUE TRUE: Run consistency checks on the input to the function (HIGHLY RECOMMENDED) FALSE: Do not run any checks at all - can result in badly configured or non configured dp functions. Use only for performance reasons.
functionType Type of dp function (DPCONFIG_DP_FUNCTION or DPCONFIG_STAT_FUNCTION).
statTypes Type of stat function (i.e. min, max... see full list on PVSS help, "_dp_fct.._stat_type"). One per parameter. The # of elements must be = to the # of elements in fwDpFunction_OBJ_PARAM.
intervalS Time interval of stat function, in seconds
delayS Time delay of stat function, in seconds
readArchive Read values from archive starting the stat function
References _fwDpFunction_checkFunction().
Referenced by fwDpFunction_setDpeConnectionMany().
fwDpFunction_getDpeConnection (string dpe, bool & configExists, dyn_string & functionParams, dyn_string & functionGlobals, string & functionDefinition, dyn_string & exceptionInfo)
Gets the current configuration of the dp function on the given dp element.
Deprecated:
This function is deprecated. Use fwDpFunction_objectGet() instead.
Constraints
This function is designed to work only with the dpe connection type of dp function. It does not support the statistical functions of the dp function config.
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe The data point element to query
configExists TRUE if dp function config exists, else FALSE
functionParams The list of dp elements used as parameters in the dp function
functionGlobals The list of dp elements used as globals in the dp function
functionDefinition The dp function is returned here (in terms of p's (parameters) and g's (globals))
exceptionInfo Details of any exceptions are returned here
Referenced by fwDpFunction_getDpeConnectionMany().
fwDpFunction_getDpeConnectionMany (dyn_string dpes, dyn_bool & configExists, dyn_dyn_string & functionParams, dyn_dyn_string & functionGlobals, dyn_string & functionDefinition, dyn_string & exceptionInfo)
Gets the current configuration of the dp function on the given list of dp elements.
Deprecated:
This function is deprecated. Use fwDpFunction_objectGetMany() instead.
Constraints
This function is designed to work only with the dpe connection type of dp function. It does not support the statistical functions of the dp function config.
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes The list of data point elements to query
configExists TRUE if dp function config exists, else FALSE
functionParams The list of dp elements used as parameters in the dp function
functionGlobals The list of dp elements used as globals in the dp function
functionDefinition The dp function is returned here (in terms of p's (parameters) and g's (globals))
exceptionInfo Details of any exceptions are returned here
References fwDpFunction_getDpeConnection().
fwDpFunction_setDpeConnection (string dpe, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string & exceptionInfo, bool runChecks = TRUE)
Configures the dp function on the given dp element.
Deprecated:
This function is deprecated. Use fwDpFunction_objectSet() instead.
Constraints
This function is designed to work only with the dpe connection type of dp function. It does not support the statistical functions of the dp function config.
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe The data point element
functionParams The list of dp elements to be used as parameters in the dp function
functionGlobals The list of dp elements to be used as globals in the dp function
functionDefinition The dp function is given here (in terms of p's (parameters) and g's (globals))
exceptionInfo Details of any exceptions are returned here
runChecks Optional parameter - default TRUE TRUE: Run consistency checks on the input to the function (HIGHLY RECOMMENDED) FALSE: Do not run any checks at all - can result in badly configured or non configured dp functions. Use only for performance reasons.
References fwDpFunction_setDpeConnectionMany().
fwDpFunction_setDpeConnectionMany (dyn_string dpes, dyn_dyn_string functionParams, dyn_dyn_string functionGlobals, dyn_string functionDefinition, dyn_string & exceptionInfo, bool runChecks = TRUE)
Configures the dp function on the given dp elements.
Deprecated:
This function is deprecated. Use fwDpFunction_objectSetMany() instead.
Constraints
This function is designed to work only with the dpe connection type of dp function. It does not support the statistical functions of the dp function config.
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes The list of data point elements
functionParams The list of dp elements to be used as parameters in the dp function
functionGlobals The list of dp elements to be used as globals in the dp function
functionDefinition The dp function is given here (in terms of p's (parameters) and g's (globals))
exceptionInfo Details of any exceptions are returned here
runChecks Optional parameter - default TRUE TRUE: Run consistency checks on the input to the function (HIGHLY RECOMMENDED) FALSE: Do not run any checks at all - can result in badly configured or non configured dp functions. Use only for performance reasons.
References _fwDpFunction_prepareSet().
Referenced by fwDpFunction_setDpeConnection(), and fwDpFunction_setDpeConnectionMultiple().
fwDpFunction_setDpeConnectionMultiple (dyn_string dpes, dyn_string functionParams, dyn_string functionGlobals, string functionDefinition, dyn_string & exceptionInfo, bool runChecks = TRUE)
Configures the dp function on the given dp elements.
Deprecated:
This function is deprecated. Use fwDpFunction_objectSetMany() instead, passing an array of settings objects containing only one settings object.
Constraints
This function is designed to work only with the dpe connection type of dp function. It does not support the statistical functions of the dp function config.
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpes The list of data point elements
functionParams The list of dp elements to be used as parameters in the dp function
functionGlobals The list of dp elements to be used as globals in the dp function
functionDefinition The dp function is given here (in terms of p's (parameters) and g's (globals))
exceptionInfo Details of any exceptions are returned here
runChecks Optional parameter - default TRUE TRUE: Run consistency checks on the input to the function (HIGHLY RECOMMENDED) FALSE: Do not run any checks at all - can result in badly configured or non configured dp functions. Use only for performance reasons.
References fwDpFunction_setDpeConnectionMany().