fwConfigs: fwUnit.ctl File Reference
fwUnit.ctl File Reference
Functions
fwUnit_set (string dpe, string sUnit, dyn_string &exceptionInfo)
fwUnit_setMultiple (dyn_string dsDpe, string sUnit, dyn_string &exceptionInfo)
fwUnit_setMany (dyn_string &dsDpe, dyn_string &dsUnit, dyn_string &exceptionInfo)
fwUnit_get (string dpe, bool &bUnitExists, string &sUnit, dyn_string &exceptionInfo)
fwUnit_getMany (dyn_string &dsDpe, dyn_bool &dbUnitExists, dyn_string &dsUnit, dyn_string &exceptionInfo)
fwUnit_delete (string dpe, dyn_string &exceptionInfo)
fwUnit_deleteMultiple (dyn_string dsDpe, dyn_string &exceptionInfo)
fwUnit_deleteMany (dyn_string dsDpe, dyn_string &exceptionInfo)
fwUnit_getMultiple (dyn_string dsDpe, dyn_bool &dbUnitExists, dyn_string &dsUnit, dyn_string &exceptionInfo)
Detailed Description
This library contains function associated with the Unit part of the common config. Functions allows to set, get and delete the unit of a dpe or multiple dpes
Creation Date
29/01/2004
Modification History
12/08/11 Marco Boccioli
#85462: Functions *_setMany and *_getMany with parameters as reference.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author
Geraldine Thomas, Oliver Holme (IT-CO)
Function Documentation
fwUnit_delete (string dpe, dyn_string & exceptionInfo)
Delete the Unit of the dpe.  The unit string is reset to ""
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe data point element to configure
exceptionInfo output, details of any exceptions are returned here
Referenced by fwUnit_deleteMany().
fwUnit_deleteMany (dyn_string dsDpe, dyn_string & exceptionInfo)
Delete the Unit of several dpes.  The unit string is reset to ""
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsDpe input, data point elements to configure
exceptionInfo output, details of any exceptions are returned here
References fwUnit_delete().
Referenced by fwUnit_deleteMultiple().
fwUnit_deleteMultiple (dyn_string dsDpe, dyn_string & exceptionInfo)
Delete the Unit of several dpes.  The unit string is reset to ""
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsDpe input, data point elements to configure
exceptionInfo output, details of any exceptions are returned here
References fwUnit_deleteMany().
fwUnit_get (string dpe, bool & bUnitExists, string & sUnit, dyn_string & exceptionInfo)
Get the Unit of the dpe
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe data point element to configure
bUnitExists TRUE if unit is set, FALSE if no unit is set
sUnit output, return the Unit of the dpe
exceptionInfo output, details of any exceptions are returned here
Referenced by fwUnit_getMany().
fwUnit_getMany (dyn_string & dsDpe, dyn_bool & dbUnitExists, dyn_string & dsUnit, dyn_string & exceptionInfo)
Get the Unit of several dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsDpe input, data point elements to configure Passed as reference only for performance reasons. Not modified.
dbUnitExists Lists of bools indicating if unit is set - TRUE if unit is set, FALSE if no unit is set
dsUnit output, return the current Unit of the dpes
exceptionInfo output, details of any exceptions are returned here
References fwUnit_get().
Referenced by fwUnit_getMultiple().
fwUnit_getMultiple (dyn_string dsDpe, dyn_bool & dbUnitExists, dyn_string & dsUnit, dyn_string & exceptionInfo)
DEPRECATED - function to get the Unit of several dpes
Function is replaced by fwUnit_getMany
References fwUnit_getMany().
fwUnit_set (string dpe, string sUnit, dyn_string & exceptionInfo)
set the Unit of a single data point element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dpe input, data point element to configure
sUnit input, string Unit to set
exceptionInfo output, details of any exceptions are returned here
Referenced by fwUnit_setMany(), and fwUnit_setMultiple().
fwUnit_setMany (dyn_string & dsDpe, dyn_string & dsUnit, dyn_string & exceptionInfo)
Set differing Units for several dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsDpe input, data point elements to configure. Passed as reference only for performance reasons. Not modified.
dsUnit input, list of Units to set to dpes. Passed as reference only for performance reasons. Not modified.
exceptionInfo output, details of any exceptions are returned here
References fwUnit_set().
fwUnit_setMultiple (dyn_string dsDpe, string sUnit, dyn_string & exceptionInfo)
Set the same Unit for several dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters
dsDpe input, data point elements to configure
sUnit input, the Unit to set to all dpes
exceptionInfo output, details of any exceptions are returned here
References fwUnit_set().