/*
* Created by Giovanni Polese (Lappeenranta University of Technology
*	date:08/03/2007
*	LastChange:12/01/2009
*
Moved all to postInstall

*/
main()
{
fwInstallation_appendManager(TRUE, "Searching components", "PVSS00ctrl", "manual", 30, 2, 2, "CMS_RPCfwSupervisor/CMS_RPCfwSupervisorCrossActions.ctl");
fwInstallation_appendManager(TRUE, "Searching components", "PVSS00ctrl", "manual", 30, 2, 2, "CMS_RPCfwSupervisor/CMS_RPCfwSupervisorStartupScript.ctl");
}
