fwTrendingTree.ctl File Reference
fwTrendingTree.ctl File Reference
Functions
TrendTree_navigator_selected (string node, string parent)
TrendTree_editor_selected (string node, string parent)
fwTrendingTree_addToTree (string parent, string mode, int &done)
fwTrendingTree_showItemInfo (string node, string parent)
TrendTree_navigator_entered (string node, string parent)
TrendTree_editor_entered (string node, string parent)
TrendTree_nodeView (string node, string parent)
TrendTree_nodeSettings (string node, string parent)
TrendTree_nodeParameters (string node, string parent)
fwTrendingTree_checkIfNeedsTemplateParameters (string node, string device, string deviceType, bool &areNeeded, dyn_string &exceptionInfo)
fwTrendingTree_manageTrendingDevices (string node)
fwTrendingTree_displayNode (string node, string device, string deviceType, bool editorMode=TRUE)
fwTrendingTree_findInTree (string device, dyn_string &parents, dyn_string &nodes, dyn_string &exceptionInfo)
fwTrendingTree_showEditorPanel (string device, string deviceType, dyn_string &exceptionInfo)
fwTrendingTree_showNavigatorPanel (string device, string deviceType, string templateParameters, dyn_string &exceptionInfo)
_fwTrendingTree_addClipboard ()
_fwTrendingTree_upgradeTree ()
_fwTrendingTree_addSystemNameRecursive (string node)
fwTrendingTree_getTemplateParameters (string device, string &parameterString, dyn_string &exceptionInfo)
Variables
const string fwTrendingTree_TREE_NAME = "TrendTree"
const int fwTrendingTree_USER_DATA_PARAMETERS = 1
global bool isTrendEdit
Detailed Description
This library contains the functions required by the Trending Tree
Creation Date
04/11/04
Modification History
None
Constraints
Some functions rely on the fwTree and some require the Trending Editor and Navigator panel
Usage
Internal
PVSS managers
VISION
Author:
Oliver Holme (IT-CO)
Function Documentation
_fwTrendingTree_addClipboard ()
Adds a clipboard to the Trend Tree
Constraints
Only needs to be run once
Usage
Internal
PVSS managers
VISION
_fwTrendingTree_addSystemNameRecursive (string node)
Goes through old trees and adds the system name to any device references that do not contain the system name
Constraints
If not system name is specified, it is assumed that the device is on the local system
Usage
Internal
PVSS managers
VISION
Parameters:
node Used to recursively work through the tree. Give the name of the top node of the tree
_fwTrendingTree_upgradeTree ()
Upgrades old trees to the new format of tree (new format as of fwTrending2.3)
Constraints
Should only be run once
Usage
Internal
PVSS managers
VISION
fwTrendingTree_addToTree (string parent, string mode, int & done)
Function that is called when the user chooses to Add an item in the Trend Tree (Editor mode)
Adapted from generic function in fwTreeDisplay.ctl
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
parent input, name of the parent of the node to be created
mode input, the type of addition. Can be one of: "addnode" - add an emtpy node to the tree "addnew" - create a new device (plot or page) and create a new node to add it in the tree "addexisting" - create a new node to link to an existing device (plot or page)
done output, value is 1 if the node was created, 0 if the process was stopped before creation
References fwTrendingTree_getTemplateParameters().
Referenced by TrendTree_editor_entered().
fwTrendingTree_checkIfNeedsTemplateParameters (string node, string device, string deviceType, bool & areNeeded, dyn_string & exceptionInfo)
Checks if any template parameters are mentioned in the configuration for the given node/device in the tree.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
device input, name of the device attached to the node
deviceType input, dp type of the device attached to the node
areNeeded output, TRUE if any template parameters are mentioned in configuration, else FALSE
exceptionInfo Any exceptions are returned here
References _fwTrending_isSystemForDpeConnected(), fwTrending_getAllTemplateParametersForConfiguration(), fwTrending_getPage(), and fwTrending_getPlot().
Referenced by TrendTree_editor_entered().
fwTrendingTree_displayNode (string node, string device, string deviceType, bool editorMode = TRUE)
Function that is used to show either the editor or navigator panel for a specific tree node
Constraints
Only works for devices other than tree nodes (i.e. TrendingPages or TrendingPlots)
Usage
Internal
PVSS managers
VISION
Parameters:
node input, the currently selected node in the tree
device input, the name of the device attached to the selected node
deviceType input, the dpType of the device attached to the selected node
editorMode Optional parameter, default value TRUE. TRUE to display editor panel, FALSE to show navigator panel.
References fwTrendingTree_showEditorPanel(), and fwTrendingTree_showNavigatorPanel().
Referenced by TrendTree_nodeSettings(), and TrendTree_nodeView().
fwTrendingTree_findInTree (string device, dyn_string & parents, dyn_string & nodes, dyn_string & exceptionInfo)
Finds all the occurences of a given device tree
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
device input, the device to search for
parents input, a list of parents of the nodes to which the device is attached
nodes input, a list of the nodes to which the device is attached
exceptionInfo Any exceptions are returned here
fwTrendingTree_getTemplateParameters (string device, string & parameterString, dyn_string & exceptionInfo)
For a given device connected to a tree node, this function will check if any template parameters are required. If so, a dialog is shown and the user can enter values for the template parameters (or choose not to). This string is then returned by the function, and the value should then be stored in the userData of the relevant data.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
device input, the device to look at for template parameters
parameterString output, any template parameters that were configured by the user are returned here
exceptionInfo Any exceptions are returned here
References fwTrending_checkAndGetAllTemplateParameters(), fwTrending_getPage(), and fwTrending_getPlot().
Referenced by fwTrendingTree_addToTree().
fwTrendingTree_manageTrendingDevices (string node)
Function that is called when the user selects "Manage Plots and Pages..." from the contextual menu in the Trend Tree (Editor mode)
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, used to determine the panel title and also passed as $ parameter to panel (but this is not used by the panel)
Referenced by TrendTree_editor_entered(), and TrendTree_navigator_entered().
fwTrendingTree_showEditorPanel (string device, string deviceType, dyn_string & exceptionInfo)
Shows the editor panel for the given device (panel to be shown is read from device definitions)
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
device input, the device to open the panel for
deviceType input, the dpType of the device
exceptionInfo Any exceptions are returned here
Referenced by fwTrendingTree_displayNode().
fwTrendingTree_showItemInfo (string node, string parent)
Function that displays the information about the currently selected node in the Trending Editor & Navigator
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
Referenced by TrendTree_editor_selected(), and TrendTree_navigator_selected().
fwTrendingTree_showNavigatorPanel (string device, string deviceType, string templateParameters, dyn_string & exceptionInfo)
Shows the navigator panel for the given device (panel to be shown is read from device definitions)
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
device input, the device to open the panel for
deviceType input, the dpType of the device
templateParameters input, any template parameters for the device are passed here
exceptionInfo Any exceptions are returned here
References fwTrending_getPage(), and fwTrending_getPlot().
Referenced by fwTrendingTree_displayNode().
TrendTree_editor_entered (string node, string parent)
Function that is called when the user right-clicks an item in the Trend Tree (Editor mode) It displays a contextual menu with the ncessary options for the selected device in the current mode.
Adapted from generic function in fwTreeDisplay.ctl
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrendingTree_addToTree(), fwTrendingTree_checkIfNeedsTemplateParameters(), and fwTrendingTree_manageTrendingDevices().
TrendTree_editor_selected (string node, string parent)
Function that is called when the user selects an item in the Trend Tree (Editor mode)
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrendingTree_showItemInfo().
TrendTree_navigator_entered (string node, string parent)
Function that is called when the user right-clicks an item in the Trend Tree (Navigator mode) It displays a contextual menu with the ncessary options for the selected device in the current mode.
Adapted from generic function in fwTreeDisplay.ctl
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrendingTree_manageTrendingDevices().
TrendTree_navigator_selected (string node, string parent)
Function that is called when the user selects an item in the Trend Tree (Navigator mode)
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrendingTree_showItemInfo().
TrendTree_nodeParameters (string node, string parent)
Function that is called when the user selects Template Parameters from the contextual menu in the Trend Tree (Editor mode) Reads any existing settings from the node user data and then lets the user modify the values for any required parameters. This modified value is then saved back to the user data.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrending_getPage(), fwTrending_getPlot(), and fwTrending_modifyAllTemplateParameters().
TrendTree_nodeSettings (string node, string parent)
Function that is called when the user selects Settings from the contextual menu in the Trend Tree (Editor mode)
Adapted from generic function in fwTreeDisplay.ctl
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrendingTree_displayNode().
TrendTree_nodeView (string node, string parent)
Function that is called when the user selects View from the contextual menu in the Trend Tree (Navigator mode)
Adapted from generic function in fwTreeDisplay.ctl
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
node input, name of the selected node
parent input, name of the parent of the selected node
References fwTrendingTree_displayNode().