fwAlarmHandlingScreenGroups.ctl File Reference
fwAlarmHandlingScreenGroups.ctl File Reference
Functions
dyn_string _fwAlarmHandlingScreenGroups_getFsmDeviceDps (string sCU)
int fwAlarmHandlingScreenGroups_getConfig (dyn_dyn_string &sysFilters, dyn_mixed &dpFilters, dyn_mixed &aliasFilters, dyn_string &dsGroupsDescriptions)
string fwAlarmHandlingScreenGroups_getGroupId (string dpName)
string fwAlarmHandlingScreenGroups_getDefaultSoundPath ()
Variables
const int fwAlarmHandlingGroups_INDEX_SUBSYS = 1
const int fwAlarmHandlingGroups_INDEX_SYS = 2
const int fwAlarmHandlingGroups_INDEX_DPE = 3
const int fwAlarmHandlingGroups_INDEX_ALIAS = 4
const int fwAlarmHandlingGroups_INDEX_PRIO = 5
const int fwAlarmHandlingGroups_INDEX_FSMCU = 6
const string fwAlarmHandlingGroups_CONFIG_DP = "_fwAesGroupsConfig_"
const string fwAlarmHandlingGroups_ORDER_DP = "_fwAesGroupsSetup.groups"
const string fwAlarmHandlingGroups_ORDERMODE_DP = "_fwAesGroupsSetup.customOrder"
const string fwAlarmHandlingGroups_SOUNDFILE_DP = "_fwAesGroupsSetup.sound.fileName"
const string fwAlarmHandlingGroups_SOUNDENABLED_DP = "_fwAesGroupsSetup.sound.enabled"
const string fwAlarmHandlingGroups_SOUNDSOURCE_DP = "_fwAesGroupsSetup.sound.playSource"
const string fwAlarmHandlingGroups_SOUNDINHIBIT_DP = "_fwAesGroupsSetup.sound.inhibitSec"
const string fwAlarmHandlingGroups_SETUP_DPTYPE = "_FwAesGroupsSetup"
const string fwAlarmHandlingGroups_SETUP_DP = "_fwAesGroupsSetup"
const string fwAlarmHandlingGroups_CONFIG_DPTYPE = "_FwAesGroupsConfig"
const string fwAlarmHandlingGroups_FRAME_TXT = "Filters for subsystem "
const string fwAlarmHandlingGroups_TYPE_ROOT = "root"
const string fwAlarmHandlingGroups_TYPE_SYS = "system"
const string fwAlarmHandlingGroups_TYPE_DP = "dp"
const string fwAlarmHandlingGroups_TYPE_ALIAS = "alias"
const string fwAlarmHandlingGroups_TYPE_FSMCU = "FSM CU"
const string fwAlarmHandlingGroups_TYPE_GROUP = "group"
const string fwAlarmHandlingGroups_ELEMENTS_SEPARATOR = ","
const string fwAlarmHandlingGroups_ICON_DP = "dpTree/dp.png"
const int fwAlarmHandlingGroups_SOUNDSOURCE_PCSPEAKER = 0
const int fwAlarmHandlingGroups_SOUNDSOURCE_FILE = 1
Detailed Description
fwAlarmHandlingScreenGroups This library contains functions for the internal workings of the JCOP Alarm Screen with Groups.
Creation Date
05/10/2011
Modification History
Constraints
Usage
Internal
PVSS managers
VISION
Author:
Marco Boccioli (EN/ICE), based on the original project of Giovanni Polese
Function Documentation
dyn_string _fwAlarmHandlingScreenGroups_getFsmDeviceDps (string sCU)
Receive the CU name, return the list of dpes of all the DU below the CU and the nested CUs.
Constraints
None
Usage
Internal
PVSS managers
VISION
Parameters:
sCU The Control Unit name Use the fwAlarmHandlingScreen_CONFIG_OBJECT_FILTER_XXX constants to interpret the object
Returns:
the list of dpes belonging to the Device Units under the CU and under the nested CUs.
Referenced by fwAlarmHandlingScreenGroups_getConfig().
int fwAlarmHandlingScreenGroups_getConfig (dyn_dyn_string & sysFilters, dyn_mixed & dpFilters, dyn_mixed & aliasFilters, dyn_string & dsGroupsDescriptions)
Read the Groups configuration
Constraints
The function can only be called from within the JCOP FW Alarm Screen with Groups
Usage
Public
PVSS managers
VISION
Parameters:
sysFilters the list of system filters (one per group) is returned here.
dpFilters the list of dp filters (one list per system) is returned here.
aliasFilters the list of alias filters (one list per system) is returned here.
dsGroupsDescriptions the list of groups descriptions is returned here.
sysFilters the list of filters is returned here.
Returns:
0 if ok, -1 if problem.
References _fwAlarmHandlingScreenGroups_getFsmDeviceDps(), and fwAlarmHandlingScreenGroups_getGroupId().
string fwAlarmHandlingScreenGroups_getDefaultSoundPath ()
Return the default alarm sound to be played
Constraints
None
Usage
Public
PVSS managers
VISION
Returns:
the alarms sound path.
string fwAlarmHandlingScreenGroups_getGroupId (string dpName)
Get the Group dp and return the Group name
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
dpName the dp name of the group.
Returns:
the group name.
Referenced by fwAlarmHandlingScreenGroups_getConfig().