fwConfigs: fwConfigs.ctl File Reference
fwConfigs.ctl File Reference
Functions
_fwConfigs_checkAreConfigsAccessible (dyn_string dpes, bool &areAccessible, dyn_int &requiredDrivers, dyn_string &exceptionInfo)
_fwConfigs_convertDriverNumbersToErrorMessage (dyn_int driverNumbers, string &errorMessage, dyn_string &exceptionInfo)
_fwConfigs_delete (dyn_string dpes, string configType, dyn_string &exceptionInfo, float setWithTime=-1)
_fwConfigs_getConfigTypeAttribute (dyn_string dpes, string configType, dyn_mixed &attributeValues, dyn_string &exceptionInfo, string customAttribute=".._type")
_fwConfigs_getConfigAttributes (dyn_string dpes, string configType, dyn_string attributes, dyn_dyn_mixed &attributeValues, dyn_string &exceptionInfo)
_fwConfigs_getAttributes (dyn_dyn_string dpeAttributes, dyn_dyn_mixed &attributeValues, dyn_string &exceptionInfo)
_fwConfigs_setConfigTypeAttribute (dyn_string dpes, string configType, dyn_anytype attributeValues, dyn_string &exceptionInfo, string customAttribute=".._type", float setWithTime=-1)
_fwConfigs_setConfigAttributes (dyn_string dpes, string configType, dyn_string attributes, dyn_dyn_anytype attributeValues, dyn_string &exceptionInfo, float setWithTime=-1)
_fwConfigs_setAttributes (dyn_dyn_string dpeAttributes, dyn_dyn_anytype attributeValues, dyn_string &exceptionInfo, float setWithTime=-1)
bool _fwConfigs_checkDpeList (dyn_string dpes, string config, string &chosenDpeType, dyn_string &exceptionInfo, string &errorString)
_fwConfigs_getConfigOptionsForDpeType (int dpeType, string config, int &configOptions, dyn_string &exceptionInfo)
_fwConfigs_getConfigOptionsForDpe (string dpe, string config, int &configOptions, dyn_string &exceptionInfo)
fwConfigs_getDpeTypeText (string dpe, string &dpeTypeName, dyn_string &exceptionInfo)
fwConfigs_getDataTypeText (int dataType, string &dataTypeText, dyn_string &exceptionInfo)
fwConfigs_getBestFormatForDpeList (dyn_string dpes, string &formatString, dyn_string &exceptionInfo)
fwConfigs_getBestFormatForDpe (string dpe, string &formatString, dyn_string &exceptionInfo)
fwConfigs_getBestFormatForDpeType (string dpeType, string &formatString, dyn_string &exceptionInfo)
fwConfigs_setTextFieldsFormat (dyn_string textFields, string formatString, dyn_bool formatOptions, dyn_string &exceptionInfo)
_fwConfigs_chooseBestFormat (string format1, string format2, string &bestFormat, dyn_string &exceptionInfo)
_fwConfigs_getDefaultFormatForDpeType (int dpeType, string &format, dyn_string &exceptionInfo)
fwConfigs_checkStringFormat (string value, int dpeType, bool &isOk, dyn_string &exceptionInfo)
fwConfigs_getConfigLock (string dpe, string config, bool &isLocked, dyn_string &lockDetails, dyn_string &exceptionInfo)
fwConfigs_checkIsConfigWriteable (string dpe, string config, bool &isWriteable, dyn_string &exceptionInfo)
fwConfigs_createDpeConfigObject (dyn_dyn_anytype &dpeConfigObject, string dpe, int type, dyn_string &exceptionInfo, bool active=false, int dpeType=-1)
fwConfigs_init ()
_fwConfigs_getSystemsInDpeList (dyn_string dpeList, dyn_string &systems, dyn_string &exceptionInfo)
_fwConfigs_getManagerHostname (int managerId, string &managerHostname, dyn_string &exceptionInfo)
Detailed Description
This library contains function associated with generic tasks for all configs.
Creation Date
15/01/2004
Modification History
24/05/11 Marco Boccioli
ENS-3185: support alarms for dpe of type bit32.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author:
Oliver Holme (IT-CO)
Function Documentation
_fwConfigs_checkAreConfigsAccessible (dyn_string dpes, bool & areAccessible, dyn_int & requiredDrivers, dyn_string & exceptionInfo)
Checks that the config can be read/written on a given list of dpes - for use with smoothing and conversion configs. This is dependant on the driver number running that is specified in the _address config of the same dpe. If no _address config exists, then there must be a simulation driver 1 running (which is running by default in PVSS projects).
Constraints
All dpes must be from the same system
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
areAccessible returns TRUE if configs are accessible (because the necessary drivers are running) returns FALSE if configs are not accessible (because the necessary drivers are not running)
requiredDrivers if areAccessible = FALSE, a list of the drivers that are needed but not running is returned
exceptionInfo details of any exceptions are returned here
References _fwConfigs_getSystemsInDpeList(), and fwPeriphAddress_checkAreDriversRunning().
Referenced by fwConfigConversion_deleteMany(), fwConfigConversion_get(), fwConfigConversion_getMany(), fwConfigConversion_setMany(), fwSmoothing_deleteMany(), fwSmoothing_get(), fwSmoothing_getMany(), fwSmoothing_getManyWithCheck(), and fwSmoothing_setMany().
bool _fwConfigs_checkDpeList (dyn_string dpes, string config, string & chosenDpeType, dyn_string & exceptionInfo, string & errorString)
Checks that all the dpes in the list can be configured with the same type of config eg. BOOLs and INTs can have different types of config settings for alert handling So if a list containing a mixture of BOOLs and INTs was passed and config = fwConfigs_PVSS_ALERT_HDL, the function would return FALSE.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
config the type of config to check consistency for: fwConfigs_PVSS_ADDRESS fwConfigs_PVSS_ARCHIVE fwConfigs_PVSS_ALERT_HDL fwConfigs_PVSS_ORIGINAL fwConfigs_PVSS_PV_RANGE fwConfigs_PVSS_SMOOTH fwConfigs_PVSS_MSG_CONV fwConfigs_PVSS_CMD_CONV fwConfigs_PVSS_COMMON
chosenDpeType the function returns the type of the first valid data point element in the list
exceptionInfo details of any errors are returned here
errorString Output - in case the function returns FALSE, an error message is returned here which can be used to raise an exception
Returns:
BOOLEAN - TRUE is list of dpes can all be configured with the same type of config, else FALSE
References _fwConfigs_getConfigOptionsForDpe().
_fwConfigs_chooseBestFormat (string format1, string format2, string & bestFormat, dyn_string & exceptionInfo)
Given two formats, this function will identify which is the most flexible for displaying various data and return that format
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
format1 the first format to consider
format2 the second format to consider
bestFormat the most flexible of the two formats is returned here
exceptionInfo details of any errors are returned here
Referenced by fwConfigs_getBestFormatForDpeList().
_fwConfigs_convertDriverNumbersToErrorMessage (dyn_int driverNumbers, string & errorMessage, dyn_string & exceptionInfo)
This function converts a list of driver numbers (a dyn_int) into a nice human readable string of numbers in the format "1, 2, 3 and 4".
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
driverNumbers the list of driver numbers
errorMessage Output - the "nice" string is returned here
exceptionInfo details of any errors are returned here
Referenced by fwConfigConversion_deleteMany(), fwConfigConversion_get(), fwConfigConversion_getMany(), fwConfigConversion_setMany(), fwSmoothing_deleteMany(), fwSmoothing_get(), fwSmoothing_getMany(), fwSmoothing_getManyWithCheck(), and fwSmoothing_setMany().
_fwConfigs_delete (dyn_string dpes, string configType, dyn_string & exceptionInfo, float setWithTime = -1)
Deletes the specified config for the given data point elements
Constraints
All dpes in the list must be from the same system
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
configType the type of the config to read
exceptionInfo details of any errors are returned here
setWithTime OPTIONAL PARAMETER - default -1, use dpSetWait If value is >= 0 then dpSetTimedWait is used with the given value If value is 0, then a dpSetTimedWait with t=0 is used which sometimes avoids data going to the param history
References _fwConfigs_setConfigTypeAttribute().
Referenced by fwAlertConfig_deleteMultiple(), fwArchive_delete(), fwArchive_deleteMany(), fwArchive_deleteMultiple(), fwConfigConversion_deleteMany(), fwPvRange_delete(), fwPvRange_deleteMany(), fwPvRange_deleteMultiple(), and fwSmoothing_deleteMany().
_fwConfigs_getAttributes (dyn_dyn_string dpeAttributes, dyn_dyn_mixed & attributeValues, dyn_string & exceptionInfo)
This functions is used to get the values of defined config attributes for a list of dpes This function can get different attributes for each dpe. If you want to read the same attributes for each dpe, use _fwConfigs_getConfigAttributes() This function uses dpGet grouping to speed up performance compared to simply reading each attribute one by one.
Constraints
All dpes in the list must be from the same system There is no checking of the inputs to this function. It is designed for speed, so any checking is your own responsibility!
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpeAttributes an array of dpe attributes to be read (given in form e.g. "dpe:_config.._attribute") The first dimension of the array should be used to divide up the attributes for each dpe The second dimension is used to list all the attributes to be read for each dpe e.g. dpeAttributes[1][1] = "dpe1:_alert.._type" dpeAttributes[1][2] = "dpe1:_original.._attribute" dpeAttributes[1][3] = "dpe1:_smooth.._type" dpeAttributes[2][1] = "dpe2:_original.._value" dpeAttributes[3][1] = "dpe3:_pv_range.._type" dpeAttributes[3][2] = "dpe3:_original.._exp_inv"
attributeValues an array containing the results attribute values from each dpe is returned here The array elements correspond to the same cells in which the attribute was put in dpeAttributes
exceptionInfo details of any errors are returned here
Referenced by _fwConfigs_getConfigAttributes().
_fwConfigs_getConfigAttributes (dyn_string dpes, string configType, dyn_string attributes, dyn_dyn_mixed & attributeValues, dyn_string & exceptionInfo)
This functions is used to get the values of a list attributes of the given config for a list of dpes. This function reads the same attributes for each of the given dpes. If you need to read from different attributes on each dpe, use _fwConfigs_getAttributes. This function uses dpGet grouping to speed up performance compared to simply reading each attribute one by one.
Constraints
All dpes in the list must be from the same system
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements from which the attributes should be read
configType the type of the config to read
attributes the list of attributes to be read from the config on each dpe (given in form e.g. ".._type")
attributeValues an array containing the results attribute values from each dpe is returned here e.g. attributeValues[1][2] = value of attribute read from dpe[1] and attributes[2]
exceptionInfo details of any errors are returned here
References _fwConfigs_getAttributes().
Referenced by _fwConfigs_getConfigTypeAttribute(), and fwOriginal_getMany().
_fwConfigs_getConfigOptionsForDpe (string dpe, string config, int & configOptions, dyn_string & exceptionInfo)
Checks what kind of config type is supported by the given data point element eg. DPEL_BOOL can support only a BINARY alert handling config DPEL_INT can support only an ANALOG alert handling config
Note: This function implements both the policy of PVSS and the JCOP FW in terms of what dpe type can support what type of config
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe a data point element
config the type of config to check consistency for: fwConfigs_PVSS_ADDRESS fwConfigs_PVSS_ARCHIVE fwConfigs_PVSS_ALERT_HDL fwConfigs_PVSS_ORIGINAL fwConfigs_PVSS_PV_RANGE fwConfigs_PVSS_SMOOTH fwConfigs_PVSS_MSG_CONV fwConfigs_PVSS_CMD_CONV fwConfigs_PVSS_UNIT fwConfigs_PVSS_FORMAT
configOptions the function returns the type of config that is suitable for the given type: fwConfigs_GENERAL_OPTIONS fwConfigs_BINARY_OPTIONS fwConfigs_ANALOG_OPTIONS fwConfigs_NOT_SUPPORTED (if a config is not supported by the dpe)
exceptionInfo details of any errors are returned here
References _fwConfigs_getConfigOptionsForDpeType().
Referenced by _fwConfigs_checkDpeList(), and fwAlertConfig_objectSetMany().
_fwConfigs_getConfigOptionsForDpeType (int dpeType, string config, int & configOptions, dyn_string & exceptionInfo)
Checks what kind of config type is supported by the given data point element type eg. DPEL_BOOL can support only a BINARY alert handling config DPEL_INT can support only an ANALOG alert handling config
Note: This function does not check whether the config is supported by PVSS for dpes of the data point element type It only offers the most suitable method according to the JCOP FW regardless of PVSS support for such a config.
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpeType a data point type eg. DPEL_BOOL
config the type of config to check consistency for: fwConfigs_PVSS_ADDRESS fwConfigs_PVSS_ARCHIVE fwConfigs_PVSS_ALERT_HDL fwConfigs_PVSS_ORIGINAL fwConfigs_PVSS_PV_RANGE fwConfigs_PVSS_SMOOTH fwConfigs_PVSS_MSG_CONV fwConfigs_PVSS_CMD_CONV fwConfigs_PVSS_DP_FUNCT fwConfigs_PVSS_UNIT fwConfigs_PVSS_FORMAT
configOptions the function returns the type of config that is suitable for the given type: fwConfigs_GENERAL_OPTIONS fwConfigs_BINARY_OPTIONS fwConfigs_ANALOG_OPTIONS fwConfigs_NOT_SUPPORTED (if a config is not supported by the dpeType)
exceptionInfo details of any errors are returned here
Referenced by _fwConfigs_getConfigOptionsForDpe().
_fwConfigs_getConfigTypeAttribute (dyn_string dpes, string configType, dyn_mixed & attributeValues, dyn_string & exceptionInfo, string customAttribute = ".._type")
This functions is used to get the ..type attributes of the given config for a list of dpes This function uses dpGet grouping to speed up performance compared to simply reading each attribute one by one.
Constraints
All dpes in the list must be from the same system
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements from which the type attribute should be read
configType the type of the config to read
attributeValues a list containing the results of the dpGet is returned here
exceptionInfo details of any errors are returned here
customAttribute Optional parameter - default value ".._type" this can be used to access a different attribute to the default type attribute if a value is not passed, the .._type attribute is read
References _fwConfigs_getConfigAttributes().
Referenced by _fwAlertConfig_activateOrDeactivate(), _fwPvRange_get(), fwAlertConfig_acknowledgeMany(), fwAlertConfig_deleteMultiple(), fwAlertConfig_generateAbsoluteLimitsMany(), fwAlertConfig_objectGetMany(), fwAlertConfig_objectSetMany(), fwOriginal_setMany(), and fwPeriphAddress_changeOpcGroups().
_fwConfigs_getDefaultFormatForDpeType (int dpeType, string & format, dyn_string & exceptionInfo)
This function will return the default fromat for a given dpe type (based on dpGetDefaultFormat in libCTRL.ctl)
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpeType the dpe type to get the format for
format the default format used for this dpe type
exceptionInfo details of any errors are returned here
Referenced by fwConfigs_getBestFormatForDpeList(), and fwConfigs_getBestFormatForDpeType().
_fwConfigs_getManagerHostname (int managerId, string & managerHostname, dyn_string & exceptionInfo)
This function returns the host name where the given manager is running. The manager id passed is the internal PVSS manager ID as used by functions like convManIdToInt(). The function looks in the internal PVSS _Connections DPs to find this information.
Constraints
Currently only supports CTRL and UI managers (because users can lock configs from these managers)
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
managerId The manager ID for which you want to find the host name
managerHostname The hostname is returned here
exceptionInfo Details of any exceptions are returned here
Referenced by fwConfigs_getConfigLock().
_fwConfigs_getSystemsInDpeList (dyn_string dpeList, dyn_string & systems, dyn_string & exceptionInfo)
This function gives a list of the systems that are referred to in the given list of dpes.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpeList The list of dpes to search for the systems in
systems The list of all the systems referred to in the dpe list are returned here
exceptionInfo Details of any exceptions are returned here
Referenced by _fwConfigs_checkAreConfigsAccessible(), fwPeriphAddress_get(), fwPeriphAddress_getMany(), and fwPeriphAddress_set().
_fwConfigs_setAttributes (dyn_dyn_string dpeAttributes, dyn_dyn_anytype attributeValues, dyn_string & exceptionInfo, float setWithTime = -1)
This functions is used to set the values of defined config attributes for a list of dpes This function can set different attributes for each dpe. If you want to write to the same attributes for each dpe, use _fwConfigs_setConfigAttributes() This function uses dpGet grouping to speed up performance compared to simply reading each attribute one by one.
Constraints
All dpes in the list must be from the same system There is no checking of the inputs to this function. It is designed for speed, so any checking is your own responsibility!
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpeAttributes an array of dpe attributes to be write (given in form e.g. "dpe:_config.._attribute") The first dimension of the array should be used to divide up the attributes for each dpe The second dimension is used to list all the attributes to be read for each dpe e.g. dpeAttributes[1][1] = "dpe1:_alert.._type" dpeAttributes[1][2] = "dpe1:_original.._attribute" dpeAttributes[1][3] = "dpe1:_smooth.._type" dpeAttributes[2][1] = "dpe2:_original.._value" dpeAttributes[3][1] = "dpe3:_pv_range.._type" dpeAttributes[3][2] = "dpe3:_original.._exp_inv"
attributeValues an array containing the attribute values to write to each dpe The array elements correspond to the same cells in which the attribute was put in dpeAttributes
exceptionInfo details of any errors are returned here
setWithTime OPTIONAL PARAMETER - default -1, use dpSetWait If value is >= 0 then dpSetTimedWait is used with the given value If value is 0, then a dpSetTimedWait with t=0 is used which sometimes avoids data going to the param history
Referenced by _fwConfigs_setConfigAttributes().
_fwConfigs_setConfigAttributes (dyn_string dpes, string configType, dyn_string attributes, dyn_dyn_anytype attributeValues, dyn_string & exceptionInfo, float setWithTime = -1)
This functions is used to set the values of a list attributes of the given config for a list of dpes This function sets the same attributes for each of the given dpes. If you need to write to different attributes on each dpe, use _fwConfigs_setAttributes. This function uses dpGet grouping to speed up performance compared to simply reading each attribute one by one.
Constraints
All dpes in the list must be from the same system
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements to which the attributes should be written
configType the type of the config to write to
attributes the list of attributes to be wrriten to the config on each dpe (given in form e.g. ".._type")
attributeValues an array containing the attribute values to write to each dpe e.g. attributeValues[3][4] = value of attribute to write to configAttributes[3][4] of dpe[3]
exceptionInfo details of any errors are returned here
setWithTime OPTIONAL PARAMETER - default -1, use dpSetWait If value is >= 0 then dpSetTimedWait is used with the given value If value is 0, then a dpSetTimedWait with t=0 is used which sometimes avoids data going to the param history
References _fwConfigs_setAttributes().
Referenced by _fwConfigs_setConfigTypeAttribute(), and fwOriginal_setMany().
_fwConfigs_setConfigTypeAttribute (dyn_string dpes, string configType, dyn_anytype attributeValues, dyn_string & exceptionInfo, string customAttribute = ".._type", float setWithTime = -1)
This functions is used to set the ..type attributes of the given config for a list of dpes This function uses dpSetWait grouping to speed up performance compared to simply reading each attribute one by one.
Constraints
All dpes in the list must be from the same system
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements from which the type attribute should be read
configType the type of the config to read
attributeValues a list containing the values to be written to each ..type attribute
exceptionInfo details of any errors are returned here
customAttribute Optional parameter - default value ".._type" this can be used to access a different attribute to the default type attribute if a value is not passed, the .._type attribute is set
setWithTime OPTIONAL PARAMETER - default -1, use dpSetWait If value is >= 0 then dpSetTimedWait is used with the given value If value is 0, then a dpSetTimedWait with t=0 is used which sometimes avoids data going to the param history
References _fwConfigs_setConfigAttributes().
Referenced by _fwConfigs_delete(), _fwPvRange_set(), fwAlertConfig_acknowledgeMany(), fwArchive_startMultiple(), fwArchive_stopMultiple(), fwPeriphAddress_changeOpcGroups(), and fwSmoothing_setMany().
fwConfigs_checkIsConfigWriteable (string dpe, string config, bool & isWriteable, dyn_string & exceptionInfo)
This functions checks whether a specified config of a given dpe is available to be written to (i.e. not locked). To get more details of the lock itself (who etc.) then call fwConfigs_getConfigLock() instead of this function.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe the data point in question
config the config to check. Use the following constants to pick: fwConfigs_PVSS_ADDRESS fwConfigs_PVSS_ARCHIVE fwConfigs_PVSS_ALERT_HDL fwConfigs_PVSS_ORIGINAL fwConfigs_PVSS_PV_RANGE fwConfigs_PVSS_SMOOTH fwConfigs_PVSS_MSG_CONV fwConfigs_PVSS_CMD_CONV fwConfigs_PVSS_COMMON
isWriteable returns TRUE if the config is writeable, else FALSE (implies that the config is locked)
exceptionInfo details of any exceptions are returned here
References fwConfigs_getConfigLock().
fwConfigs_checkStringFormat (string value, int dpeType, bool & isOk, dyn_string & exceptionInfo)
This function checks whether a value as a string (for example as entered in a text field) is consistent with the default value formatting for a given dpe type
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
value the value to check (as a string)
dpeType the dpe type to use to verify the formatting of the value (presumably the target dpe for the value to be written to)
isOk returns TRUE if the value is formatted OK for the dpe, else FALSE
exceptionInfo details of any errors are returned here
fwConfigs_createDpeConfigObject (dyn_dyn_anytype & dpeConfigObject, string dpe, int type, dyn_string & exceptionInfo, bool active = false, int dpeType = -1)
This functions creates an object (dyn_dyn_anytype) from the basic attributes of a config. The basic attributes are the dpe to which it belongs, the _type and active (if supported) of the config.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpeConfigObject The config object is returned here
dpe The name of the dpe is passed here
type The config type is passed here
exceptionInfo Details of any exceptions are returned here
active Optional parameter - Pass TRUE or FALSE for configs that support the active setting Otherwise you can leave it blank and the default (FALSE) will be used
dpeType Optional parameter - Only for optimisation purposes. Normally you do not need this parameter. You may pass the data type of the DPE (if known) here to avoid the function doing a dpElementType() call.
Referenced by _fwAlertConfig_createDpeAlertConfigObject().
fwConfigs_getBestFormatForDpe (string dpe, string & formatString, dyn_string & exceptionInfo)
Provides a format string that is sufficiently flexible to show the required format for a dpe
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe a data point element
formatString a format which allows display of the given dpe in the format specified in the common config on that dpe
exceptionInfo details of any errors are returned here
References fwConfigs_getBestFormatForDpeList().
fwConfigs_getBestFormatForDpeList (dyn_string dpes, string & formatString, dyn_string & exceptionInfo)
Provides a format string that is sufficiently flexible to show all the formats of the dpes given in the list
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes a list of data point elements
formatString a format which allows display of all the given dpes in the format specified in the common config on each dpe
exceptionInfo details of any errors are returned here
References _fwConfigs_chooseBestFormat(), and _fwConfigs_getDefaultFormatForDpeType().
Referenced by fwConfigs_getBestFormatForDpe().
fwConfigs_getBestFormatForDpeType (string dpeType, string & formatString, dyn_string & exceptionInfo)
Provides a format string that is sufficiently flexible to show the required format for a dpe type
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpeType a data point element type
formatString a format which allows display of the given dpe type in the format best suited to that data type
exceptionInfo details of any errors are returned here
References _fwConfigs_getDefaultFormatForDpeType().
fwConfigs_getConfigLock (string dpe, string config, bool & isLocked, dyn_string & lockDetails, dyn_string & exceptionInfo)
This functions checks the state of the lock of a given config on a given dpe
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe the data point in question
config the config to check. Use the following constants to pick: fwConfigs_PVSS_ADDRESS fwConfigs_PVSS_ARCHIVE fwConfigs_PVSS_ALERT_HDL fwConfigs_PVSS_ORIGINAL fwConfigs_PVSS_PV_RANGE fwConfigs_PVSS_SMOOTH fwConfigs_PVSS_MSG_CONV fwConfigs_PVSS_CMD_CONV fwConfigs_PVSS_COMMON
isLocked returns TRUE if the config is locked, else FALSE
lockDetails if the config is locked, the details of the lock are returned here lockDetails[fwConfigs_LOCK_MANAGER_DETAIL] - The name of the manager that has control of the config lockDetails[fwConfigs_LOCK_USER_NAME] - The name of the user who has control of the config lockDetails[fwConfigs_LOCK_MANAGER_TYPE] - The type of manager that has control of the config lockDetails[fwConfigs_LOCK_MANAGER_NUMBER] - Manager number of manager that has contol of the config lockDetails[fwConfigs_LOCK_MANAGER_SYSTEM] - System name of manager that has contol of the config lockDetails[fwConfigs_LOCK_MANAGER_HOST] - The host of the manager that has control of the config lockDetails[fwConfigs_LOCK_USER_ID] - User ID of user who has control of the config lockDetails[fwConfigs_LOCK_TYPE] - Type of lock on the config
exceptionInfo details of any errors are returned here
References _fwConfigs_getManagerHostname().
Referenced by fwConfigs_checkIsConfigWriteable().
fwConfigs_getDataTypeText (int dataType, string & dataTypeText, dyn_string & exceptionInfo)
Provides a text version of a given data type
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dataType a data type
dataTypeText a text version of the data type eg: BOOLEAN (returned value if dpe is of type DPEL_BOOL)
exceptionInfo details of any errors are returned here
Referenced by fwConfigs_getDpeTypeText().
fwConfigs_getDpeTypeText (string dpe, string & dpeTypeName, dyn_string & exceptionInfo)
Provides a text version of the dpElementType of a given dpe
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe a data point element
dpeTypeName a text version of the data point element type eg: BOOLEAN (returned value if dpe is of type DPEL_BOOL)
exceptionInfo details of any errors are returned here
References fwConfigs_getDataTypeText().
fwConfigs_init ()
Initialises useful mappings like fwConfigs_PVSS, fwConfigs_FW and fwConfigs_FW_PANEL. This function should be called once per manager before attempting to use one of the mappings.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
fwConfigs_setTextFieldsFormat (dyn_string textFields, string formatString, dyn_bool formatOptions, dyn_string & exceptionInfo)
Sets the format attributes of the given list of text fields to the specified format
For more info on format strings, see the PVSS Online Help -> CONTROL -> Control Graphics -> Graphics Objects -> Format string
Constraints
None
Usage
Public
PVSS managers
VISION
Parameters:
textFields a list of text fields to operate on
formatString the format which you wish to apply to the text fields
formatOptions these are the additional options that can be set when the formatting of a text field is defined formatOptions[1] is EmptyifZero formatOptions[2] is LeadingZeros formatOptions[3] is Alignment formatOptions[4] is Exponentialrep
exceptionInfo details of any errors are returned here