fwSmoothing.ctl File Reference
fwSmoothing.ctl File Reference
Functions
fwSmoothing_setMany (dyn_string &dpes, dyn_int &smoothProcedure, dyn_float &deadband, dyn_float &timeInterval, dyn_string &exceptionInfo, bool runDriverCheck=FALSE, bool storeInParamHistory=TRUE)
fwSmoothing_setMultiple (dyn_string dpes, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo, bool runDriverCheck=FALSE, bool storeInParamHistory=TRUE)
fwSmoothing_set (string dpe, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo, bool runDriverCheck=FALSE, bool storeInParamHistory=TRUE)
fwSmoothing_deleteMultiple (dyn_string dpes, dyn_string &exceptionInfo)
fwSmoothing_deleteMany (dyn_string dpes, dyn_string &exceptionInfo)
fwSmoothing_delete (string dpe, dyn_string &exceptionInfo)
fwSmoothing_get (string dpe, bool &configExists, int &smoothProcedure, float &deadband, float &timeInterval, dyn_string &exceptionInfo)
fwSmoothing_getManyWithCheck (dyn_string &dpes, dyn_bool &configExists, dyn_int &smoothProcedure, dyn_float &deadband, dyn_float &timeInterval, dyn_string &exceptionInfo)
fwSmoothing_getMany (dyn_string &dpes, dyn_bool &configExists, dyn_int &smoothProcedure, dyn_float &deadband, dyn_float &timeInterval, dyn_string &exceptionInfo)
_fwSmoothing_getParameters (dyn_string &dpes, bool isArchiveConfig, dyn_int &smoothProcedure, dyn_float &deadband, dyn_float &timeInterval, dyn_string &exceptionInfo)
_fwSmoothing_setParameters (dyn_string dpes, bool isArchiveConfig, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string &exceptionInfo, bool storeInParamHistory=TRUE)
Detailed Description
This library contains function associated with the smoothing config. Functions are provided for getting the current settings, deleting the config and setting the config
Creation Date
19/06/2000
Modification History
05/09/11 Marco Boccioli
#86405: index out of range if a dpe has archive not fully parametrized. In case an attribute is not readable, _fwSmoothing_getParameters() makes a dpGet attribute per attribute. In this way it saves all the other dpes that are readable.
31/08/11 Marco Boccioli
#86236: Error if dpe has no smoothing configured. added check into _fwSmoothing_getParameters()
12/08/11 Marco Boccioli
#85462: Functions *_setMany and *_getMany with parameters as reference.
#85464: Improved performance for fwSmoothing_getMany(). It now makes 2 dpGet instead of 2*n.
26/01/11 Marco Boccioli
#77348, ENS-2495 - added option to archive or not the modification of smoothing (parametrization history).
21/01/04 Oliver
Added functionality for relative deadband values. Seperated out get and set of smoothing parameters (for use by fwArchive and fwSmoothing functions)
15/01/04 Oliver
Completed overhaul of whole library
15/09/00 Oliver
added error handling to save and delete functions
Oliver
cases for "combined smoothing and time" and " old/new comparison and time" added ability to get/set time interval when available
Constraints
WARNING: the functions use the dpGet or dpSetWait, problems may occur when using these functions in a working function called by a PVSS (dpConnect) or in a calling function
Usage
Public
PVSS managers
VISION, CTRL
Author:
Herve Milcent, Niko Karlsson, Oliver Holme (IT-CO)
Function Documentation
_fwSmoothing_getParameters (dyn_string & dpes, bool isArchiveConfig, dyn_int & smoothProcedure, dyn_float & deadband, dyn_float & timeInterval, dyn_string & exceptionInfo)
Gets the parameters of the smoothing in the archiving or smoothing config of a given dpe. NOTE: This function does not check if the smoothing config exists nor if the archive config has smoothing configured (this must be done before using this function)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
isArchiveConfig TRUE to read archive config smoothing parameters FALSE to read smoothing config smoothing parameters
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband deadband value returned here
timeInterval time in seconds returned here
exceptionInfo details of any errors are returned here
Referenced by fwArchive_get(), fwArchive_getMany(), fwSmoothing_get(), and fwSmoothing_getMany().
_fwSmoothing_setParameters (dyn_string dpes, bool isArchiveConfig, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string & exceptionInfo, bool storeInParamHistory = TRUE)
Gets the parameters of the smoothing in the archiving or smoothing config of a given dpe. NOTE: This function does not check if the smoothing config exists nor if the archive config has smoothing configured (this must be done before using this function)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
isArchiveConfig TRUE to read archive config smoothing parameters FALSE to read smoothing config smoothing parameters
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband deadband value returned here
timeInterval time in seconds returned here
exceptionInfo details of any errors are returned here Sets the parameters of the smoothing in the archiving or smoothing config of a given dpe. NOTE: This function does not create the smoothing config nor set up smoothing for the archiving config (this must be done before using this function)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
isArchiveConfig TRUE to read archive config smoothing parameters FALSE to read smoothing config smoothing parameters
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband deadband value
timeInterval time in seconds
exceptionInfo details of any errors are returned here
storeInParamHistory Optional parameter (default value = TRUE) - TRUE to archive the parameter change, else FALSE
Referenced by _fwArchive_setMany(), and fwSmoothing_setMany().
fwSmoothing_delete (string dpe, dyn_string & exceptionInfo)
Deletes the smoothing config for the given data point element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
exceptionInfo details of any errors are returned here
References fwSmoothing_deleteMany().
fwSmoothing_deleteMany (dyn_string dpes, dyn_string & exceptionInfo)
Deletes the smoothing config for the given data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
References _fwConfigs_checkAreConfigsAccessible(), _fwConfigs_convertDriverNumbersToErrorMessage(), and _fwConfigs_delete().
Referenced by fwSmoothing_delete(), and fwSmoothing_deleteMultiple().
fwSmoothing_deleteMultiple (dyn_string dpes, dyn_string & exceptionInfo)
Deletes the smoothing config for the given data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
References fwSmoothing_deleteMany().
fwSmoothing_get (string dpe, bool & configExists, int & smoothProcedure, float & deadband, float & timeInterval, dyn_string & exceptionInfo)
Gets the smoothing config from the given data point element. The function checks that the relevant driver is running. If not it returns an exception saying the config could not be read.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
configExists TRUE if smoothing config exists, else FALSE
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband Deadband value
timeInterval Time interval in seconds
exceptionInfo details of any errors are returned here
References _fwConfigs_checkAreConfigsAccessible(), _fwConfigs_convertDriverNumbersToErrorMessage(), and _fwSmoothing_getParameters().
fwSmoothing_getMany (dyn_string & dpes, dyn_bool & configExists, dyn_int & smoothProcedure, dyn_float & deadband, dyn_float & timeInterval, dyn_string & exceptionInfo)
Gets the smoothing config from the given data point element. The function checks that the relevant driver is running. If not it returns an exception saying the config could not be read.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes data point elements. Passed as reference only for performance reasons. Not modified.
configExists TRUE if smoothing config exists, else FALSE
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband Deadband value
timeInterval Time interval in seconds
exceptionInfo details of any errors are returned here
References _fwConfigs_checkAreConfigsAccessible(), _fwConfigs_convertDriverNumbersToErrorMessage(), and _fwSmoothing_getParameters().
fwSmoothing_getManyWithCheck (dyn_string & dpes, dyn_bool & configExists, dyn_int & smoothProcedure, dyn_float & deadband, dyn_float & timeInterval, dyn_string & exceptionInfo)
Gets the smoothing config from the given data point element. The function checks that the relevant driver is running. If not it returns an exception saying the config could not be read.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes data point elements. Passed as reference only for performance reasons. Not modified.
configExists TRUE if smoothing config exists, else FALSE
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband Deadband value
timeInterval Time interval in seconds
exceptionInfo details of any errors are returned here
References _fwConfigs_checkAreConfigsAccessible(), and _fwConfigs_convertDriverNumbersToErrorMessage().
fwSmoothing_set (string dpe, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo, bool runDriverCheck = FALSE, bool storeInParamHistory = TRUE)
Adds or modifies the smoothing config on the given dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband deadband value
timeInterval time in seconds
exceptionInfo details of any errors are returned here
runDriverCheck Optional parameter (default value = FALSE) - TRUE to check if driver is running before setting config, else FALSE
storeInParamHistory Optional parameter (default value = TRUE) - TRUE to archive the parameter change, else FALSE The necessary driver number must be running in order to successfully create config
References fwSmoothing_setMany().
fwSmoothing_setMany (dyn_string & dpes, dyn_int & smoothProcedure, dyn_float & deadband, dyn_float & timeInterval, dyn_string & exceptionInfo, bool runDriverCheck = FALSE, bool storeInParamHistory = TRUE)
Adds or modifies the smoothing config on the given dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements. Passed as reference only for performance reasons. Not modified.
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time. Passed as reference only for performance reasons. Not modified.
deadband deadband value . Passed as reference only for performance reasons. Not modified.
timeInterval time in seconds. Passed as reference only for performance reasons. Not modified.
exceptionInfo details of any errors are returned here
runDriverCheck Optional parameter (default value = FALSE) - TRUE to check if driver is running before setting config, else FALSE The necessary driver number must be running in order to successfully create config
storeInParamHistory Optional parameter (default value = TRUE) - TRUE to archive the parameter change, else FALSE
References _fwConfigs_checkAreConfigsAccessible(), _fwConfigs_convertDriverNumbersToErrorMessage(), _fwConfigs_setConfigTypeAttribute(), and _fwSmoothing_setParameters().
Referenced by fwSmoothing_set(), and fwSmoothing_setMultiple().
fwSmoothing_setMultiple (dyn_string dpes, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo, bool runDriverCheck = FALSE, bool storeInParamHistory = TRUE)
Adds or modifies the smoothing config on the given dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband deadband value
timeInterval time in seconds
exceptionInfo details of any errors are returned here
runDriverCheck Optional parameter (default value = FALSE) - TRUE to check if driver is running before setting config, else FALSE The necessary driver number must be running in order to successfully create config
storeInParamHistory Optional parameter (default value = TRUE) - TRUE to archive the parameter change, else FALSE
References fwSmoothing_setMany().