fwConfigs: fwArchive.ctl File Reference
fwArchive.ctl File Reference
Functions
fwArchive_deleteMultiple (dyn_string dpes, dyn_string &exceptionInfo)
fwArchive_deleteMany (dyn_string dpes, dyn_string &exceptionInfo)
fwArchive_delete (string dpe, dyn_string &exceptionInfo)
_fwArchive_setOrConfig (dyn_string dpes, bool startArchiving, dyn_string archiveClassDpName, dyn_int archiveType, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE)
fwArchive_setMultiple (dyn_string dpes, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE)
fwArchive_setMany (dyn_string &dpes, dyn_string &archiveClassName, dyn_int &archiveType, dyn_int &smoothProcedure, dyn_float &deadband, dyn_float &timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE, bool activateArchiving=TRUE)
fwArchive_set (string dpe, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE)
fwArchive_configMultiple (dyn_string dpes, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE)
fwArchive_configMany (dyn_string dpes, dyn_string archiveClassName, dyn_int archiveType, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE)
fwArchive_config (string dpe, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo, bool checkClass=TRUE)
fwArchive_getMany (dyn_string &dpes, dyn_bool &configExists, dyn_string &archiveClass, dyn_int &archiveType, dyn_int &smoothProcedure, dyn_float &deadband, dyn_float &timeInterval, dyn_bool &isActive, dyn_string &exceptionInfo)
fwArchive_get (string dpe, bool &configExists, string &archiveClass, int &archiveType, int &smoothProcedure, float &deadband, float &timeInterval, bool &isActive, dyn_string &exceptionInfo)
fwArchive_startMultiple (dyn_string dpes, dyn_string &exceptionInfo)
fwArchive_start (string dpe, dyn_string &exceptionInfo)
fwArchive_stopMultiple (dyn_string dpes, dyn_string &exceptionInfo)
fwArchive_stop (string dpe, dyn_string &exceptionInfo)
_fwArchive_set (string dpe, bool startArchive, string archiveClassDpName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string &exceptionInfo)
_fwArchive_setMany (dyn_string dpes, bool startArchive, dyn_string archiveClassDpName, dyn_int archiveType, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string &exceptionInfo)
fwArchive_convertClassNameToDpName (string archiveClassName, string &archiveDpName, dyn_string &exceptionInfo, string searchSystem="")
fwArchive_convertDpNameToClassName (string archiveDpName, string &archiveClassName, dyn_string &exceptionInfo)
fwArchive_checkClass (string archiveClassDpName, dyn_string dpesToAdd, dyn_string &exceptionInfo)
fwArchive_getClassState (string archiveClassDpName, int &archiveState, string &archiveStateText, dyn_string &exceptionInfo)
fwArchive_getClassStatistics (string archiveClassDpName, int &currentDpes, int &dpesAfterFileSwitch, int &maximumDpes, dyn_string &exceptionInfo, bool refreshClass=TRUE)
fwArchive_getClassFreeSpace (string archiveClassDpName, int &freeSpace, dyn_string &exceptionInfo, bool refreshClass=TRUE)
fwArchive_checkDpesArchived (string archiveClassDpName, dyn_string dpesToCheck, dyn_bool &areArchived, dyn_string &exceptionInfo)
_fwArchive_flagEndOfRefresh (string dpe, int value)
fwArchive_convertDpNameToRDBClassName (string rdbArchiveGroupDpName, string &rdbClassName, dyn_string &exceptionInfo)
fwArchive_convertRDBClassNameToDpName (string rdbClassName, string &rdbArchiveGroupDpName, dyn_string &exceptionInfo, string searchSystem="")
fwArchive_getAllValueArchiveClasses (dyn_string readFromSystems, dyn_string &archiveClasses, dyn_string &archiveClassDps, dyn_string &exceptionInfo)
fwArchive_getAllRDBArchiveClasses (dyn_string readFromSystems, dyn_string &archiveClasses, dyn_string &archiveGroupDps, dyn_string &exceptionInfo, bool includeAlertGroups=FALSE)
Variables
const int fwArchive_CLASS_STOPPED = 0
const int fwArchive_CLASS_ONLINE = 1
const int fwArchive_CLASS_SWAPPED_OUT = 2
const int fwArchive_CLASS_DELETED = 3
const string fwArchive_VALARCH_CLASS_DPTYPE = "_ValueArchive"
const string fwArchive_RDB_CLASS_DPTYPE = "_RDBArchiveGroups"
const int fwArchive_MANAGER_NUMBER_OFFSET = 2
bool fwArchive_REFRESH_IN_PROGRESS = FALSE
Detailed Description
This library contains function associated with the archive config. Functions are provided for getting the current settings, deleting the config and setting the config
Creation Date
28/3/00
Modification History
05/09/11 Marco Boccioli
#86405: index out of range if a dpe has archive not fully parametrized. In case an attribute is not readable, fwArchive_getMany() makes a dpGet attribute per attribute. In this way it saves all the other dpes that are readable.
31/08/11 Marco Boccioli
#86237: fwArchive gives error if dpe is has no archive class name
12/08/11 Marco Boccioli
#85462: Functions *_setMany and *_getMany with parameters as reference.
#86012: Improve performance for fwArchive_getMany(). Function completely re-written.
Oliver: cases for "combined smoothing and time" and " old/new comparison and time" added ability to get/set time interval when available 15/09/00 Oliver: added error handling to save and delete functions
31/01/03 S. Schmeling Changes to set/get for all smoothing procedures 07/02/03 S. Schmeling Changes to set for allowing configuration without starting. New functions: start/stop 06/04/03 S. Schmeling Changed set to old syntax. Will again start archiving immediately. Added function config that will config the archive but not start archiving. 15/01/04 Oliver Holme (IT-CO) Completed major overhaul of whole library 21/01/04 Oliver Holme (IT-CO) Added functionality for relative deadband values Functionality for set and get of smoothing parameters is now called from the fwSmoothing.ctl
Constraints
WARNING: the functions use the dpGet or dpSetWait, problems may occur when using these functions in a working function called by a PVSS (dpConnect) or in a calling function
Usage
Public
PVSS managers
VISION, CTRL
Author:
Oliver Holme, Herve Milcent, Niko Karlsson from exemple from Fernando Varela, changed by Sascha Schmeling
Function Documentation
_fwArchive_flagEndOfRefresh (string dpe, int value)
Work function used to flag the end of a refresh of the archive class statistics
Constraints
Should only be used as a work function to signal the end of a statistical refresh of an archive class
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe name of the data point element connected to (archiveClassDpName + ".statistics.dpElements:_online.._stime")
value the time of the latest update of the datapoint element connected to
_fwArchive_set (string dpe, bool startArchive, string archiveClassDpName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo)
Sets archive config for the given dp element NOTE: This function requires the dp name of the archiving class. It will not perform the search for the dp name from a given archive class name. NOTE: This function does not check that the chosen archive class has enough free space, nor if the class has been deleted
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
startArchive true in order to start the archive immediately, false in order to ONLY configure it
archiveClassDpName the dp name of the archiving class to be used
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
References _fwArchive_setMany().
_fwArchive_setMany (dyn_string dpes, bool startArchive, dyn_string archiveClassDpName, dyn_int archiveType, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string & exceptionInfo)
Sets archive config for the given dp elements NOTE: This function requires the dp name of the archiving class. It will not perform the search for the dp name from a given archive class name. NOTE: This function does not check that the chosen archive class has enough free space, nor if the class has been deleted
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes data point elements
startArchive true in order to start the archive immediately, false in order to ONLY configure it
archiveClassDpName the dp name of the archiving class to be used
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
References _fwSmoothing_setParameters().
Referenced by _fwArchive_set(), and _fwArchive_setOrConfig().
_fwArchive_setOrConfig (dyn_string dpes, bool startArchiving, dyn_string archiveClassDpName, dyn_int archiveType, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE)
Sets archive config for the given dp elements with the option to start or not start the archiving
Constraints
None
Usage
Internal
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
startArchiving true in order to start the archive immediately, false in order to ONLY configure it
archiveClassDpName the dp name of the archiving class to be used
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
References _fwArchive_setMany(), and fwArchive_checkClass().
Referenced by fwArchive_setMany().
fwArchive_checkClass (string archiveClassDpName, dyn_string dpesToAdd, dyn_string & exceptionInfo)
Checks the given archive class to ensure the class has not been deleted and has enough free space to configure a given number of archiving configs
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveClassDpName dp name of the archive class _ValueArchive data point to check
dpesToAdd a list of data point elements you wish to configure with the given class
exceptionInfo details of any errors are returned here
References fwArchive_checkDpesArchived(), fwArchive_getClassFreeSpace(), and fwArchive_getClassState().
Referenced by _fwArchive_setOrConfig().
fwArchive_checkDpesArchived (string archiveClassDpName, dyn_string dpesToCheck, dyn_bool & areArchived, dyn_string & exceptionInfo)
This function can be used to check if a given list of dpes are correctly configured to be archived by a given archive manager. Sometimes, if an archive class is full and more data point elements are added without checking for errors, the additional data points are not added to the archive class (even though the config appears correct) and only a log messages indicates this failure. This function can be used to check that the data point elements are really going to be archived.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveClassDpName dp name of the archive class _ValueArchive data point to check
dpesToCheck the list of dpes that you wish to check are correctly configured for the given archive class
areArchived list of booleans relating to dpes in dpesToCheck. TRUE = archived, FALSE = not archived
exceptionInfo details of any errors are returned here
Referenced by fwArchive_checkClass().
fwArchive_config (string dpe, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE)
Sets archive config for the given dp element without starting the archiving
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
archiveClassName name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
References fwArchive_configMany().
fwArchive_configMany (dyn_string dpes, dyn_string archiveClassName, dyn_int archiveType, dyn_int smoothProcedure, dyn_float deadband, dyn_float timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE)
Sets archive config for the given dp elements without starting the archiving
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
archiveClassName name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
References fwArchive_setMany().
Referenced by fwArchive_config(), and fwArchive_configMultiple().
fwArchive_configMultiple (dyn_string dpes, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE)
Sets archive config for the given dp elements without starting the archiving
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
archiveClassName name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
References fwArchive_configMany().
fwArchive_convertClassNameToDpName (string archiveClassName, string & archiveDpName, dyn_string & exceptionInfo, string searchSystem = "")
Finds the _ValueArchive DP name corresponding to the given archive class name
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveClassName name of the archive class
archiveDpName dp name of the archive class _ValueArchive data point is returned here
exceptionInfo details of any errors are returned here
searchSystem OPTIONAL PARAMETER - default value is "" (search local system) The system on which to perform the lookup of the archive class name
References fwArchive_convertRDBClassNameToDpName().
Referenced by fwArchive_setMany().
fwArchive_convertDpNameToClassName (string archiveDpName, string & archiveClassName, dyn_string & exceptionInfo)
Finds the archive class name corresponding to the given _ValueArchive DP
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveDpName dp name of the archive class _ValueArchive data point
archiveClassName name of the archive class is returned here
exceptionInfo details of any errors are returned here
References fwArchive_convertDpNameToRDBClassName().
Referenced by fwArchive_get(), and fwArchive_getMany().
fwArchive_convertDpNameToRDBClassName (string rdbArchiveGroupDpName, string & rdbClassName, dyn_string & exceptionInfo)
Finds the RDB archive class name corresponding to the given _RDBArchiveGroups DP
Constraints
Only works for RDB archiving classes - not traditional _ValueArchive classes
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
rdbArchiveGroupDpName dp name of the RDB archive group _RDBArchiveGroups data point
rdbClassName name of the archive class is returned here
exceptionInfo details of any errors are returned here
Referenced by fwArchive_convertDpNameToClassName().
fwArchive_convertRDBClassNameToDpName (string rdbClassName, string & rdbArchiveGroupDpName, dyn_string & exceptionInfo, string searchSystem = "")
Finds the _RDBArchiveGroups DP name corresponding to the given RDB archive class name
Constraints
Only works for RDB archiving classes - not traditional _ValueArchive classes The RDB archive class name must be given as displayed in the PVSS panels - e.g. RDB-XX) GroupName
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
rdbClassName name of the RDB archive class
rdbArchiveGroupDpName dp name of the RDB archive group _RDBArchiveGroups data point is returned here
exceptionInfo details of any errors are returned here
searchSystem OPTIONAL PARAMETER - default value is "" (search local system) The system on which to perform the lookup of the archive class name
Referenced by fwArchive_convertClassNameToDpName().
fwArchive_delete (string dpe, dyn_string & exceptionInfo)
Deletes the archive config for the given data point element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
exceptionInfo details of any errors are returned here
References _fwConfigs_delete().
fwArchive_deleteMany (dyn_string dpes, dyn_string & exceptionInfo)
Deletes the archive config for the given data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
References _fwConfigs_delete().
fwArchive_deleteMultiple (dyn_string dpes, dyn_string & exceptionInfo)
Deletes the archive config for the given data point elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
References _fwConfigs_delete().
fwArchive_get (string dpe, bool & configExists, string & archiveClass, int & archiveType, int & smoothProcedure, float & deadband, float & timeInterval, bool & isActive, dyn_string & exceptionInfo)
Returns details of the archive config on the given dp element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
configExists TRUE - archive config existing, FALSE - archive config is not existing
archiveClass name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
isActive TRUE if archiving of this dpe is active, else FALSE
exceptionInfo details of any errors are returned here
References _fwSmoothing_getParameters(), and fwArchive_convertDpNameToClassName().
fwArchive_getAllRDBArchiveClasses (dyn_string readFromSystems, dyn_string & archiveClasses, dyn_string & archiveGroupDps, dyn_string & exceptionInfo, bool includeAlertGroups = FALSE)
Finds all the RDB Archiving Group classes and returns the class names (for display) and the group dps (for writing to the config)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
readFromSystems The systems to read from - the list of classes returned is only those classes that are available on every one of the named systems
archiveClasses The list of RDB archive group names is returned here
archiveGroupDps The list of _RDBArchiveGroups data point names is returned here
exceptionInfo Details of any errors are returned here
includeAlertGroups OPTIONAL PARAMETER - default value = FALSE If set to FALSE, only EVENT archive groups are returned If set to TRUE, both EVENT and ALERT archive groups are returned
fwArchive_getAllValueArchiveClasses (dyn_string readFromSystems, dyn_string & archiveClasses, dyn_string & archiveClassDps, dyn_string & exceptionInfo)
Finds all the NOT DELETED Value Archive classes and returns the class names (for display) and the class dps (for writing to the config)
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
readFromSystems The systems to read from - the list of classes returned is only those classes that are available on every one of the named systems
archiveClasses The list of archive class names is returned here
archiveClassDps The list of _ValueArchive data point names is returned here
exceptionInfo Details of any errors are returned here
fwArchive_getClassFreeSpace (string archiveClassDpName, int & freeSpace, dyn_string & exceptionInfo, bool refreshClass = TRUE)
Gets the amount of additional data point elements that can be added to a given archive class The value returned is based on the number of dpes in the archive currently, not the number after the next file switch
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveClassDpName dp name of the archive class _ValueArchive data point to check
freeSpace the number of dpes that can be added to the archive is returned here
exceptionInfo details of any errors are returned here
refreshClass Optional parameter. Default value TRUE. If TRUE, force class to refresh statistics before getting values (maybe slow) If FALSE, get current values which may be out of date
References fwArchive_getClassStatistics().
Referenced by fwArchive_checkClass().
fwArchive_getClassState (string archiveClassDpName, int & archiveState, string & archiveStateText, dyn_string & exceptionInfo)
Gets the state of the given archive class
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveClassDpName dp name of the archive class _ValueArchive data point to check
archiveState the archive state is returned here fwArchive_CLASS_STOPPED = Archive manager not running fwArchive_CLASS_ONLINE = Archive manager running fwArchive_CLASS_SWAPPED_OUT = Archive is currently swapped out fwArchive_CLASS_DELETED = Archive has been deleted
archiveStateText a text representation of the state is returned here
exceptionInfo details of any errors are returned here
Referenced by fwArchive_checkClass(), and fwArchive_getClassStatistics().
fwArchive_getClassStatistics (string archiveClassDpName, int & currentDpes, int & dpesAfterFileSwitch, int & maximumDpes, dyn_string & exceptionInfo, bool refreshClass = TRUE)
Gets the statistics of the given archive class
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
archiveClassDpName dp name of the archive class _ValueArchive data point to check
currentDpes the number of dpes currently in the archive is returned here
dpesAfterFileSwitch the number of dpes that will be in the archive after a file switch is returned here
maximumDpes the maximum number of dpes for this class is returned here
exceptionInfo details of any errors are returned here
refreshClass Optional parameter. Default value TRUE. If TRUE, force class to refresh statistics before getting values (maybe slow) If FALSE, get current values which may be out of date
References fwArchive_getClassState().
Referenced by fwArchive_getClassFreeSpace().
fwArchive_getMany (dyn_string & dpes, dyn_bool & configExists, dyn_string & archiveClass, dyn_int & archiveType, dyn_int & smoothProcedure, dyn_float & deadband, dyn_float & timeInterval, dyn_bool & isActive, dyn_string & exceptionInfo)
Returns details of the archive config on the given list of dp elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes the list of data point elements. Passed as reference only for performance reasons. Not modified.
configExists TRUE - archive config existing, FALSE - archive config is not existing
archiveClass name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
isActive TRUE if archiving of this dpe is active, else FALSE
exceptionInfo details of any errors are returned here
References _fwSmoothing_getParameters(), and fwArchive_convertDpNameToClassName().
fwArchive_set (string dpe, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE)
Sets archive config for the given dp element and start the archiving
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
archiveClassName name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
References fwArchive_setMany().
fwArchive_setMany (dyn_string & dpes, dyn_string & archiveClassName, dyn_int & archiveType, dyn_int & smoothProcedure, dyn_float & deadband, dyn_float & timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE, bool activateArchiving = TRUE)
Sets archive config for the given dp elements and start the archiving
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements. Passed as reference only for performance reasons. Not modified.
archiveClassName name of the archive class for the config (not archive class dp name) Passed as reference only for performance reasons. Not modified.
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing Passed as reference only for performance reasons. Not modified.
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time. Passed as reference only for performance reasons. Not modified.
deadband archive deadband. Passed as reference only for performance reasons. Not modified.
timeInterval archive time interval Passed as reference only for performance reasons. Not modified.
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
activateArchiving Optional parameter. For internal use - to configure but not start archiving, please use fwArchive_configMany. Default value = TRUE, archiving is started immediately. Else if set to FALSE archiving is configured but not started.
References _fwArchive_setOrConfig(), and fwArchive_convertClassNameToDpName().
Referenced by fwArchive_configMany(), fwArchive_set(), and fwArchive_setMultiple().
fwArchive_setMultiple (dyn_string dpes, string archiveClassName, int archiveType, int smoothProcedure, float deadband, float timeInterval, dyn_string & exceptionInfo, bool checkClass = TRUE)
Sets archive config for the given dp elements and start the archiving
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
archiveClassName name of the archive class for the config (not archive class dp name)
archiveType DPATTR_ARCH_PROC_VALARCH: no smoothing, DPATTR_ARCH_PROC_SIMPLESM: value dependent + deadband/old-new comparison smoothing
smoothProcedure DPATTR_VALUE_SMOOTH : value dependent, DPATTR_VALUE_REL_SMOOTH : relative value dependent, DPATTR_TIME_SMOOTH : time dependent, DPATTR_TIME_AND_VALUE_SMOOTH : value AND time dependent, DPATTR_TIME_AND_VALUE_REL_SMOOTH : relative value AND time dependent, DPATTR_TIME_OR_VALUE_SMOOTH : value OR time dependent, DPATTR_TIME_OR_VALUE_REL_SMOOTH : relative value OR time dependent, DPATTR_COMPARE_OLD_NEW : old-new comparison, DPATTR_OLD_NEW_AND_TIME_SMOOTH : old-new comparison AND time, DPATTR_OLD_NEW_OR_TIME_SMOOTH : old-new comparison OR time
deadband archive deadband
timeInterval archive time interval
exceptionInfo details of any errors are returned here
checkClass Optional parameter. Default value TRUE. If TRUE, check class is not deleted and has enough free space. If FALSE skip checks.
References fwArchive_setMany().
fwArchive_start (string dpe, dyn_string & exceptionInfo)
Starts archiving for the given dp element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
exceptionInfo details of any errors are returned here
References fwArchive_startMultiple().
fwArchive_startMultiple (dyn_string dpes, dyn_string & exceptionInfo)
Starts archiving for the given dp elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
References _fwConfigs_setConfigTypeAttribute().
Referenced by fwArchive_start().
fwArchive_stop (string dpe, dyn_string & exceptionInfo)
Stops archiving for the given dp element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element
exceptionInfo details of any errors are returned here
References fwArchive_stopMultiple().
fwArchive_stopMultiple (dyn_string dpes, dyn_string & exceptionInfo)
Stops archiving for the given dp elements
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpes list of data point elements
exceptionInfo details of any errors are returned here
References _fwConfigs_setConfigTypeAttribute().
Referenced by fwArchive_stop().