fwConfigs: fwFormat.ctl File Reference
fwFormat.ctl File Reference
Functions
fwFormat_set (string dpe, string sFormat, dyn_string &exceptionInfo)
fwFormat_setMultiple (dyn_string dsDpe, string sFormat, dyn_string &exceptionInfo)
fwFormat_setMany (dyn_string &dsDpe, dyn_string &dsFormat, dyn_string &exceptionInfo)
fwFormat_get (string dpe, bool &bFormatExists, string &sFormat, dyn_string &exceptionInfo)
fwFormat_getMany (dyn_string &dsDpe, dyn_bool &dbFormatExists, dyn_string &dsFormat, dyn_string &exceptionInfo)
fwFormat_delete (string dpe, dyn_string &exceptionInfo)
fwFormat_deleteMultiple (dyn_string dsDpe, dyn_string &exceptionInfo)
fwFormat_deleteMany (dyn_string dsDpe, dyn_string &exceptionInfo)
fwFormat_getMultiple (dyn_string dsDpe, dyn_bool &dbFormatExists, dyn_string &dsFormat, dyn_string &exceptionInfo)
Detailed Description
This library contains function associated with the Format part of the common config. Functions allows to set, get and delete the Format of a dpe or multiple dpes
Creation Date
29/01/2004
Modification History
12/08/11 Marco Boccioli
#85462: Functions *_setMany and *_getMany with parameters as reference.
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Author:
Geraldine Thomas, Oliver Holme (IT-CO)
Function Documentation
fwFormat_delete (string dpe, dyn_string & exceptionInfo)
Delete the Format of the dpe. The format string is reset to ""
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element to configure
exceptionInfo output, details of any exceptions are returned here
Referenced by fwFormat_deleteMany().
fwFormat_deleteMany (dyn_string dsDpe, dyn_string & exceptionInfo)
Delete the Format of several dpes. The format strings are reset to ""
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dsDpe input, data point elements to configure
exceptionInfo output, details of any exceptions are returned here
References fwFormat_delete().
Referenced by fwFormat_deleteMultiple().
fwFormat_deleteMultiple (dyn_string dsDpe, dyn_string & exceptionInfo)
Delete the Format of several dpes. The format strings are reset to ""
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dsDpe input, data point elements to configure
exceptionInfo output, details of any exceptions are returned here
References fwFormat_deleteMany().
fwFormat_get (string dpe, bool & bFormatExists, string & sFormat, dyn_string & exceptionInfo)
Get the Format of the dpe
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe data point element to configure
bFormatExists TRUE if format is set, FALSE if no format is set
sFormat output, return the Format of the dpe
exceptionInfo output, details of any exceptions are returned here
Referenced by fwFormat_getMany().
fwFormat_getMany (dyn_string & dsDpe, dyn_bool & dbFormatExists, dyn_string & dsFormat, dyn_string & exceptionInfo)
Get the Format of several dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dsDpe input, data point elements to configure. Passed as reference only for performance reasons. Not modified.
dbFormatExists Lists of bools indicating if format is set - TRUE if format is set, FALSE if no format is set
dsFormat output, return the current Format of the dpes
exceptionInfo output, details of any exceptions are returned here
References fwFormat_get().
Referenced by fwFormat_getMultiple().
fwFormat_getMultiple (dyn_string dsDpe, dyn_bool & dbFormatExists, dyn_string & dsFormat, dyn_string & exceptionInfo)
DEPRECATED - function to get the Format of several dpes
Function is replaced by fwFormat_getMany
References fwFormat_getMany().
fwFormat_set (string dpe, string sFormat, dyn_string & exceptionInfo)
set the Format of a single data point element
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dpe input, data point element to configure
sFormat input, string Format to set
exceptionInfo output, details of any exceptions are returned here
Referenced by fwFormat_setMany(), and fwFormat_setMultiple().
fwFormat_setMany (dyn_string & dsDpe, dyn_string & dsFormat, dyn_string & exceptionInfo)
Set differing Formats for several dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dsDpe input, data point elements to configure. Passed as reference only for performance reasons. Not modified.
dsFormat input, list of Formats to set to dpes. Passed as reference only for performance reasons. Not modified.
exceptionInfo output, details of any exceptions are returned here
References fwFormat_set().
fwFormat_setMultiple (dyn_string dsDpe, string sFormat, dyn_string & exceptionInfo)
Set the same Format for several dpes
Constraints
None
Usage
Public
PVSS managers
VISION, CTRL
Parameters:
dsDpe input, data point elements to configure
sFormat input, string Format to set
exceptionInfo output, details of any exceptions are returned here
References fwFormat_set().